#![cfg(test)]

use std::sync::{Mutex, PoisonError};

use amm_pool_contract::{ConstantProductPool, ConstantProductPoolClient};
use budget_macros::{
    budget_cpu_lt, budget_lt, budget_mem_lt, budget_read_bytes_lt, budget_write_bytes_lt,
};
use soroban_sdk::{testutils::Address as _, Address, Env};

/// Serialises all JSON-config tests so they never read stale `budget.json`
/// content written by another test running in parallel.
static BUDGET_JSON_LOCK: Mutex<()> = Mutex::new(());

/// A Drop guard that writes `budget.json` on creation and removes it on drop
/// (including during stack unwinding from a panic). The `_lock` field prevents
/// other JSON-config tests from overwriting the file while the assertion runs.
struct BudgetJsonGuard {
    _lock: std::sync::MutexGuard<'static, ()>,
}

impl BudgetJsonGuard {
    fn create(content: &str) -> Self {
        let lock = BUDGET_JSON_LOCK
            .lock()
            .unwrap_or_else(PoisonError::into_inner);
        std::fs::write("budget.json", content).expect("failed to write budget.json");
        BudgetJsonGuard { _lock: lock }
    }
}

impl Drop for BudgetJsonGuard {
    fn drop(&mut self) {
        let _ = std::fs::remove_file("budget.json");
    }
}

/// Path to the workspace-root `tier-a-limits.env` relative to this test's
/// CWD. The file is auto-generated by `cargo budget-report --derive-limits`
/// (see [derive.rs]). Every `env_file = TIER_A_LIMITS_FILE` annotation in
/// this crate reads exactly the keys here, with provenance documented in the
/// sibling `tier-a-limits.provenance.md`.
const TIER_A_LIMITS_FILE: &str = "../tier-a-limits.env";

fn setup_wasm(env: &Env) -> (ConstantProductPoolClient<'_>, Address) {
    let wasm_path = "../target/wasm32v1-none/release/amm_pool_contract.wasm";
    let wasm = std::fs::read(wasm_path).expect("WASM file not found, did you run cargo build?");
    // Register the precompiled WASM so measurements exercise the contract in
    // the host's Wasm VM rather than as linked-in Rust (raw Rust estimates
    // undercount costs — see MEASUREMENTS.md). `Env::register` accepts raw
    // WASM bytes: `Register` is implemented for `&[u8]`, and it drives the
    // exact same host path the deprecated `register_contract_wasm` used
    // (`upload_contract_wasm` + `CreateContractV2`, no constructor args),
    // verified against soroban-sdk 22.0.11 (Issue #472).
    let contract_id = env.register(wasm.as_slice(), ());
    let client = ConstantProductPoolClient::new(env, &contract_id);

    let user = Address::generate(env);

    client.initialize();

    env.mock_all_auths();

    env.cost_estimate().budget().reset_unlimited();

    (client, user)
}

/// The fixed cost of invoking *any* export on the WASM contract, measured by
/// invoking the deliberately-empty `noop`.
///
/// Every invocation in the local test VM re-parses and re-instantiates the
/// whole module before contract logic runs. That floor is ~3.1M CPU
/// instructions — an order of magnitude more than most of these functions
/// actually cost — so a raw local measurement is dominated by it and cannot be
/// compared against the Tier B *network* limits in `tier-a-limits.env`.
/// Subtracting this leaves the marginal cost, which is what those limits
/// describe.
///
/// Cached: the floor is deterministic for a given module, and re-measuring it
/// per assertion would double the module instantiations in the suite.
fn wasm_baseline() -> (u64, u64) {
    static BASELINE: std::sync::OnceLock<(u64, u64)> = std::sync::OnceLock::new();
    *BASELINE.get_or_init(|| {
        let env = Env::default();
        let (client, _user) = setup_wasm(&env);
        client.noop();
        let budget = env.cost_estimate().budget();
        (budget.cpu_instruction_cost(), budget.memory_bytes_cost())
    })
}

/// CPU half of [`wasm_baseline`], for `baseline = …` / `cpu_baseline = …`.
fn baseline_cpu() -> u64 {
    wasm_baseline().0
}

/// Memory half of [`wasm_baseline`], for `baseline = …` / `mem_baseline = …`.
fn baseline_mem() -> u64 {
    wasm_baseline().1
}

#[test]
fn test_budget_raw_rust() {
    let env = Env::default();
    let contract_id = env.register(ConstantProductPool, ());
    let client = ConstantProductPoolClient::new(&env, &contract_id);

    env.cost_estimate().budget().reset_unlimited();

    client.do_expensive_work(&10_000);

    let budget = env.cost_estimate().budget();
    println!("=== RAW RUST LOCAL ===");
    println!("CPU instructions: {}", budget.cpu_instruction_cost());
    println!("Memory bytes: {}", budget.memory_bytes_cost());
}

#[test]
#[budget_cpu_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__SCENARIO__FULL_WORKFLOW__CPU", baseline = baseline_cpu())]
fn test_budget_wasm() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

/// Measures CPU instruction cost of `do_expensive_work` across multiple input
/// sizes in WASM mode, for gap-vs-input-size analysis.
#[test]
fn test_measure_gap_vs_input_size() {
    let wasm_path = "../target/wasm32v1-none/release/amm_pool_contract.wasm";
    let wasm = std::fs::read(wasm_path).expect("WASM file not found");
    let sizes = [1000, 10000, 50000, 100000];

    for &n in &sizes {
        // --- Wasm measurement ---
        let env = Env::default();
        let contract_id = env.register(wasm.as_slice(), ());
        let client = ConstantProductPoolClient::new(&env, &contract_id);
        env.cost_estimate().budget().reset_unlimited();
        client.do_expensive_work(&n);
        let wasm_cpu = env.cost_estimate().budget().cpu_instruction_cost();
        println!("  n={:>6} | local WASM CPU: {:>10}", n, wasm_cpu);
    }
}

#[test]
#[budget_lt(
    cpu = env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__DEPOSIT__CPU",
    mem = env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__DEPOSIT__MEM",
    cpu_baseline = baseline_cpu(),
    mem_baseline = baseline_mem()
)]
fn test_budget_require_auth_deposit() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
}

#[test]
#[budget_cpu_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__SCENARIO__FULL_WORKFLOW__CPU", baseline = baseline_cpu())]
fn test_budget_require_auth_swap() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
}

#[test]
#[budget_cpu_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__SCENARIO__FULL_WORKFLOW__CPU", baseline = baseline_cpu())]
fn test_budget_require_auth_withdraw() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[budget_cpu_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__REQUIRE_AUTH_ONLY__CPU", baseline = baseline_cpu())]
fn test_budget_require_auth_isolated() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.require_auth_only(&user);
}

#[test]
#[budget_mem_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__REQUIRE_AUTH_ONLY__MEM", baseline = baseline_mem())]
fn test_budget_require_auth_isolated_mem() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.require_auth_only(&user);
}

#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_cpu_lt(1000)] // Deliberate regression: require_auth costs well above 1K CPU
fn test_budget_require_auth_deliberate_regression_cpu() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.require_auth_only(&user);
}

#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_mem_lt(1)] // Deliberate regression: any real memory cost exceeds an impossible 1-byte limit
fn test_budget_require_auth_deliberate_regression_mem() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.require_auth_only(&user);
}

#[test]
#[budget_cpu_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__EXTEND_INSTANCE_TTL__CPU", baseline = baseline_cpu())]
fn test_budget_extend_ttl_isolated() {
    let env = Env::default();
    let (client, _user) = setup_wasm(&env);

    client.extend_instance_ttl(&100, &10_000);
}

#[test]
#[budget_mem_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__EXTEND_INSTANCE_TTL__MEM", baseline = baseline_mem())]
fn test_budget_extend_ttl_isolated_mem() {
    let env = Env::default();
    let (client, _user) = setup_wasm(&env);

    client.extend_instance_ttl(&100, &10_000);
}

#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_cpu_lt(1000)] // Deliberate regression: extend_ttl costs well above 1K CPU
fn test_budget_extend_ttl_deliberate_regression_cpu() {
    let env = Env::default();
    let (client, _user) = setup_wasm(&env);

    client.extend_instance_ttl(&100, &10_000);
}

#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_mem_lt(1)] // Deliberate regression: any real memory cost exceeds an impossible 1-byte limit
fn test_budget_extend_ttl_deliberate_regression_mem() {
    let env = Env::default();
    let (client, _user) = setup_wasm(&env);

    client.extend_instance_ttl(&100, &10_000);
}

#[test]
#[budget_cpu_lt(env_file = TIER_A_LIMITS_FILE, env = "TIER_A__AMM_POOL_CONTRACT__SCENARIO__FULL_WORKFLOW__CPU", baseline = baseline_cpu())]
fn test_budget_macro_gated() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_cpu_lt(1000000)]
fn test_budget_macro_deliberate_regression() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_mem_lt(1)]
fn test_budget_macro_mem_deliberate_regression() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[budget_cpu_lt(env = "TEST_MAX_CPU", baseline = baseline_cpu())]
fn test_budget_macro_dynamic_env() {
    let budget_env_resolve = |var: &str| -> Option<String> {
        if var == "TEST_MAX_CPU" {
            Some("3000000".to_string())
        } else {
            None
        }
    };
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[budget_cpu_lt(env = "TEST_MAX_CPU_FALLBACK")]
fn test_budget_macro_dynamic_env_fallback() {
    let budget_env_resolve = |_var: &str| -> Option<String> { None };
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

// ---------------------------------------------------------------------------
// JSON config tests
// ---------------------------------------------------------------------------

#[test]
#[budget_cpu_lt(config = "cpu_instructions", baseline = baseline_cpu())]
fn test_budget_macro_json_config_valid() {
    let _guard = BudgetJsonGuard::create(r#"{"cpu_instructions": 3000000}"#);
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[budget_mem_lt(config = "memory_bytes")]
fn test_budget_macro_json_config_mem_valid() {
    let _guard = BudgetJsonGuard::create(r#"{"memory_bytes": 5000000}"#);
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[should_panic(expected = "key 'non_existent_key' not found or invalid in budget.json")]
#[budget_cpu_lt(config = "non_existent_key")]
fn test_budget_macro_json_config_missing_key() {
    let _guard = BudgetJsonGuard::create(r#"{"some_other_key": 100}"#);
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
#[budget_cpu_lt(config = "cpu_instructions_deliberate")]
fn test_budget_macro_json_config_deliberate_regression() {
    let _guard = BudgetJsonGuard::create(r#"{"cpu_instructions_deliberate": 1}"#);
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[should_panic(expected = "key 'cpu_instructions' not found or invalid in budget.json")]
#[budget_cpu_lt(config = "cpu_instructions")]
fn test_budget_macro_json_config_missing_key_empty_config() {
    // Empty JSON object -> requested key won't be found -> macro panics.
    let _guard = BudgetJsonGuard::create(r#"{}"#);
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

#[test]
#[should_panic(expected = "key 'cpu_instructions' not found or invalid in budget.json")]
#[budget_cpu_lt(config = "cpu_instructions")]
fn test_budget_macro_json_config_invalid_json() {
    let _guard = BudgetJsonGuard::create(r#"this is not valid json at all"#);
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

// ---------------------------------------------------------------------------
// Macro hygiene regression test
//
// Verify that #[budget_cpu_lt] and #[budget_mem_lt] do not leak their
// injected temporaries (budget, cpu_cost, mem_cost, limit_u64) into the
// user's namespace by declaring identically-named locals in the test body.
// These tests must compile and assert correctly.
// ---------------------------------------------------------------------------

#[test]
#[budget_cpu_lt(5000000)]
fn test_macro_hygiene_cpu_shadows_budget_and_limit() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    // Deliberately shadow the macro's injected identifiers.
    let budget = "this_is_not_a_soroban_budget";
    let cpu_cost = "also_not_a_cost";
    let limit_u64 = 9999;

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);

    // Verify our shadowing locals are intact after the macro's injected
    // assertions run.
    assert_eq!(budget, "this_is_not_a_soroban_budget");
    assert_eq!(cpu_cost, "also_not_a_cost");
    assert_eq!(limit_u64, 9999);
}

#[test]
#[budget_mem_lt(2000000)]
fn test_macro_hygiene_mem_shadows_budget_and_limit() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    // Deliberately shadow the macro's injected identifiers.
    let budget = "shadowed_budget";
    let mem_cost = "shadowed_mem_cost";
    let limit_u64 = 42;

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);

    assert_eq!(budget, "shadowed_budget");
    assert_eq!(mem_cost, "shadowed_mem_cost");
    assert_eq!(limit_u64, 42);
}

#[test]
#[budget_write_bytes_lt(5_000_000)]
fn test_macro_hygiene_write_bytes_shadows_budget_and_limit() {
    let env = Env::default();
    let contract_id = env.register(ConstantProductPool, ());
    let client = ConstantProductPoolClient::new(&env, &contract_id);

    env.cost_estimate().budget().reset_unlimited();

    // Deliberately shadow the macro's injected identifiers.
    let budget = "i_am_a_string_not_a_budget";
    let write_bytes_cost = "also_string_not_cost";
    let limit_u64 = 777;

    client.do_write_heavy_work(&50);

    assert_eq!(budget, "i_am_a_string_not_a_budget");
    assert_eq!(write_bytes_cost, "also_string_not_cost");
    assert_eq!(limit_u64, 777);
}

#[test]
#[budget_read_bytes_lt(5_000_000)]
fn test_macro_hygiene_read_bytes_shadows_budget_and_limit() {
    let env = Env::default();
    let contract_id = env.register(ConstantProductPool, ());
    let client = ConstantProductPoolClient::new(&env, &contract_id);

    env.cost_estimate().budget().reset_unlimited();

    // Deliberately shadow the macro's injected identifiers.
    let budget = "i_am_a_string_not_a_budget";
    let read_bytes_cost = "also_string_not_cost";
    let limit_u64 = 777;

    client.do_read_heavy_work(&50);

    assert_eq!(budget, "i_am_a_string_not_a_budget");
    assert_eq!(read_bytes_cost, "also_string_not_cost");
    assert_eq!(limit_u64, 777);
}

#[test]
#[budget_read_bytes_lt(
    env_file = TIER_A_LIMITS_FILE,
    env = "TIER_A__AMM_POOL_CONTRACT__SCENARIO__FULL_WORKFLOW__READ",
    baseline = baseline_mem()
)]
fn test_budget_read_bytes_full_workflow() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);
}

/// Fixture: contract invocation stays within the read bytes budget.
///
/// Runs a deposit + swap + withdraw cycle against the WASM contract and
/// asserts that the ledger read bytes reported by
/// `env.cost_estimate().resources().read_bytes` do not exceed a generous
/// upper bound.  This test is expected to pass under normal conditions and
/// acts as a regression guard that will fail if storage reads grow
/// unexpectedly.
#[test]
fn test_read_bytes_budget_within_limit() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);

    let read_bytes = env.cost_estimate().resources().read_bytes;
    println!("Read bytes (WASM deposit+swap+withdraw): {read_bytes}");

    // Generous upper bound (measured 25,784 locally) — tighten once a clean
    // baseline is recorded.
    //
    // `read_bytes` counts the contract's Wasm module, which the host reads from
    // the ledger on every invocation, so this figure tracks module *size* far
    // more than it tracks storage access. Adding the `noop` baseline export
    // grew the module 24,505 -> 25,380 bytes, taking read_bytes 24,912 ->
    // 25,784 and past the old 25,000 bound. The ceiling moves rather than the
    // export being dropped, because `noop` is what makes every CPU/memory
    // assertion in this file measure marginal cost instead of the
    // instantiation floor.
    assert!(
        read_bytes < 30_000,
        "Read bytes {read_bytes} exceeded the expected limit of 30,000 \
         - local estimate, real network cost may differ significantly in either direction"
    );
}

/// Fixture: deliberate regression — contract exceeds the read bytes budget.
///
/// Sets an impossibly tight read bytes limit (1 byte) to demonstrate what a
/// read-bytes budget breach looks like.  The `#[should_panic]` attribute
/// documents the expected failure message so that the test suite treats this
/// as a passing regression fixture rather than a real failure.
#[test]
#[should_panic(
    expected = "local estimate, real network cost may differ significantly in either direction"
)]
fn test_read_bytes_budget_exceeds_limit() {
    let env = Env::default();
    let (client, user) = setup_wasm(&env);

    client.deposit(&user, &10_000_i128, &10_000_i128);
    client.swap(&user, &true, &100_i128, &90_i128);
    client.withdraw(&user, &1_000_i128, &900_i128, &900_i128);

    let read_bytes = env.cost_estimate().resources().read_bytes;
    println!("Read bytes (deliberate regression): {read_bytes}");

    // Deliberately impossible limit: any real WASM invocation will read more
    // than 1 byte from ledger storage, so this assertion always fires.
    let limit: u32 = 1;
    assert!(
        read_bytes < limit,
        "Read bytes {read_bytes} exceeded the expected limit of {limit} \
         - local estimate, real network cost may differ significantly in either direction"
    );
}

/// Measures the local WASM read-bytes cost of `do_read_heavy_work` for the
/// storage-read gap measurement table in `MEASUREMENTS.md`.
///
/// Writes 100 keys (256 bytes each) to instance storage, then reads them
/// all back.  The read-bytes figure is the isolated local estimate for the
/// storage-read gap analysis; the CPU and memory figures are captured
/// alongside so the entry has parity with the existing calibration table.
///
/// # Running
///
/// ```bash
/// cargo build --target wasm32v1-none --release -p amm-pool-contract
/// cargo test -p amm-pool-contract test_storage_read_wasm_local -- --nocapture
/// ```
#[test]
fn test_storage_read_wasm_local() {
    let wasm_path = "../target/wasm32v1-none/release/amm_pool_contract.wasm";
    let wasm = std::fs::read(wasm_path).expect("WASM file not found, did you run cargo build?");

    let env = Env::default();
    let contract_id = env.register(wasm.as_slice(), ());
    let client = ConstantProductPoolClient::new(&env, &contract_id);

    env.cost_estimate().budget().reset_unlimited();

    // 100 keys × 256 bytes = 25 600 bytes of reads, plus per-key overhead.
    client.do_read_heavy_work(&100);

    let budget = env.cost_estimate().budget();
    let read_bytes = env.cost_estimate().resources().read_bytes;
    let cpu = budget.cpu_instruction_cost();
    let mem = budget.memory_bytes_cost();

    println!("=== STORAGE_READ_WASM_LOCAL ===");
    println!("READ_BYTES={}", read_bytes);
    println!("CPU_INSTRUCTIONS={}", cpu);
    println!("MEMORY_BYTES={}", mem);
}
