use anyhow::{Context, Result};
use cargo_metadata::{CrateType, MetadataCommand};
use clap::Parser;
use indicatif::{ProgressBar, ProgressStyle};
use serde::Serialize;
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::fmt;
use std::io::Write;
use std::path::Path;
use std::path::PathBuf;
use std::str::FromStr;

mod args;
use crate::args::ArgSpec;

use std::process::{Command, Stdio};
use std::sync::{Arc, Condvar, Mutex};
use std::thread;
use std::time::{Duration, Instant};
use stellar_xdr::{Limits, ReadXdr, SorobanTransactionData};
use tabled::{Table, Tabled};
use wasmparser::Parser as WasmParser;

/// Maximum number of total deployment attempts (1 initial + 3 retries)
/// when friendbot funding is suspected to have failed transiently
/// (rate-limiting, network hiccups, or the account not being fully
/// confirmed on-ledger yet).
const MAX_DEPLOY_ATTEMPTS: u32 = 4;

/// Initial backoff delay between deployment retries. Doubles on each
/// subsequent attempt (2 s → 4 s → 8 s).
const INITIAL_RETRY_DELAY_SECS: u64 = 2;

/// Default maximum number of functions to simulate concurrently.
/// Public RPC endpoints rate-limit, so keep this conservative.
const DEFAULT_CONCURRENCY: usize = 4;

/// Simple counting semaphore for bounding concurrent work.
struct Semaphore {
    count: Mutex<usize>,
    condvar: Condvar,
}

impl Semaphore {
    fn new(count: usize) -> Self {
        Self {
            count: Mutex::new(count),
            condvar: Condvar::new(),
        }
    }

    fn acquire(&self) {
        let mut count = self.count.lock().unwrap();
        while *count == 0 {
            count = self.condvar.wait(count).unwrap();
        }
        *count -= 1;
    }

    fn release(&self) {
        let mut count = self.count.lock().unwrap();
        *count += 1;
        self.condvar.notify_one();
    }
}

/// Commented budget.toml template written by `cargo budget-report --init`.
const BUDGET_TOML_TEMPLATE: &str = r#"# -- Budget report configuration ---------------------------------------------
# Generated by `cargo budget-report --init`.
# See https://github.com/Tollcraft/soroban-budget-assert for the full reference.

# Target network for contract simulation.
# Supported values: "testnet", "futurenet", "local" (for a local container),
# or any custom network defined in your Stellar CLI config.
network = "testnet"

# Stellar source account keypair name (as configured in your Stellar CLI).
source = "alice"

# -- Per-function configuration ----------------------------------------------
# Declare one section per contract function you want to simulate and
# optionally enforce limits against.
#
#   [functions.<function_name>]
#
#   # --- Arguments -------------------------------------------------------
#   # Two formats are supported.
#   #
#   # Legacy flat string format (recommended for simple flag-based args):
#   #   args = ["--flag", "value"]
#   #
#   # Typed format (recommended for real contract simulation with typed
#   # function parameters):
#   #   args = [
#   #     { address = "alice" },       # Stellar address or named identity
#   #     { i128     = "1000" },       # 128-bit signed integer (string for precision)
#   #     { symbol   = "USDC" },       # Soroban symbol
#   #     { bool     = true },         # boolean
#   #     { string   = "hello" },      # string value
#   #     { u32      = 42 },           # unsigned 32-bit integer
#   #     { i32      = -7 },           # signed 32-bit integer
#   #     { u64      = 1000000 },      # unsigned 64-bit integer
#   #     { i64      = -1000000 },     # signed 64-bit integer
#   #     { u128     = "340282366920938463463374607431768211455" }, # u128 as string
#   #     { bytes    = "0102ff" },     # raw bytes as hex string
#   #     { vec      = [{ u32 = 1 }, { u32 = 2 }] },  # vector of typed values
#   #     { map      = { name = { symbol = "alice" }, balance = { i128 = "100" } } },
#   #   ]
#   #
#   # The two formats must not be mixed in the same array (TOML restriction).
#   # Empty arrays default to the legacy format.
#
#   cpu_limit  = 5000000          # optional, inclusive CPU instruction limit
#   mem_limit  = 5000000          # optional, inclusive memory-bytes limit
#   read_limit = 5000             # optional, inclusive read-bytes limit
#   write_limit = 1000            # optional, inclusive write-bytes limit
#
#   # Percentage-based limits (mutually exclusive with the corresponding
#   # `*_limit`).  Resolved against the protocol max at runtime:
#   #   CPU Instructions → 10 000 000  inst.
#   #   Read Bytes       →  1 048 576  B
#   #   Write Bytes      →  1 048 576  B
#   # Examples:
#   #   cpu_limit_pct  = 50   #  50 % of max CPU = 5 000 000 inst.
#   #   read_limit_pct = 10   #  10 % of max read =   104 857 B
#   #   write_limit_pct = 5   #   5 % of max write =   52 428 B
#
# A missing `*_limit` (or `*_limit_pct`) means that metric is reported but not enforced.
# See `cargo budget-report --check` for limit enforcement.
# Unknown keys inside a [functions.*] block produce an error.
#
# Foreign top-level sections (e.g. [lints] for soroban-cost-linter) are
# silently accepted so that both tools can share a single budget.toml.

[functions.do_expensive_work]
args = ["--n", "10000"]
cpu_limit = 5000000
read_limit = 5000
write_limit = 1000
"#;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
enum OutputFormat {
    #[default]
    Table,
    Json,
    Md,
}

impl FromStr for OutputFormat {
    type Err = String;
    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "table" => Ok(Self::Table),
            "json" => Ok(Self::Json),
            "md" => Ok(Self::Md),
            _ => Err(format!(
                "unsupported output format `{value}`; expected `table`, `json`, or `md`"
            )),
        }
    }
}

impl fmt::Display for OutputFormat {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Table => write!(f, "table"),
            Self::Json => write!(f, "json"),
            Self::Md => write!(f, "md"),
        }
    }
}

/// Top-level CLI entry point for `cargo budget-report`.
///
/// Wraps the binary in a `cargo <subcommand>` compatible enum so it can be
/// invoked as `cargo budget-report [OPTIONS]`.
#[derive(Parser, Debug)]
#[command(name = "cargo", bin_name = "cargo")]
enum CargoCli {
    BudgetReport(BudgetReportArgs),
}

#[derive(Parser, Debug)]
struct BudgetReportArgs {
    /// Scaffold a commented `budget.toml` template and exit.
    #[arg(long)]
    init: bool,

    /// Allow `--init` to overwrite an existing `budget.toml`.
    #[arg(long)]
    force: bool,

    #[arg(long)]
    network: Option<String>,

    #[arg(long)]
    source: Option<String>,

    /// Deprecated alias for `--format json` (use `--format json` instead).
    #[arg(long, hide = true)]
    json: bool,

    /// Output format: table, json, or md (markdown).
    #[arg(long, default_value = "table")]
    format: OutputFormat,

    /// Enforce per-function limits declared in `budget.toml`.
    ///
    /// When set, each measured metric is compared against its configured
    /// `cpu_limit` / `read_limit` / `write_limit`. A missing limit means the
    /// metric is reported but **not** enforced. The process exits with a
    /// non-zero status when any limit is breached, or when a function that
    /// has a `budget.toml` entry fails to simulate. Functions that are not
    /// declared in `budget.toml` are reported only.
    #[arg(long, default_value_t = false)]
    check: bool,

    /// Exit immediately on the first budget violation instead of collecting
    /// all results before reporting. Only meaningful with `--check`.
    #[arg(long, default_value_t = false)]
    fail_fast: bool,

    /// Emit the report as CSV instead of a table or JSON.
    #[arg(long, default_value_t = false)]
    csv: bool,

    /// Maximum number of contract functions to simulate concurrently.
    /// Public RPC endpoints may rate-limit; keep this conservative.
    #[arg(long, default_value_t = DEFAULT_CONCURRENCY)]
    concurrency: usize,

    #[arg(long)]
    validate: bool,

    #[arg(long, default_value_t = false)]
    quiet: bool,

    #[arg(long)]
    record_baseline: Option<String>,

    #[arg(long)]
    check_baseline: Option<String>,

    #[arg(long)]
    tolerance: Option<String>,

    #[arg(long)]
    derive_limits: Option<String>,

    #[arg(long)]
    provenance_out: Option<String>,

    #[arg(long)]
    profile: Option<String>,

    #[arg(long)]
    from: Option<String>,

    #[arg(long)]
    margin_cpu: Option<String>,

    #[arg(long)]
    margin_memory: Option<String>,

    #[arg(long)]
    margin_read: Option<String>,

    #[arg(long)]
    margin_write: Option<String>,

    #[arg(long, default_value_t = false)]
    totals: bool,
}

fn default_network() -> Option<String> {
    Some("testnet".to_string())
}
fn default_source() -> Option<String> {
    Some("alice".to_string())
}

#[derive(serde::Deserialize, Default, Debug)]
struct BudgetToml {
    /// Network to target. Defaults to `"testnet"` when not specified.
    #[serde(default = "default_network")]
    network: Option<String>,
    /// Stellar source account keypair name. Defaults to `"alice"` when not specified.
    #[serde(default = "default_source")]
    source: Option<String>,
    #[serde(default)]
    tolerance: Option<f64>,
    #[serde(default)]
    functions: HashMap<String, FunctionConfig>,
}

#[allow(dead_code)]
#[derive(serde::Deserialize, Debug)]
struct Resources {
    instructions: u64,
    disk_read_bytes: u64,
    write_bytes: u64,
}

#[allow(dead_code)]
#[derive(serde::Deserialize, Debug)]
struct TransactionData {
    #[serde(alias = "resources")]
    resources: Resources,
}

impl TransactionData {
    #[cfg(test)]
    fn parse_json(json_str: &str) -> Result<Self> {
        let parsed_json: serde_json::Value =
            serde_json::from_str(json_str).context("Failed to parse JSON")?;
        serde_json::from_value(parsed_json).context("Failed to deserialize transaction data")
    }
}

#[derive(serde::Deserialize, Default, Debug)]
struct FunctionConfig {
    /// Function arguments. Supports both legacy flat string args and
    /// the new typed format (see [`ArgSpec`]).
    #[serde(default)]
    args: ArgSpec,
    /// Inclusive upper bound on the measured CPU `Instructions` metric. `None`
    /// means this metric is reported but not enforced by `--check`.
    #[serde(default)]
    cpu_limit: Option<u64>,
    #[serde(default)]
    mem_limit: Option<u64>,
    #[serde(default)]
    read_limit: Option<u64>,
    #[serde(default)]
    write_limit: Option<u64>,
    #[serde(default)]
    cpu_limit_pct: Option<u64>,
    #[serde(default)]
    read_limit_pct: Option<u64>,
    #[serde(default)]
    write_limit_pct: Option<u64>,
    #[serde(default)]
    tolerance: Option<f64>,
}

#[derive(Default, Serialize)]
struct CostReport {
    package: String,
    function: String,
    metric: &'static str,
    /// The measured value, or `None` if the simulation failed to produce one
    /// (only emitted in `--check` mode for functions declared in
    /// `budget.toml`).
    #[serde(skip_serializing_if = "Option::is_none")]
    value: Option<u32>,
    /// Configured upper bound for the metric, if any. Emitted in `--check`
    /// mode only.
    #[serde(skip_serializing_if = "Option::is_none")]
    limit: Option<u64>,
    /// `true` if the measured value is within the configured limit, `false`
    /// if it exceeds the limit **or** the simulation failed for a configured
    /// function. Emitted in `--check` mode only.
    #[serde(skip_serializing_if = "Option::is_none")]
    pass: Option<bool>,
    /// The network resource limit (instructions, read bytes, or write bytes)
    /// that this metric's value is measured against. `None` for metrics
    /// that have no corresponding network limit (e.g. `WASM Bytes`).
    #[serde(skip_serializing_if = "Option::is_none")]
    resource_limit: Option<u64>,
    /// The measured value as a percentage of the corresponding network
    /// resource limit (0-100). `None` when no network limit is available.
    #[serde(skip_serializing_if = "Option::is_none")]
    share_pct: Option<f64>,
}

#[derive(Tabled)]
struct TableCostReport {
    package: String,
    function: String,
    metric: &'static str,
    value: String,
}

struct FunctionMetrics {
    cpu: u32,
    read: u32,
    write: u32,
    wasm: u32,
}

fn build_markdown_report(reports: &[CostReport]) -> String {
    use std::collections::BTreeMap;

    let mut packages: BTreeMap<String, BTreeMap<String, FunctionMetrics>> = BTreeMap::new();

    for r in reports {
        let Some(value) = r.value else { continue };
        let functions = packages.entry(r.package.clone()).or_default();
        let metrics = functions
            .entry(r.function.clone())
            .or_insert(FunctionMetrics {
                cpu: 0,
                read: 0,
                write: 0,
                wasm: 0,
            });
        match r.metric {
            "CPU Instructions" => metrics.cpu = value,
            "Read Bytes" => metrics.read = value,
            "Write Bytes" => metrics.write = value,
            "WASM Bytes" => metrics.wasm = value,
            _ => {}
        }
    }

    let mut output = String::new();
    output.push_str("# Workspace Budget Report\n\n");

    for (pkg_name, functions) in &packages {
        output.push_str(&format!("## {}\n\n", pkg_name));
        output.push_str("| Function | CPU Instructions | Read Bytes | Write Bytes |\n");
        output.push_str("|----------|-----------------|------------|-------------|\n");

        for (func_name, m) in functions {
            let cpu = format_with_commas_and_units(u64::from(m.cpu), "CPU Instructions");
            let read = format_with_commas_and_units(u64::from(m.read), "Read Bytes");
            let write = format_with_commas_and_units(u64::from(m.write), "Write Bytes");
            output.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                func_name, cpu, read, write
            ));
        }
        output.push('\n');
    }

    output.push_str("---\n");
    output.push_str("_The values above are simulated resource amounts, not fees. They are three of the inputs to the non-refundable resource fee._\n");

    output
}

fn resolve_limit(config: &FunctionConfig, metric: &str) -> Option<u64> {
    match metric {
        "CPU Instructions" => config
            .cpu_limit
            .or_else(|| config.cpu_limit_pct.map(|pct| pct * 10_000_000 / 100)),
        "Read Bytes" => config
            .read_limit
            .or_else(|| config.read_limit_pct.map(|pct| pct * 1_048_576 / 100)),
        "Write Bytes" => config
            .write_limit
            .or_else(|| config.write_limit_pct.map(|pct| pct * 1_048_576 / 100)),
        _ => None,
    }
}

/// Returns the configured limit (if any) for the given metric name.
///
/// This returns the *raw* configured value — either an absolute limit
/// (`cpu_limit`, `read_limit`, `write_limit`) or a percentage
/// (`cpu_limit_pct`, `read_limit_pct`, `write_limit_pct`). Use
/// [`resolve_limit`] to convert a percentage into an absolute value.
fn limit_for_metric(func_config: &FunctionConfig, metric: &str) -> Option<u64> {
    match metric {
        "CPU Instructions" => func_config.cpu_limit,
        "Memory Bytes" => func_config.mem_limit,
        "Read Bytes" => func_config.read_limit,
        "Write Bytes" => func_config.write_limit,
        _ => None,
    }
}

/// Given a measured value and an optional configured limit, returns the
/// `(limit, pass)` pair that should be attached to a `CostReport`.
///
/// * No limit configured → `(None, None)`; the metric is reported but not
///   enforced.
/// * Limit configured and value is within it → `(Some(limit), Some(true))`.
/// * Limit configured and value exceeds it → `(Some(limit), Some(false))`;
///   the caller should mark the check as failed.
fn evaluate_check(value: u32, limit: Option<u64>) -> (Option<u64>, Option<bool>) {
    match limit {
        Some(limit_value) => (
            Some(limit_value),
            // Widen `value` from u32 → u64 before comparing.
            // `u64::from(value)` is preferred over `value as u64` because it
            // is a lossless, explicitly zero-extending conversion.  If the
            // type of `value` were ever changed to a signed integer (e.g.
            // i32), the compiler would reject `u64::from(value)` rather than
            // silently sign-extending via `as`.
            // The comparison is inclusive (`<=`): a measurement that exactly
            // equals the configured limit is still a passing result.
            Some(u64::from(value) <= limit_value),
        ),
        // No limit configured — report the metric but do not enforce it.
        None => (None, None),
    }
}

/// Emit one stub `CostReport` per metric (`CPU Instructions`, `Read Bytes`,
/// `Write Bytes`) so that the `--check` JSON output and check summary make
/// the failure visible per metric.
///
/// * Metrics with a configured `*_limit` get `value: None, limit: Some(n),
///   pass: Some(false)` — the consumer can read the breached limit.
/// * Metrics without a configured limit get `value: None, limit: None,
///   pass: Some(false)` — still a hook for `--check --json` consumers, but
///   the table filter (`value.is_some()`) keeps it out of the plain-text
///   report and the summary lines remain unchanged.
///
/// The caller has already set the `checks_failed` flag for the function as a
/// whole, so emitting one entry per metric — even metrics without a limit —
/// does not change the exit-code semantics.
fn emit_check_failure_entries(
    reports: &mut Vec<CostReport>,
    package_name: &str,
    function: &str,
    func_config: &FunctionConfig,
) {
    for metric in [
        "CPU Instructions",
        "Memory Bytes",
        "Read Bytes",
        "Write Bytes",
    ] {
        let limit = limit_for_metric(func_config, metric);
        reports.push(CostReport {
            package: package_name.to_string(),
            function: function.to_string(),
            metric,
            value: None,
            limit,
            pass: Some(false),
            resource_limit: None,
            share_pct: None,
        });
    }
}

fn format_with_commas_and_units(value: u64, metric: &str) -> String {
    let s = value.to_string();
    let mut result = String::new();
    let mut digit_count = 0;
    for ch in s.chars().rev() {
        if digit_count == 3 {
            result.push(',');
            digit_count = 0;
        }
        result.push(ch);
        digit_count += 1;
    }
    let formatted = result.chars().rev().collect::<String>();

    if metric.contains("Bytes") {
        format!("{} B", formatted)
    } else {
        format!("{} inst.", formatted)
    }
}

fn soroban_rpc_url(network: &str) -> &str {
    match network {
        "testnet" => "https://soroban-testnet.stellar.org:443",
        "futurenet" => "https://rpc-futurenet.stellar.org:443",
        "local" => "http://localhost:8000",
        _ => "https://soroban-testnet.stellar.org:443",
    }
}

fn extract_memory_bytes_cost(rpc_resp: &serde_json::Value) -> Option<u32> {
    rpc_resp["result"]["cost"]["mem_bytes"]
        .as_u64()
        .map(|v| v as u32)
}

fn extract_metrics(rpc_response: &serde_json::Value) -> Result<(u32, u32, u32)> {
    if let Some(error) = rpc_response.get("error") {
        anyhow::bail!("{}", error);
    }

    let tx_data_b64 = rpc_response["result"]["transactionData"]
        .as_str()
        .context("No transactionData found in simulateTransaction response.")?;

    let tx_data = SorobanTransactionData::from_xdr_base64(tx_data_b64, Limits::none())
        .context("Failed to decode SorobanTransactionData from base64 XDR")?;

    Ok((
        tx_data.resources.instructions,
        tx_data.resources.disk_read_bytes,
        tx_data.resources.write_bytes,
    ))
}

/// Why simulating a single exported function did not produce metrics.
/// Carries the same text the caller previously logged inline, so extracting
/// this out of the main loop doesn't change any user-facing diagnostics.
#[derive(Debug)]
enum SimulationFailure {
    /// `stellar contract invoke --build-only` exited non-zero.
    Invoke(String),
    /// The RPC `simulateTransaction` response contained an `"error"` field.
    Rpc(String),
    /// The RPC response didn't contain a decodable `SorobanTransactionData`.
    MetricsExtraction(String),
    /// A spawn or IO error on the `stellar`/`curl` subprocess itself
    /// (not a failure returned *by* the subprocess).
    Spawn(String),
}

/// Outcome of simulating one exported function.
#[derive(Debug)]
enum SimulationOutcome {
    Metrics {
        instructions: u32,
        read_bytes: u32,
        write_bytes: u32,
        memory_bytes: Option<u32>,
        transaction_data_xdr: String,
    },
    Failed(SimulationFailure),
}

/// Builds the `stellar contract invoke --build-only -- <function> [args..]`
/// argument list for one exported function.
fn build_invoke_args(
    contract_id: &str,
    source: &str,
    network: &str,
    function: &str,
    func_args: &[String],
) -> Vec<String> {
    let mut invoke_args = vec![
        "contract".to_string(),
        "invoke".to_string(),
        "--id".to_string(),
        contract_id.to_string(),
        "--source".to_string(),
        source.to_string(),
        "--network".to_string(),
        network.to_string(),
        "--build-only".to_string(),
        "--".to_string(),
        function.to_string(),
    ];
    invoke_args.extend(func_args.iter().cloned());
    invoke_args
}

/// Builds the JSON-RPC `simulateTransaction` request body for a base64 XDR
/// transaction envelope.
fn build_rpc_payload(b64_xdr: &str) -> serde_json::Value {
    serde_json::json!({
        "jsonrpc": "2.0",
        "id": 1,
        "method": "simulateTransaction",
        "params": {
            "transaction": b64_xdr
        }
    })
}

/// POSTs a `simulateTransaction` JSON-RPC request for `b64_xdr` and returns
/// the parsed response body.
fn simulate_transaction_rpc(b64_xdr: &str, rpc_url: &str) -> Result<serde_json::Value> {
    let rpc_payload = build_rpc_payload(b64_xdr);

    let mut curl = Command::new("curl")
        .args([
            "-s",
            "-X",
            "POST",
            "-H",
            "Content-Type: application/json",
            "-d",
            "@-",
            rpc_url,
        ])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .context("failed to execute curl")?;

    {
        let stdin = curl.stdin.as_mut().context("Failed to open stdin")?;
        stdin
            .write_all(rpc_payload.to_string().as_bytes())
            .context("Failed to write to stdin")?;
    }

    let curl_output = curl
        .wait_with_output()
        .context("Failed to read curl output")?;
    serde_json::from_slice(&curl_output.stdout).context("Failed to parse RPC response")
}

/// Simulates one exported function end-to-end: runs
/// `stellar contract invoke --build-only` to build the transaction, then
/// POSTs it to `simulateTransaction` and decodes the reported resource
/// usage.
///
/// Returns `Err` only for a spawn/IO failure on the `stellar`/`curl` child
/// processes — the tool cannot proceed without those binaries. A
/// *recoverable* simulation failure (non-zero invoke exit, an RPC `error`
/// field, or an undecodable response) is reported as
/// `Ok(SimulationOutcome::Failed(..))` so the caller can move on to the next
/// function instead of aborting the whole report.
fn simulate_function(
    contract_id: &str,
    source: &str,
    network: &str,
    function: &str,
    func_args: &[String],
) -> Module10Result<SimulationOutcome> {
    let invoke_args = build_invoke_args(contract_id, source, network, function, func_args);
    let invoke_output = Command::new("stellar")
        .args(&invoke_args)
        .output()
        .context("failed to execute stellar-cli invoke")?;

    if !invoke_output.status.success() {
        let stderr = String::from_utf8_lossy(&invoke_output.stderr).to_string();
        return Ok(SimulationOutcome::Failed(SimulationFailure::Invoke(stderr)));
    }

    let b64_xdr = String::from_utf8_lossy(&invoke_output.stdout)
        .trim()
        .to_string();
    let rpc_url = soroban_rpc_url(network);
    let rpc_resp = simulate_transaction_rpc(&b64_xdr, rpc_url)?;

    if let Some(error) = rpc_resp.get("error") {
        return Ok(SimulationOutcome::Failed(SimulationFailure::Rpc(
            error.to_string(),
        )));
    }

    // Capture the raw transactionData XDR before decode, so --validate
    // can re-decode it through the Stellar CLI independently.
    let tx_data_xdr_b64 = rpc_resp["result"]["transactionData"]
        .as_str()
        .map(|s| s.to_string());

    // `result.cost.memBytes` is a Protocol 22+ field. Older responses or
    // malformed payloads do not surface it; absence is not zero cost.
    let memory_bytes = extract_memory_bytes_cost(&rpc_resp);

    match extract_metrics(&rpc_resp) {
        Ok((instructions, read_bytes, write_bytes)) => Ok(SimulationOutcome::Metrics {
            instructions,
            read_bytes,
            write_bytes,
            memory_bytes,
            transaction_data_xdr: tx_data_xdr_b64.unwrap_or_default(),
        }),
        Err(err) => Ok(SimulationOutcome::Failed(
            SimulationFailure::MetricsExtraction(format!("{:#}", err)),
        )),
    }
}

fn load_budget_toml<P: AsRef<Path>>(path: P) -> Result<BudgetToml> {
    match std::fs::read_to_string(&path) {
        Ok(contents) => toml::from_str(&contents)
            .map_err(|err| anyhow::anyhow!("failed to parse {}: {}", path.as_ref().display(), err)),
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(BudgetToml::default()),
        Err(err) => Err(err).with_context(|| format!("failed to read {}", path.as_ref().display())),
    }
}

/// Scaffold a commented `budget.toml` template. Errors if the file already
/// exists and `force` is not set.
fn scaffold_init(force: bool) -> Result<()> {
    let path = Path::new("budget.toml");
    if path.exists() && !force {
        anyhow::bail!("budget.toml already exists; use --force to overwrite");
    }
    std::fs::write(path, BUDGET_TOML_TEMPLATE)
        .with_context(|| format!("failed to write {}", path.display()))?;
    eprintln!("Wrote {}", path.display());
    Ok(())
}

/// Run environment preflight checks before building or deploying.
///
/// Each check fails fast with an actionable error message. Checks that are
/// not applicable (e.g. rustup not installed) are silently skipped.
fn run_preflight_checks() -> Result<()> {
    // ── stellar CLI ─────────────────────────────────────────────────────
    eprint!("Checking Stellar CLI... ");
    let stellar_check = Command::new("stellar").arg("--version").output();
    match stellar_check {
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            anyhow::bail!(
                "Stellar CLI is not installed or not on PATH.\n\
                 Install it with:  cargo install --locked stellar-cli\n\
                 See: https://github.com/stellar/stellar-cli"
            );
        }
        Err(e) => {
            anyhow::bail!("failed to execute stellar --version: {}", e);
        }
        Ok(output) if !output.status.success() => {
            anyhow::bail!(
                "Stellar CLI failed to run.\n\
                 stderr: {}",
                String::from_utf8_lossy(&output.stderr)
            );
        }
        Ok(_output) => {
            eprintln!("found");
        }
    }

    // ── wasm32 target ───────────────────────────────────────────────────
    eprint!("Checking wasm32-unknown-unknown target... ");
    let rustup_check = Command::new("rustup")
        .args(["target", "list", "--installed"])
        .output();
    match rustup_check {
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            // rustup is not installed — skip the check silently.
            eprintln!("skipped (rustup not found)");
        }
        Err(e) => {
            anyhow::bail!("failed to execute rustup: {}", e);
        }
        Ok(output) => {
            let installed = String::from_utf8_lossy(&output.stdout);
            if installed
                .lines()
                .any(|line| line.trim() == "wasm32-unknown-unknown")
            {
                eprintln!("found");
            } else {
                anyhow::bail!(
                    "wasm32-unknown-unknown target is not installed.\n\
                     Install it with:  rustup target add wasm32-unknown-unknown"
                );
            }
        }
    }

    Ok(())
}

struct NetworkLimits {
    max_instructions: u64,
    max_read_bytes: u64,
    max_write_bytes: u64,
}

type Module10Result<T> = Result<T>;

#[derive(serde::Serialize, serde::Deserialize, Default, Clone)]
struct CacheEntry {
    wasm_sha256: String,
    contract_id: String,
    network: String,
}

#[derive(serde::Serialize, serde::Deserialize, Default)]
struct BudgetCache {
    package: HashMap<String, CacheEntry>,
}

const CACHE_FILE: &str = ".budget-cache.toml";

/// Loads the contract ID cache from `.budget-cache.toml`.
fn load_cache() -> BudgetCache {
    std::fs::read_to_string(CACHE_FILE)
        .ok()
        .and_then(|s| toml::from_str(&s).ok())
        .unwrap_or_default()
}

fn save_cache(cache: &BudgetCache) {
    let toml_str = toml::to_string_pretty(cache).unwrap_or_default();
    let _ = std::fs::write(CACHE_FILE, toml_str);
}

fn wasm_sha256(wasm_bytes: &[u8]) -> String {
    let mut hasher = Sha256::default();
    hasher.update(wasm_bytes);
    hex::encode(hasher.finalize())
}

fn get_contract_id_for_package(
    package_name: &str,
    wasm_bytes: &[u8],
    network: &str,
    source: &str,
    wasm_path: &Path,
    force_deploy: bool,
    cache: &mut BudgetCache,
) -> Result<String> {
    let hash = wasm_sha256(wasm_bytes);

    if !force_deploy {
        if let Some(entry) = cache.package.get(package_name) {
            if entry.wasm_sha256 == hash && entry.network == network {
                eprintln!(
                    "Cache hit for '{}' — reusing contract id {}",
                    package_name, entry.contract_id
                );
                return Ok(entry.contract_id.clone());
            }
        }
    }

    let contract_id = deploy_contract_with_retry(wasm_path, source, network, package_name)?;

    cache.package.insert(
        package_name.to_string(),
        CacheEntry {
            wasm_sha256: hash,
            contract_id: contract_id.clone(),
            network: network.to_string(),
        },
    );
    save_cache(cache);

    Ok(contract_id)
}

/// Deploys a contract WASM to the network with automatic retry on
/// friendbot-related transient failures.
///
/// The `stellar contract deploy` command implicitly triggers friendbot
/// funding for the source account on testnet. Friendbot may return 429
/// (rate-limited) or the account may not be confirmed on-ledger yet.
/// This function makes up to `MAX_DEPLOY_ATTEMPTS` total attempts with
/// exponential backoff before giving up.
fn deploy_contract_with_retry(
    wasm_path: &Path,
    source: &str,
    network: &str,
    package_name: &str,
) -> Module10Result<String> {
    let mut last_error = String::new();

    for attempt in 0..MAX_DEPLOY_ATTEMPTS {
        if attempt > 0 {
            let delay = INITIAL_RETRY_DELAY_SECS * 2u64.pow(attempt - 1);
            eprintln!(
                "Deploy attempt {}/{} failed. Retrying in {} s...",
                attempt, MAX_DEPLOY_ATTEMPTS, delay
            );
            thread::sleep(Duration::from_secs(delay));
        }

        let deploy_output = Command::new("stellar")
            .args([
                "contract",
                "deploy",
                "--wasm",
                wasm_path.to_str().context("wasm path is not valid UTF-8")?,
                "--source",
                source,
                "--network",
                network,
            ])
            .output()
            .context("failed to execute stellar-cli deploy")?;

        if deploy_output.status.success() {
            let contract_id = String::from_utf8_lossy(&deploy_output.stdout)
                .trim()
                .to_string();
            return Ok(contract_id);
        }

        last_error = String::from_utf8_lossy(&deploy_output.stderr).to_string();
    }

    anyhow::bail!(
        "Failed to deploy {} after {} attempts. Ensure your source account is funded.\nLast error: {}",
        package_name,
        MAX_DEPLOY_ATTEMPTS,
        last_error
    )
}

fn main() -> Result<()> {
    let CargoCli::BudgetReport(args) = CargoCli::parse();

    // ── --init: scaffold a template and exit ──────────────────────────
    if args.init {
        return scaffold_init(args.force);
    }

    // ── Preflight environment checks ──────────────────────────────────
    run_preflight_checks()?;

    let toml_config = load_budget_toml("budget.toml")?;

    let network = args
        .network
        .or(toml_config.network)
        .context("missing --network or budget.toml network field")?;
    let source = args
        .source
        .or(toml_config.source)
        .context("missing --source or budget.toml source field")?;

    eprintln!("Discovering workspace members...");
    let metadata = MetadataCommand::new()
        .no_deps()
        .exec()
        .context("failed to execute cargo metadata")?;

    let overall_start = Instant::now();

    let mut reports = Vec::new();
    let mut has_errors = false;
    let mut checks_failed = false;
    let mut _validation_failed = false;

    let force_deploy = false;
    let mut cache = load_cache();

    for package in metadata.packages {
        let is_cdylib = package
            .targets
            .iter()
            .any(|t| t.crate_types.iter().any(|c| *c == CrateType::CDyLib));
        if !is_cdylib {
            continue;
        }

        eprintln!("Building package '{}' for wasm32...", package.name);
        let build_status = Command::new("cargo")
            .args([
                "build",
                "-p",
                &package.name,
                "--target",
                "wasm32-unknown-unknown",
                "--release",
            ])
            .status()
            .context("failed to build package")?;

        if !build_status.success() {
            anyhow::bail!("Failed to build {}", package.name);
        }

        // Locate the cdylib target to derive the correct WASM filename.
        // A crate's [lib] name may differ from its package name, so we
        // cannot rely on package.name.replace('-', "_").
        let cdylib_target = package
            .targets
            .iter()
            .find(|t| t.crate_types.iter().any(|ct| *ct == CrateType::CDyLib));
        let wasm_name = match cdylib_target {
            Some(target) => target.name.clone(),
            None => {
                eprintln!(
                    "Warning: no cdylib target found for package '{}' — skipping",
                    package.name
                );
                continue;
            }
        };
        let wasm_path = metadata
            .target_directory
            .join("wasm32-unknown-unknown")
            .join("release")
            .join(format!("{}.wasm", wasm_name));

        if !wasm_path.exists() {
            eprintln!("Warning: WASM not found at {}", wasm_path);
            continue;
        }

        // Parse WASM exports
        let wasm_bytes = std::fs::read(&wasm_path).context("failed to read wasm file")?;
        let wasm_size: u32 = wasm_bytes.len().try_into().unwrap_or(u32::MAX);
        let mut exported_fns = Vec::new();

        for payload in WasmParser::new(0).parse_all(&wasm_bytes) {
            if let wasmparser::Payload::ExportSection(s) = payload? {
                for export in s {
                    let export = export?;
                    if export.kind == wasmparser::ExternalKind::Func {
                        let name = export.name.to_string();
                        // Ignore internal and common exports
                        if !name.starts_with('_') && name != "memory" {
                            exported_fns.push(name);
                        }
                    }
                }
            }
        }

        if exported_fns.is_empty() {
            eprintln!("No exported functions found in {}", package.name);
            continue;
        }

        let spinner = ProgressBar::new_spinner();
        spinner.set_style(
            ProgressStyle::default_spinner()
                .tick_strings(&["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏", "✔"])
                .template("{spinner:.green} Deploying contract {msg}...")
                .unwrap(),
        );
        spinner.set_message(package.name.to_string());
        spinner.enable_steady_tick(std::time::Duration::from_millis(100));

        let contract_id = get_contract_id_for_package(
            &package.name,
            &wasm_bytes,
            &network,
            &source,
            wasm_path.as_std_path(),
            force_deploy,
            &mut cache,
        )?;

        spinner.finish_and_clear();

        eprintln!("Contract deployed at: {}", contract_id);

        // ── Simulate exported functions concurrently ─────────────────
        //
        // Deploys are per-package and must complete before any of that
        // package's functions are simulated.  Once the contract is on
        // chain every exported function is independent and latency-bound
        // (subprocess + RPC round-trip), so they are fanned out across
        // scoped threads with a bounded semaphore.
        //
        // Results are collected into a Vec keyed by the original
        // enumeration order so the report output stays deterministic
        // regardless of completion order.

        let concurrency = args.concurrency.max(1);
        let fn_count = exported_fns.len();

        // Pre-compute function arguments so threads don't borrow
        // `toml_config`.
        let function_args: Vec<(String, Vec<String>)> = exported_fns
            .iter()
            .map(|f| {
                let args = toml_config
                    .functions
                    .get(f)
                    .map(|c| c.args.encode())
                    .unwrap_or_default();
                (f.clone(), args)
            })
            .collect();

        if fn_count == 1 {
            eprintln!("Simulating function '{}'...", function_args[0].0);
        } else {
            eprintln!(
                "Simulating {} functions concurrently (max {})...",
                fn_count, concurrency
            );
        }

        let pb = ProgressBar::new(fn_count as u64);
        pb.set_style(
            ProgressStyle::default_bar()
                .template(
                    "{spinner:.green} [{elapsed_precise}] [{bar:40.cyan/blue}] \
                     {pos}/{len} functions {msg}",
                )
                .unwrap()
                .progress_chars("#>-\u{00a0}"),
        );

        let semaphore = Arc::new(Semaphore::new(concurrency));
        let results_mutex = Arc::new(Mutex::new(Vec::new()));

        thread::scope(|s| {
            for (i, (function, func_args)) in function_args.iter().enumerate() {
                let semaphore = Arc::clone(&semaphore);
                let results_mutex = Arc::clone(&results_mutex);
                let pb = pb.clone();
                let contract_id = contract_id.clone();
                let source = source.clone();
                let network = network.clone();
                let function = function.clone();
                let func_args = func_args.clone();

                s.spawn(move || {
                    semaphore.acquire();

                    let outcome = match simulate_function(
                        &contract_id,
                        &source,
                        &network,
                        &function,
                        &func_args,
                    ) {
                        Ok(outcome) => outcome,
                        Err(e) => {
                            SimulationOutcome::Failed(SimulationFailure::Spawn(format!("{:#}", e)))
                        }
                    };

                    semaphore.release();

                    results_mutex.lock().unwrap().push((i, outcome));
                    pb.set_message(function);
                    pb.inc(1);
                });
            }
        });

        pb.finish_and_clear();

        // Sort by original enumeration order so report output is
        // deterministic.
        let mut ordered_results = Arc::try_unwrap(results_mutex)
            .unwrap()
            .into_inner()
            .unwrap();
        ordered_results.sort_by_key(|(i, _)| *i);

        let network_limits = NetworkLimits {
            max_instructions: 10_000_000,
            max_read_bytes: 1_048_576,
            max_write_bytes: 1_048_576,
        };

        for (i, outcome) in ordered_results {
            let function = &function_args[i].0;
            let func_config = toml_config.functions.get(function);

            match outcome {
                SimulationOutcome::Metrics {
                    instructions,
                    read_bytes,
                    write_bytes,
                    memory_bytes,
                    transaction_data_xdr,
                } => {
                    // Build four CostReport entries for this function.
                    // In --check mode, attach the configured limit and
                    // pass/fail to each entry.
                    //
                    // `Memory Bytes` is appended only when the Protocol 22+
                    // `result.cost.memBytes` field was present, so older
                    // protocol simulations cleanly skip the metric rather
                    // than reporting a misleading zero.
                    let mut reporting_metrics: Vec<(&'static str, u32)> = vec![
                        ("CPU Instructions", instructions),
                        ("Read Bytes", read_bytes),
                        ("Write Bytes", write_bytes),
                        ("WASM Bytes", wasm_size),
                    ];
                    if let Some(mb) = memory_bytes {
                        reporting_metrics.push(("Memory Bytes", mb));
                    }

                    for (metric, value) in reporting_metrics {
                        let limit = func_config.and_then(|cfg| limit_for_metric(cfg, metric));
                        let (entry_limit, pass) = evaluate_check(value, limit);
                        if pass == Some(false) {
                            checks_failed = true;
                            if args.check && args.fail_fast {
                                let value_str =
                                    format_with_commas_and_units(u64::from(value), metric);
                                let limit_str = entry_limit
                                    .map(|limit_val| {
                                        let display_value =
                                            u32::try_from(limit_val).unwrap_or(u32::MAX);
                                        format_with_commas_and_units(
                                            u64::from(display_value),
                                            metric,
                                        )
                                    })
                                    .unwrap_or_else(|| "-".to_string());
                                println!("\n=== BUDGET CHECKS ===");
                                println!(
                                    "{}::{} [{}] value={} limit={} FAIL",
                                    package.name, function, metric, value_str, limit_str
                                );
                                println!("Summary: 0 check(s) passed, 1 failed");
                                println!("(--fail-fast: stopped on first violation)");
                                std::process::exit(1);
                            }
                        }
                        let (resource_limit, share_pct) = match metric {
                            "CPU Instructions" => (
                                Some(network_limits.max_instructions),
                                Some(value as f64 / network_limits.max_instructions as f64 * 100.0),
                            ),
                            "Read Bytes" => (
                                Some(network_limits.max_read_bytes),
                                Some(value as f64 / network_limits.max_read_bytes as f64 * 100.0),
                            ),
                            "Write Bytes" => (
                                Some(network_limits.max_write_bytes),
                                Some(value as f64 / network_limits.max_write_bytes as f64 * 100.0),
                            ),
                            _ => (None, None),
                        };
                        reports.push(CostReport {
                            package: package.name.to_string(),
                            function: function.clone(),
                            metric,
                            value: Some(value),
                            limit: entry_limit,
                            pass,
                            resource_limit,
                            share_pct,
                        });
                    }

                    // ── Optional Stellar CLI validation ──────────────
                    if args.validate {
                        let v_result = validate::validate_metrics(
                            &transaction_data_xdr,
                            instructions,
                            read_bytes,
                            write_bytes,
                        );
                        match v_result {
                            validate::ValidationResult::Match => {
                                if !args.quiet {
                                    eprintln!("  ✓ validation passed for '{}'", function);
                                }
                            }
                            validate::ValidationResult::Mismatch { diagnostics } => {
                                _validation_failed = true;
                                eprintln!(
                                    "  ✗ VALIDATION FAILED for '{}' in package '{}':",
                                    function, package.name
                                );
                                for d in &diagnostics {
                                    eprintln!("    {}", d);
                                }
                            }
                            validate::ValidationResult::Skipped { reason } => {
                                if !args.quiet {
                                    eprintln!(
                                        "  - validation skipped for '{}': {}",
                                        function, reason
                                    );
                                }
                            }
                        }
                    }
                }
                SimulationOutcome::Failed(failure) => {
                    has_errors = true;
                    match failure {
                        SimulationFailure::Invoke(stderr) => {
                            eprintln!("Warning: Simulation failed for {}: {}", function, stderr);
                        }
                        SimulationFailure::Rpc(error) => {
                            eprintln!("Warning: RPC error for {}: {}", function, error);
                        }
                        SimulationFailure::MetricsExtraction(err) => {
                            eprintln!(
                                "Warning: Failed to extract metrics for {}: {}",
                                function, err
                            );
                        }
                        SimulationFailure::Spawn(err) => {
                            eprintln!("Warning: Subprocess error for {}: {}", function, err);
                        }
                    }
                    if let (true, Some(fc)) = (args.check, func_config) {
                        // A configured function that won't simulate cannot
                        // satisfy any of its declared limits; record this as
                        // a check failure even if no `*_limit` is set on
                        // this row of budget.toml.
                        checks_failed = true;
                        emit_check_failure_entries(&mut reports, &package.name, function, fc);
                    }
                }
            }
        }
    }

    if reports.is_empty() {
        eprintln!("No successful simulations to report.");
        if has_errors || (args.check && checks_failed) {
            std::process::exit(1);
        }
        return Ok(());
    }

    if args.csv {
        let mut wtr = csv::Writer::from_writer(std::io::stdout());
        if args.check {
            wtr.write_record(["package", "function", "metric", "value", "limit", "pass"])
                .context("Failed to write CSV header")?;
            for r in &reports {
                let value_str = r.value.map(|v| v.to_string()).unwrap_or_default();
                let limit_str = r.limit.map(|l| l.to_string()).unwrap_or_default();
                let pass_str = r.pass.map(|p| p.to_string()).unwrap_or_default();
                wtr.write_record([
                    r.package.as_str(),
                    r.function.as_str(),
                    r.metric,
                    value_str.as_str(),
                    limit_str.as_str(),
                    pass_str.as_str(),
                ])
                .context("Failed to write CSV record")?;
            }
        } else {
            wtr.write_record(["package", "function", "metric", "value"])
                .context("Failed to write CSV header")?;
            for r in &reports {
                if r.value.is_some() {
                    let value_str = r.value.map(|v| v.to_string()).unwrap_or_default();
                    wtr.write_record([
                        r.package.as_str(),
                        r.function.as_str(),
                        r.metric,
                        value_str.as_str(),
                    ])
                    .context("Failed to write CSV record")?;
                }
            }
        }
        wtr.flush().context("Failed to flush CSV writer")?;
    } else if args.json {
        let json_output =
            serde_json::to_string_pretty(&reports).context("Failed to serialize report to JSON")?;
        println!("{}", json_output);
    } else {
        // The plain text report path is preserved byte-for-byte when
        // `--check` is not passed: only entries with a measured value are
        // rendered in the table, and summary text is unchanged.
        println!("\n=== WORKSPACE BUDGET REPORT ===");
        let table_reports: Vec<TableCostReport> = reports
            .iter()
            .filter(|r| r.value.is_some())
            .map(|r| {
                let value = r.value.unwrap_or(0);
                let formatted = format_with_commas_and_units(u64::from(value), r.metric);
                TableCostReport {
                    package: r.package.clone(),
                    function: r.function.clone(),
                    metric: r.metric,
                    value: formatted,
                }
            })
            .collect();
        let table = Table::new(table_reports).to_string();
        println!("{}", table);
        println!("\nSummary: The values above are simulated resource amounts, not fees. They are three of the inputs to the non-refundable resource fee.");
        println!("* Not measured: transaction size, ledger footprint entry counts, refundable fees (rent, events, return value), the inclusion fee, and therefore the total fee charged.");
        println!("* Note: These are simulated numbers on testnet and may vary slightly depending on ledger state.");
        println!("* See the \"Measurement scope\" section of the Tool Reference for what to use instead when you need those figures.");

        if args.check {
            println!("\n=== BUDGET CHECKS ===");
            let mut _passed: usize = 0;
            let mut _failed: usize = 0;
            for r in &reports {
                let Some(pass) = r.pass else {
                    continue;
                };
                let status = if pass { "PASS" } else { "FAIL" };
                let value_str = match r.value {
                    Some(v) => format_with_commas_and_units(u64::from(v), r.metric),
                    None => "<simulation failed>".to_string(),
                };
                let limit_str = r
                    .limit
                    .map(|n| {
                        // Limits wider than u32::MAX are not representable in
                        // the table's units, but anything close to the
                        // practical ceiling formats fine.
                        let v = u32::try_from(n).unwrap_or(u32::MAX);
                        format_with_commas_and_units(u64::from(v), r.metric)
                    })
                    .unwrap_or_else(|| "-".to_string());
                println!(
                    "{}::{} [{}] value={} limit={} {}",
                    r.package, r.function, r.metric, value_str, limit_str, status
                );
                if pass {
                    _passed += 1;
                } else {
                    _failed += 1;
                }
            }
        }
    }

    let elapsed = overall_start.elapsed();
    eprintln!("\nTotal wall-clock time: {:.2}s", elapsed.as_secs_f64());

    if has_errors || (args.check && checks_failed) {
        std::process::exit(1);
    }

    Ok(())
}

pub mod compare;
pub(crate) mod derive;
pub(crate) mod json_output;
pub(crate) mod markdown;
mod module_10;
mod module_12;
mod module_2;
mod module_3;
mod module_4;
pub mod validate;

#[derive(Debug, Clone, PartialEq, Eq)]
enum Mode {
    Report,
    Record(PathBuf),
    Check(PathBuf),
    /// Tier A limit derivation. The path is the destination env file.
    /// The optional secondary path, when present, is the destination
    /// for the Markdown provenance sidecar (or `None` to derive the
    /// default `<OUT>.provenance.md` next to it).
    Derive(PathBuf, Option<PathBuf>),
}

impl Mode {
    fn from_args(args: &BudgetReportArgs) -> Self {
        if let Some(out) = &args.derive_limits {
            let provenance = args.provenance_out.as_deref().map(PathBuf::from);
            return Mode::Derive(PathBuf::from(out), provenance);
        }
        if let Some(p) = &args.record_baseline {
            Mode::Record(PathBuf::from(p))
        } else if let Some(p) = &args.check_baseline {
            Mode::Check(PathBuf::from(p))
        } else {
            Mode::Report
        }
    }
}

#[cfg(test)]
mod module_32;

#[cfg(test)]
mod module_8;

mod module_18;
#[cfg(test)]
mod module_27;

#[cfg(test)]
mod module_19;

/// Serializes tests that mutate the process working directory.
#[cfg(test)]
static TEST_CWD_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

fn resolve_tolerance(
    cli_value: Option<&str>,
    config: &BudgetToml,
) -> std::result::Result<compare::Tolerance, String> {
    if let Some(val) = cli_value {
        let parsed: f64 = val.parse().map_err(|_| {
            format!("tolerance must be a number (e.g. '5%' or '0.05'), got '{val}'")
        })?;
        Ok(compare::Tolerance::new(parsed))
    } else if let Some(val) = config.tolerance {
        Ok(compare::Tolerance::new(val))
    } else {
        Ok(compare::Tolerance::default())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};
    use stellar_xdr::WriteXdr;

    fn unique_test_path() -> PathBuf {
        let mut path = std::env::temp_dir();
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time is before UNIX_EPOCH")
            .as_nanos();
        path.push(format!("cargo_budget_report_test_{}.toml", nanos));
        path
    }

    // --- Network simulation loop helper tests ---

    #[test]
    fn build_invoke_args_without_function_args() {
        let invoke_args = build_invoke_args("CCONTRACT", "alice", "testnet", "do_work", &[]);
        assert_eq!(
            invoke_args,
            vec![
                "contract",
                "invoke",
                "--id",
                "CCONTRACT",
                "--source",
                "alice",
                "--network",
                "testnet",
                "--build-only",
                "--",
                "do_work",
            ]
        );
    }

    #[test]
    fn build_invoke_args_appends_function_args_after_separator() {
        let func_args = vec!["--n".to_string(), "10000".to_string()];
        let invoke_args = build_invoke_args("CCONTRACT", "alice", "testnet", "do_work", &func_args);
        assert_eq!(
            invoke_args,
            vec![
                "contract",
                "invoke",
                "--id",
                "CCONTRACT",
                "--source",
                "alice",
                "--network",
                "testnet",
                "--build-only",
                "--",
                "do_work",
                "--n",
                "10000",
            ]
        );
    }

    #[test]
    fn build_rpc_payload_wraps_xdr_in_simulate_transaction_request() {
        let payload = build_rpc_payload("AAAAAgAAAAA=");
        assert_eq!(payload["jsonrpc"], "2.0");
        assert_eq!(payload["method"], "simulateTransaction");
        assert_eq!(payload["params"]["transaction"], "AAAAAgAAAAA=");
    }

    #[test]
    fn build_rpc_payload_empty_xdr_is_still_well_formed() {
        let payload = build_rpc_payload("");
        assert_eq!(payload["params"]["transaction"], "");
    }

    // --- Metric extraction tests ---

    const FIXTURE_INSTRUCTIONS: u32 = 1_000_000;
    const FIXTURE_READ_BYTES: u32 = 2_048;
    const FIXTURE_WRITE_BYTES: u32 = 4_096;
    const FIXTURE_RESOURCE_FEE: i64 = 0;

    fn make_fixture_tx_data() -> SorobanTransactionData {
        use stellar_xdr::{LedgerFootprint, SorobanTransactionDataExt, VecM};
        SorobanTransactionData {
            ext: SorobanTransactionDataExt::V0,
            resources: stellar_xdr::SorobanResources {
                footprint: LedgerFootprint {
                    read_only: VecM::default(),
                    read_write: VecM::default(),
                },
                instructions: FIXTURE_INSTRUCTIONS,
                disk_read_bytes: FIXTURE_READ_BYTES,
                write_bytes: FIXTURE_WRITE_BYTES,
            },
            resource_fee: FIXTURE_RESOURCE_FEE,
        }
    }

    fn fixture_rpc_response_json() -> serde_json::Value {
        let tx_data = make_fixture_tx_data();
        let b64 = tx_data
            .to_xdr_base64(Limits::none())
            .expect("failed to encode fixture SorobanTransactionData");
        serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "result": {
                "transactionData": b64
            }
        })
    }

    #[test]
    fn extract_metrics_from_programmatic_rpc_response() {
        let rpc_json = fixture_rpc_response_json();
        let (instructions, read_bytes, write_bytes) =
            extract_metrics(&rpc_json).expect("extraction should succeed");
        assert_eq!(instructions, FIXTURE_INSTRUCTIONS);
        assert_eq!(read_bytes, FIXTURE_READ_BYTES);
        assert_eq!(write_bytes, FIXTURE_WRITE_BYTES);
    }

    #[test]
    fn extract_metrics_from_fixture_file() {
        let fixture_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("fixtures")
            .join("simulate_transaction_response_valid.json");
        let fixture_json: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(&fixture_path).expect("failed to read fixture file"),
        )
        .expect("failed to parse fixture JSON");

        let meta = &fixture_json["_metadata"];
        assert_eq!(meta["network"].as_str(), Some("testnet"));
        assert!(meta["protocol_version"].as_u64().is_some());

        let (instructions, read_bytes, write_bytes) =
            extract_metrics(&fixture_json).expect("extraction from fixture should succeed");
        assert_eq!(instructions, FIXTURE_INSTRUCTIONS);
        assert_eq!(read_bytes, FIXTURE_READ_BYTES);
        assert_eq!(write_bytes, FIXTURE_WRITE_BYTES);
    }

    #[test]
    fn extract_metrics_fails_on_rpc_error() {
        let rpc_json = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "error": {
                "code": -32600,
                "message": "Invalid Request"
            }
        });
        let result = extract_metrics(&rpc_json);
        assert!(result.is_err());
        let err = format!("{:#}", result.as_ref().unwrap_err());
        assert!(
            err.contains("Invalid Request"),
            "error should mention the RPC error message, got: {}",
            err
        );
    }

    #[test]
    fn extract_metrics_fails_on_missing_transaction_data() {
        let rpc_json = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "result": {
                "some_other_field": "no transaction data here"
            }
        });
        let result = extract_metrics(&rpc_json);
        assert!(result.is_err());
        let err = format!("{:#}", result.as_ref().unwrap_err());
        assert!(
            err.contains("transactionData"),
            "error should mention transactionData, got: {}",
            err
        );
    }

    #[test]
    fn extract_metrics_fails_on_invalid_xdr() {
        let rpc_json = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "result": {
                "transactionData": "this-is-not-valid-base64-xdr!!!"
            }
        });
        let result = extract_metrics(&rpc_json);
        assert!(result.is_err(), "extraction should fail on invalid XDR");
    }

    #[test]
    fn extract_metrics_from_malformed_fixture_file() {
        let fixture_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("fixtures")
            .join("simulate_transaction_response_malformed.json");
        let fixture_json: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(&fixture_path).expect("failed to read malformed fixture file"),
        )
        .expect("failed to parse malformed JSON");

        let result = extract_metrics(&fixture_json);
        assert!(
            result.is_err(),
            "extraction should fail on malformed response"
        );
    }

    #[test]
    fn extract_metrics_fails_on_non_string_transaction_data() {
        let rpc_json = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "result": {
                "transactionData": 12345
            }
        });
        let result = extract_metrics(&rpc_json);
        assert!(
            result.is_err(),
            "extraction should fail when transactionData is not a string"
        );
    }

    // --- Budget toml loading tests ---

    #[test]
    fn missing_budget_toml_returns_default() {
        let path = unique_test_path();
        let _ = fs::remove_file(&path);

        let config = load_budget_toml(&path).expect("missing file should return default");
        assert!(config.network.is_none());
        assert!(config.source.is_none());
        assert!(config.functions.is_empty());
    }

    #[test]
    fn malformed_budget_toml_errors_with_parse_message() {
        let path = unique_test_path();
        fs::write(
            &path,
            "network = \"testnet\"\n[functions.do_expensive_work]\nargs = \"--n 10\"\n",
        )
        .expect("failed to write malformed budget.toml");

        let err = load_budget_toml(&path).unwrap_err();
        let err_text = err.to_string();

        assert!(err_text.contains("failed to parse"));
        assert!(err_text.contains("line") || err_text.contains("Line"));
        assert!(err_text.contains("column") || err_text.contains("Column"));
    }

    #[test]
    fn budget_toml_parses_global_and_per_function_tolerance() {
        let path = unique_test_path();
        fs::write(
            &path,
            "network = \"testnet\"\ntolerance = 0.10\n\
             [functions.do_expensive_work]\nargs = [\"--n\", \"10\"]\ntolerance = 0.05\n",
        )
        .expect("failed to write budget.toml");
        let config = load_budget_toml(&path).expect("parse should succeed");
        assert_eq!(config.tolerance, Some(0.10));
        let func = config
            .functions
            .get("do_expensive_work")
            .expect("function present");
        assert_eq!(func.tolerance, Some(0.05));
    }

    // --- Tolerance resolution ----------------------------------------------

    #[test]
    fn resolve_tolerance_precedence_cli_over_toml_over_default() {
        let config = BudgetToml {
            tolerance: Some(0.25),
            ..Default::default()
        };
        let t = resolve_tolerance(Some("0.42"), &config).expect("cli should win");
        assert!((t.value - 0.42).abs() < f64::EPSILON);

        let t = resolve_tolerance(None, &config).expect("toml should win");
        assert!((t.value - 0.25).abs() < f64::EPSILON);

        let empty = BudgetToml::default();
        let t = resolve_tolerance(None, &empty).expect("default should win");
        assert!((t.value - 0.10).abs() < f64::EPSILON);
    }

    #[test]
    fn resolve_tolerance_rejects_invalid_cli() {
        let config = BudgetToml::default();
        let err = resolve_tolerance(Some("nope"), &config)
            .unwrap_err()
            .to_string();
        assert!(err.contains("tolerance must be a number"), "got: {err}");
    }

    // --- Mode dispatch ------------------------------------------------------

    #[test]
    fn mode_defaults_to_report_when_no_flags() {
        let args = BudgetReportArgs {
            init: false,
            force: false,
            network: None,
            source: None,
            json: false,
            format: Default::default(),
            check: false,
            fail_fast: false,
            csv: false,
            concurrency: Default::default(),
            record_baseline: None,
            check_baseline: None,
            tolerance: None,
            quiet: false,
            validate: false,
            profile: None,
            derive_limits: None,
            from: None,
            margin_cpu: None,
            margin_memory: None,
            margin_read: None,
            margin_write: None,
            provenance_out: None,
            totals: false,
        };
        assert_eq!(Mode::from_args(&args), Mode::Report);
    }

    #[test]
    fn mode_distinguishes_record_and_check() {
        let record = BudgetReportArgs {
            init: false,
            force: false,
            network: None,
            source: None,
            json: false,
            format: Default::default(),
            check: false,
            fail_fast: false,
            csv: false,
            concurrency: Default::default(),
            record_baseline: Some("budget-baseline.toml".to_string()),
            check_baseline: None,
            tolerance: None,
            quiet: false,
            validate: false,
            profile: None,
            derive_limits: None,
            from: None,
            margin_cpu: None,
            margin_memory: None,
            margin_read: None,
            margin_write: None,
            provenance_out: None,
            totals: false,
        };
        assert_eq!(
            Mode::from_args(&record),
            Mode::Record(PathBuf::from("budget-baseline.toml"))
        );

        let check = BudgetReportArgs {
            init: false,
            force: false,
            network: None,
            source: None,
            json: false,
            format: Default::default(),
            check: false,
            fail_fast: false,
            csv: false,
            concurrency: Default::default(),
            record_baseline: None,
            check_baseline: Some("custom.toml".to_string()),
            tolerance: None,
            quiet: false,
            validate: false,
            profile: None,
            derive_limits: None,
            from: None,
            margin_cpu: None,
            margin_memory: None,
            margin_read: None,
            margin_write: None,
            provenance_out: None,
            totals: false,
        };
        assert_eq!(
            Mode::from_args(&check),
            Mode::Check(PathBuf::from("custom.toml"))
        );
    }

    #[test]
    fn mode_detects_derive() {
        let args = BudgetReportArgs {
            init: false,
            force: false,
            network: None,
            source: None,
            json: false,
            format: Default::default(),
            check: false,
            fail_fast: false,
            csv: false,
            concurrency: Default::default(),
            record_baseline: None,
            check_baseline: None,
            tolerance: None,
            quiet: false,
            validate: false,
            profile: None,
            derive_limits: Some("tier-a-limits.env".to_string()),
            from: None,
            margin_cpu: None,
            margin_memory: None,
            margin_read: None,
            margin_write: None,
            provenance_out: None,
            totals: false,
        };
        match Mode::from_args(&args) {
            Mode::Derive(out, _) => assert_eq!(out, PathBuf::from("tier-a-limits.env")),
            other => panic!("expected Derive mode, got {other:?}"),
        }
    }

    const SHARED_BUDGET_TOML: &str = r#"
network = "testnet"
source = "alice"

[functions.do_expensive_work]
args = ["--n", "10000"]

[functions.require_auth_only]
args = []

[lints]
some_key = "value"
"#;

    #[test]
    fn shared_budget_toml_parses_with_foreign_sections() {
        let config: BudgetToml = toml::from_str(SHARED_BUDGET_TOML)
            .expect("shared budget.toml with foreign [lints] section should parse");
        assert_eq!(config.network.as_deref(), Some("testnet"));
        assert_eq!(config.source.as_deref(), Some("alice"));
        assert!(config.functions.contains_key("do_expensive_work"));
        assert!(config.functions.contains_key("require_auth_only"));
    }

    #[test]
    fn unknown_function_keys_produce_error() {
        let err =
            toml::from_str::<BudgetToml>("[functions.do_expensive_work]\ncpu_lmit = 5000000\n")
                .unwrap_err();
        let err_text = err.to_string();
        assert!(
            err_text.contains("unknown field") || err_text.contains("cpu_lmit"),
            "expected error mentioning unknown field or the offending key, got: {err_text}"
        );
    }

    #[test]
    fn known_function_key_spelling_produces_correct_deserialization() {
        let config: BudgetToml = toml::from_str(
            r#"
[functions.do_expensive_work]
cpu_limit = 5000000
read_limit = 5000
write_limit = 1000
"#,
        )
        .expect("valid function config should parse");
        let func = &config.functions["do_expensive_work"];
        assert_eq!(func.cpu_limit, Some(5000000));
        assert_eq!(func.read_limit, Some(5000));
        assert_eq!(func.write_limit, Some(1000));
    }

    #[test]
    fn percentage_limits_parse_correctly_from_toml() {
        let config: BudgetToml = toml::from_str(
            r#"
[functions.do_expensive_work]
cpu_limit_pct = 50
read_limit_pct = 10
write_limit_pct = 5
"#,
        )
        .expect("valid function config with percentage limits should parse");
        let func = &config.functions["do_expensive_work"];
        assert_eq!(func.cpu_limit, None);
        assert_eq!(func.cpu_limit_pct, Some(50));
        assert_eq!(func.read_limit, None);
        assert_eq!(func.read_limit_pct, Some(10));
        assert_eq!(func.write_limit, None);
        assert_eq!(func.write_limit_pct, Some(5));
    }

    #[test]
    fn mixed_absolute_and_percentage_limits_parse_correctly() {
        let config: BudgetToml = toml::from_str(
            r#"
[functions.do_expensive_work]
cpu_limit = 5000000
read_limit_pct = 25
write_limit = 1000
"#,
        )
        .expect("mixed absolute and percentage limits should parse");
        let func = &config.functions["do_expensive_work"];
        assert_eq!(func.cpu_limit, Some(5000000));
        assert_eq!(func.cpu_limit_pct, None);
        assert_eq!(func.read_limit, None);
        assert_eq!(func.read_limit_pct, Some(25));
        assert_eq!(func.write_limit, Some(1000));
        assert_eq!(func.write_limit_pct, None);
    }

    #[test]
    fn percentage_limits_report_only_no_absolute_limits() {
        let config: BudgetToml = toml::from_str(
            r#"
[functions.do_expensive_work]
cpu_limit_pct = 50
"#,
        )
        .expect("percentage-only config should parse");
        let func = &config.functions["do_expensive_work"];
        assert_eq!(func.cpu_limit, None);
        assert_eq!(func.cpu_limit_pct, Some(50));
        assert_eq!(func.read_limit, None);
        assert_eq!(func.read_limit_pct, None);
        assert_eq!(func.write_limit, None);
        assert_eq!(func.write_limit_pct, None);
    }

    // --- TransactionData deserialization tests ---

    #[test]
    fn transaction_data_parsing_deserializes_successfully() {
        let json_str = r#"{"resources": {"instructions": 1000, "disk_read_bytes": 2048, "write_bytes": 3072}}"#;
        let tx_data = TransactionData::parse_json(json_str).expect("Parsing should succeed");
        assert_eq!(tx_data.resources.instructions, 1000);
        assert_eq!(tx_data.resources.disk_read_bytes, 2048);
        assert_eq!(tx_data.resources.write_bytes, 3072);
    }

    #[test]
    fn transaction_data_parsing_fails_on_missing_field() {
        let json_str = r#"{"resources": {"instructions": 1000, "disk_read_bytes": 2048}}"#;
        let result = TransactionData::parse_json(json_str);
        assert!(result.is_err(), "Parsing should fail on missing field");
        let err_msg = format!("{:#}", result.as_ref().unwrap_err());
        assert!(
            err_msg.contains("write_bytes"),
            "Error should mention missing field, got: {}",
            err_msg
        );
    }

    #[test]
    fn transaction_data_parsing_fails_on_non_numeric_field() {
        let json_str = r#"{"resources": {"instructions": "not-a-number", "disk_read_bytes": 2048, "write_bytes": 3072}}"#;
        let result = TransactionData::parse_json(json_str);
        assert!(result.is_err(), "Parsing should fail on non-numeric field");
        let err_msg = format!("{:#}", result.as_ref().unwrap_err());
        assert!(
            err_msg.contains("invalid type") || err_msg.contains("not-a-number"),
            "Error should mention type mismatch, got: {}",
            err_msg
        );
    }

    // --- Cost value formatter tests ---

    #[test]
    fn formatter_zero_cpu() {
        assert_eq!(
            format_with_commas_and_units(0, "CPU Instructions"),
            "0 inst."
        );
    }

    #[test]
    fn formatter_zero_bytes() {
        assert_eq!(format_with_commas_and_units(0, "Read Bytes"), "0 B");
    }

    #[test]
    fn formatter_single_digit_cpu() {
        assert_eq!(
            format_with_commas_and_units(7, "CPU Instructions"),
            "7 inst."
        );
    }

    #[test]
    fn formatter_single_digit_bytes() {
        assert_eq!(format_with_commas_and_units(3, "Write Bytes"), "3 B");
    }

    #[test]
    fn formatter_just_below_thousand() {
        assert_eq!(
            format_with_commas_and_units(999, "CPU Instructions"),
            "999 inst."
        );
    }

    #[test]
    fn formatter_at_thousand() {
        assert_eq!(
            format_with_commas_and_units(1_000, "CPU Instructions"),
            "1,000 inst."
        );
    }

    #[test]
    fn formatter_just_above_thousand() {
        assert_eq!(
            format_with_commas_and_units(1_001, "CPU Instructions"),
            "1,001 inst."
        );
    }

    #[test]
    fn formatter_just_below_million() {
        assert_eq!(
            format_with_commas_and_units(999_999, "Read Bytes"),
            "999,999 B"
        );
    }

    #[test]
    fn formatter_at_million() {
        assert_eq!(
            format_with_commas_and_units(1_000_000, "CPU Instructions"),
            "1,000,000 inst."
        );
    }

    #[test]
    fn formatter_just_above_million() {
        assert_eq!(
            format_with_commas_and_units(1_000_001, "Write Bytes"),
            "1,000,001 B"
        );
    }

    #[test]
    fn formatter_ten_million() {
        assert_eq!(
            format_with_commas_and_units(10_000_000, "CPU Instructions"),
            "10,000,000 inst."
        );
    }

    #[test]
    fn formatter_u32_max_cpu() {
        assert_eq!(
            format_with_commas_and_units(u64::from(u32::MAX), "CPU Instructions"),
            "4,294,967,295 inst."
        );
    }

    #[test]
    fn formatter_u32_max_bytes() {
        assert_eq!(
            format_with_commas_and_units(u64::from(u32::MAX), "Read Bytes"),
            "4,294,967,295 B"
        );
    }

    #[test]
    fn formatter_write_bytes_gets_byte_unit() {
        assert_eq!(
            format_with_commas_and_units(4_096, "Write Bytes"),
            "4,096 B"
        );
    }

    #[test]
    fn formatter_non_bytes_metric_gets_inst_unit() {
        assert_eq!(
            format_with_commas_and_units(500, "Some Other Metric"),
            "500 inst."
        );
    }

    // --- CSV serialization tests ---

    /// Helper to serialize a slice of CostReport to CSV bytes and return the
    /// result as a String, using the same logic as the `--csv` output path.
    fn reports_to_csv(reports: &[CostReport], check: bool) -> String {
        let mut wtr = csv::Writer::from_writer(vec![]);
        if check {
            wtr.write_record(["package", "function", "metric", "value", "limit", "pass"])
                .unwrap();
            for r in reports {
                let value_str = r.value.map(|v| v.to_string()).unwrap_or_default();
                let limit_str = r.limit.map(|l| l.to_string()).unwrap_or_default();
                let pass_str = r.pass.map(|p| p.to_string()).unwrap_or_default();
                wtr.write_record([
                    r.package.as_str(),
                    r.function.as_str(),
                    r.metric,
                    value_str.as_str(),
                    limit_str.as_str(),
                    pass_str.as_str(),
                ])
                .unwrap();
            }
        } else {
            wtr.write_record(["package", "function", "metric", "value"])
                .unwrap();
            for r in reports {
                if r.value.is_some() {
                    let value_str = r.value.map(|v| v.to_string()).unwrap_or_default();
                    wtr.write_record([
                        r.package.as_str(),
                        r.function.as_str(),
                        r.metric,
                        value_str.as_str(),
                    ])
                    .unwrap();
                }
            }
        }
        wtr.flush().unwrap();
        String::from_utf8(wtr.into_inner().unwrap()).unwrap()
    }

    #[test]
    fn csv_output_without_check_has_four_columns() {
        let reports = vec![
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "CPU Instructions",
                value: Some(1_000_000),
                limit: None,
                pass: None,
                ..Default::default()
            },
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "Read Bytes",
                value: Some(2_048),
                limit: None,
                pass: None,
                ..Default::default()
            },
        ];
        let csv = module_32::reports_to_csv(&reports, false);
        let expected = concat!(
            "package,function,metric,value\n",
            "my-contract,do_work,CPU Instructions,1000000\n",
            "my-contract,do_work,Read Bytes,2048\n",
        );
        assert_eq!(csv, expected);
    }

    #[test]
    fn csv_output_with_check_has_six_columns() {
        let reports = vec![
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "CPU Instructions",
                value: Some(1_000_000),
                limit: Some(5_000_000),
                pass: Some(true),
                ..Default::default()
            },
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "Write Bytes",
                value: Some(4_096),
                limit: Some(1_000),
                pass: Some(false),
                ..Default::default()
            },
        ];
        let csv = module_32::reports_to_csv(&reports, true);
        let expected = concat!(
            "package,function,metric,value,limit,pass\n",
            "my-contract,do_work,CPU Instructions,1000000,5000000,true\n",
            "my-contract,do_work,Write Bytes,4096,1000,false\n",
        );
        assert_eq!(csv, expected);
    }

    #[test]
    fn csv_output_without_check_excludes_null_values() {
        let reports = vec![
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "CPU Instructions",
                value: None,
                limit: None,
                pass: None,
                ..Default::default()
            },
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "Read Bytes",
                value: Some(2_048),
                limit: None,
                pass: None,
                ..Default::default()
            },
        ];
        let csv = module_32::reports_to_csv(&reports, false);
        let expected = concat!(
            "package,function,metric,value\n",
            "my-contract,do_work,Read Bytes,2048\n",
        );
        assert_eq!(csv, expected);
    }

    #[test]
    fn csv_output_with_check_includes_simulation_failures() {
        let reports = vec![CostReport {
            package: "my-contract".to_string(),
            function: "do_work".to_string(),
            metric: "CPU Instructions",
            value: None,
            limit: Some(5_000_000),
            pass: Some(false),
            ..Default::default()
        }];
        let csv = module_32::reports_to_csv(&reports, true);
        let expected = concat!(
            "package,function,metric,value,limit,pass\n",
            "my-contract,do_work,CPU Instructions,,5000000,false\n",
        );
        assert_eq!(csv, expected);
    }

    #[test]
    fn csv_output_empty_reports_produces_header_only() {
        let reports: Vec<CostReport> = vec![];
        let csv = module_32::reports_to_csv(&reports, false);
        assert_eq!(csv, "package,function,metric,value\n");
    }

    // ── JSON serialization tests ────────────────────────────────────────

    /// Helper to serialize a slice of CostReport to a pretty-printed JSON
    /// string, matching the `--json` output path.
    fn reports_to_json(reports: &[CostReport]) -> String {
        serde_json::to_string_pretty(reports).unwrap()
    }

    #[test]
    fn json_output_without_check_has_package_function_metric_value() {
        let reports = vec![
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "CPU Instructions",
                value: Some(1_000_000),
                limit: None,
                pass: None,
                ..Default::default()
            },
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "Read Bytes",
                value: Some(2_048),
                limit: None,
                pass: None,
                ..Default::default()
            },
        ];
        let json = reports_to_json(&reports);
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        let arr = parsed.as_array().unwrap();
        assert_eq!(arr.len(), 2);

        assert_eq!(arr[0]["package"], "my-contract");
        assert_eq!(arr[0]["function"], "do_work");
        assert_eq!(arr[0]["metric"], "CPU Instructions");
        assert_eq!(arr[0]["value"], 1_000_000);
        assert!(arr[0].get("limit").is_none());
        assert!(arr[0].get("pass").is_none());

        assert_eq!(arr[1]["package"], "my-contract");
        assert_eq!(arr[1]["function"], "do_work");
        assert_eq!(arr[1]["metric"], "Read Bytes");
        assert_eq!(arr[1]["value"], 2_048);
        assert!(arr[1].get("limit").is_none());
        assert!(arr[1].get("pass").is_none());
    }

    #[test]
    fn json_output_with_check_includes_limit_and_pass() {
        let reports = vec![
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "CPU Instructions",
                value: Some(1_000_000),
                limit: Some(5_000_000),
                pass: Some(true),
                ..Default::default()
            },
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "Write Bytes",
                value: Some(4_096),
                limit: Some(1_000),
                pass: Some(false),
                ..Default::default()
            },
        ];
        let json = reports_to_json(&reports);
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        let arr = parsed.as_array().unwrap();
        assert_eq!(arr.len(), 2);

        assert_eq!(arr[0]["package"], "my-contract");
        assert_eq!(arr[0]["function"], "do_work");
        assert_eq!(arr[0]["metric"], "CPU Instructions");
        assert_eq!(arr[0]["value"], 1_000_000);
        assert_eq!(arr[0]["limit"], 5_000_000);
        assert_eq!(arr[0]["pass"], true);

        assert_eq!(arr[1]["package"], "my-contract");
        assert_eq!(arr[1]["function"], "do_work");
        assert_eq!(arr[1]["metric"], "Write Bytes");
        assert_eq!(arr[1]["value"], 4_096);
        assert_eq!(arr[1]["limit"], 1_000);
        assert_eq!(arr[1]["pass"], false);
    }

    #[test]
    fn json_output_without_check_excludes_null_values() {
        let reports = vec![
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "CPU Instructions",
                value: None,
                limit: None,
                pass: None,
                ..Default::default()
            },
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "Read Bytes",
                value: Some(2_048),
                limit: None,
                pass: None,
                ..Default::default()
            },
        ];
        let json = reports_to_json(&reports);
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        let arr = parsed.as_array().unwrap();
        assert_eq!(arr.len(), 2);

        // The CPU Instructions entry has value: None; with
        // skip_serializing_if, "value" is absent from the JSON object.
        assert!(arr[0].get("value").is_none());
        // But the entry itself is still present in the array.
        assert_eq!(arr[0]["metric"], "CPU Instructions");

        assert_eq!(arr[1]["metric"], "Read Bytes");
        assert_eq!(arr[1]["value"], 2_048);
    }

    #[test]
    fn json_output_with_check_includes_simulation_failures() {
        let reports = vec![CostReport {
            package: "my-contract".to_string(),
            function: "do_work".to_string(),
            metric: "CPU Instructions",
            value: None,
            limit: Some(5_000_000),
            pass: Some(false),
            ..Default::default()
        }];
        let json = reports_to_json(&reports);
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        let arr = parsed.as_array().unwrap();
        assert_eq!(arr.len(), 1);

        assert_eq!(arr[0]["package"], "my-contract");
        assert_eq!(arr[0]["function"], "do_work");
        assert_eq!(arr[0]["metric"], "CPU Instructions");
        assert!(arr[0].get("value").is_none());
        assert_eq!(arr[0]["limit"], 5_000_000);
        assert_eq!(arr[0]["pass"], false);
    }

    #[test]
    fn json_output_empty_reports_produces_empty_array() {
        let reports: Vec<CostReport> = vec![];
        let json = reports_to_json(&reports);
        assert_eq!(json, "[]");
    }

    #[test]
    fn json_output_with_all_metric_types() {
        let reports = vec![
            CostReport {
                package: "pkg".to_string(),
                function: "f".to_string(),
                metric: "CPU Instructions",
                value: Some(1_000_000),
                limit: None,
                pass: None,
                ..Default::default()
            },
            CostReport {
                package: "pkg".to_string(),
                function: "f".to_string(),
                metric: "Read Bytes",
                value: Some(2_048),
                limit: None,
                pass: None,
                ..Default::default()
            },
            CostReport {
                package: "pkg".to_string(),
                function: "f".to_string(),
                metric: "Write Bytes",
                value: Some(4_096),
                limit: None,
                pass: None,
                ..Default::default()
            },
            CostReport {
                package: "pkg".to_string(),
                function: "f".to_string(),
                metric: "WASM Bytes",
                value: Some(12_345),
                limit: None,
                pass: None,
                ..Default::default()
            },
        ];
        let json = reports_to_json(&reports);
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        let arr = parsed.as_array().unwrap();
        assert_eq!(arr.len(), 4);

        let metrics: Vec<&str> = arr.iter().map(|r| r["metric"].as_str().unwrap()).collect();
        assert_eq!(
            metrics,
            vec![
                "CPU Instructions",
                "Read Bytes",
                "Write Bytes",
                "WASM Bytes"
            ]
        );
    }
}
