use crate::derive::{DerivationConfig, Margin};
use crate::module_10::{Error, Result, SimulationFailure, SimulationOutcome};
use anyhow::Context;
mod compare;
use cargo_metadata::MetadataCommand;
use clap::Parser;
use compare::{
    build_baseline, check_against_baseline, max_allowed as max_allowed_metric, parse_tolerance,
    render_report_text, Baseline, Measurement, Tolerance,
};
use indicatif::{ProgressBar, ProgressStyle};
use serde::Serialize;
use std::collections::{BTreeMap, HashMap, HashSet};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::thread;
use std::time::Duration;
use stellar_xdr::curr::{Limits, ReadXdr, SorobanTransactionData};
use tabled::{Table, Tabled};
use wasmparser::Parser as WasmParser;

mod derive;
mod module_10;

/// Maximum number of total deployment attempts (1 initial + 3 retries)
/// when friendbot funding is suspected to have failed transiently
/// (rate-limiting, network hiccups, or the account not being fully
/// confirmed on-ledger yet).
const MAX_DEPLOY_ATTEMPTS: u32 = 4;

/// Initial backoff delay between deployment retries. Doubles on each
/// subsequent attempt (2 s → 4 s → 8 s).
const INITIAL_RETRY_DELAY_SECS: u64 = 2;

/// Commented budget.toml template written by `cargo budget-report --init`.
const BUDGET_TOML_TEMPLATE: &str = r#"# -- Budget report configuration ---------------------------------------------
# Generated by `cargo budget-report --init`.
# See https://github.com/Tollcraft/soroban-budget-assert for the full reference.

# Target network for contract simulation.
# Supported values: "testnet", "futurenet", "local" (for a local container),
# or any custom network defined in your Stellar CLI config.
network = "testnet"

# Stellar source account keypair name (as configured in your Stellar CLI).
source = "alice"

# -- Per-function configuration ----------------------------------------------
# Declare one section per contract function you want to simulate and
# optionally enforce limits against.
#
#   [functions.<function_name>]
#   args = ["--arg1", "value1"]   # CLI arguments forwarded to the function
#   cpu_limit  = 5000000          # optional, inclusive CPU instruction limit
#   read_limit = 5000             # optional, inclusive read-bytes limit
#   write_limit = 1000            # optional, inclusive write-bytes limit
#
# A missing `*_limit` field means that metric is reported but not enforced.
# See `cargo budget-report --check` for limit enforcement.
# Unknown keys inside a [functions.*] block produce an error.
#
# Foreign top-level sections (e.g. [lints] for soroban-cost-linter) are
# silently accepted so that both tools can share a single budget.toml.

[functions.do_expensive_work]
args = ["--n", "10000"]
cpu_limit = 5000000
read_limit = 5000
write_limit = 1000
"#;

/// Top-level CLI entry point for `cargo budget-report`.
///
/// Wraps the binary in a `cargo <subcommand>` compatible enum so it can be
/// invoked as `cargo budget-report [OPTIONS]`.
#[derive(Parser, Debug)]
#[command(name = "cargo", bin_name = "cargo")]
enum CargoCli {
    BudgetReport(BudgetReportArgs),
}

/// CLI arguments for `cargo budget-report`.
///
/// All fields are optional; missing values fall back to the corresponding
/// `budget.toml` configuration when available.
#[derive(Parser, Debug)]
struct BudgetReportArgs {
    /// Scaffold a commented `budget.toml` template and exit.
    #[arg(long)]
    init: bool,

    /// Allow `--init` to overwrite an existing `budget.toml`.
    #[arg(long)]
    force: bool,

    #[arg(long)]
    network: Option<String>,

    #[arg(long)]
    source: Option<String>,

    #[arg(long, default_value_t = false)]
    json: bool,

    /// Enforce per-function limits declared in `budget.toml`.
    ///
    /// When set, each measured metric is compared against its configured
    /// `cpu_limit` / `read_limit` / `write_limit`. A missing limit means the
    /// metric is reported but **not** enforced. The process exits with a
    /// non-zero status when any limit is breached, or when a function that
    /// has a `budget.toml` entry fails to simulate. Functions that are not
    /// declared in `budget.toml` are reported only.
    #[arg(long, default_value_t = false)]
    check: bool,

    /// Emit the report as CSV instead of a table or JSON.
    #[arg(long, default_value_t = false)]
    csv: bool,

    /// Write a new resource-usage baseline snapshot to this path and exit.
    #[arg(long)]
    record_baseline: Option<String>,

    /// Check current measurements against an existing baseline snapshot at
    /// this path, applying the configured regression tolerance.
    #[arg(long)]
    check_baseline: Option<String>,

    /// Override the regression tolerance (e.g. "0.10" for 10%). Takes
    /// precedence over `tolerance` in `budget.toml`.
    #[arg(long)]
    tolerance: Option<String>,

    /// Suppress non-essential progress messages and warnings on stderr.
    ///
    /// The final report (table, JSON, or CSV) is still printed to stdout.
    /// Fatal errors from child-process spawn failures or hard contract
    /// build failures are not suppressed — they always go to stderr
    /// regardless of this flag.
    #[arg(long, default_value_t = false)]
    quiet: bool,

    /// Validate reported metrics against the Stellar CLI's own XDR decoder.
    ///
    /// For each successfully simulated function, the base64 SorobanTransactionData
    /// XDR from the RPC response is re-decoded through `stellar xdr decode` and
    /// the resulting metrics are compared against cargo-budget-report's values.
    /// Any discrepancy is reported as a diagnostic; the tool still exits with a
    /// non-zero status when mismatches are found.
    ///
    /// Validation is skipped (not failed) when the Stellar CLI or the `xdr decode`
    /// subcommand is unavailable.
    #[arg(long, default_value_t = false)]
    validate: bool,

    /// Cargo build profile to use when compiling the contract WASM.
    ///
    /// Defaults to `release` when not provided. Custom profiles (e.g.
    /// `release-opt`) must be defined in the project's `Cargo.toml`.
    #[arg(long)]
    profile: Option<String>,

    /// Derive local (Tier A) test limits from a Tier B JSON report and
    /// exit. Reads the Tier B report from `--from <PATH>` (or stdin if
    /// `--from -`) and writes the chosen `KEY=VALUE` shape to the file
    /// at `<OUT>`.
    ///
    /// The Tier B report is the same JSON shape `cargo budget-report
    /// --json` emits — either the bare array of `CostReport`-shaped
    /// rows or the `{schema_version, snapshots}` wrapped form. The
    /// `--margin-{cpu,memory,read,write}` flags (or the `[margin]`
    /// section of `budget.toml`) supply the per-metric multipliers
    /// applied to the Tier B values; the resulting ceilings become
    /// Tier A test limits.
    ///
    /// The function-to-scenario mapping is recorded under
    /// `[[scenarios.<name>]]` blocks in `budget.toml` so component
    /// limits can be summed under a single Tier A `KEY=VALUE` for
    /// tests that exercise multi-step workflows.
    #[arg(long, value_name = "OUT")]
    derive_limits: Option<String>,

    /// Source Tier B JSON report for `--derive-limits`. Use `-` to
    /// read JSON from stdin (so `cargo budget-report --json | cargo
    /// budget-report --derive-limits tier-a-limits.env` composes).
    #[arg(long, value_name = "PATH")]
    from: Option<String>,

    /// Per-metric multiplier applied to Tier B CPU values. Required
    /// unless `[margin].cpu_margin` is set in `budget.toml`; no
    /// default is applied because the project deliberately treats the
    /// margin as data (issue #45) and silently picking a value would
    /// defeat the audit trail.
    #[arg(long, value_name = "F")]
    margin_cpu: Option<String>,

    /// Per-metric multiplier applied to Tier B memory values.
    #[arg(long, value_name = "F")]
    margin_memory: Option<String>,

    /// Per-metric multiplier applied to Tier B read-bytes values.
    #[arg(long, value_name = "F")]
    margin_read: Option<String>,

    /// Per-metric multiplier applied to Tier B write-bytes values.
    #[arg(long, value_name = "F")]
    margin_write: Option<String>,

    /// Path to write the Markdown provenance table next to the env
    /// file. Defaults to `<OUT>` with `.env` replaced by `.md` (e.g.
    /// `tier-a-limits.provenance.md` for `tier-a-limits.env`).
    #[arg(long, value_name = "PATH")]
    provenance_out: Option<String>,
}

/// Top-level configuration deserialized from `budget.toml`.
///
/// Contains optional network and source-account overrides, plus a map of
/// per-function budget configurations keyed by exported function name.
#[derive(serde::Deserialize, Default, Debug)]
struct BudgetToml {
    network: Option<String>,
    source: Option<String>,
    /// Global default tolerance, used unless overridden per function or by `--tolerance`.
    #[serde(default)]
    tolerance: Option<f64>,
    #[serde(default)]
    margin: Option<MarginToml>,
    /// Per-function `[[scenarios.<name>]]` table mapping a scenario to
    /// the list of component function names it sums over. Keys mirror
    /// the `(package, scenario_name)` namespace used by
    /// `derive::env_var_scenario_key`.
    #[serde(default)]
    scenarios: HashMap<String, ScenarioToml>,
    #[serde(default)]
    functions: HashMap<String, FunctionConfig>,
}

/// Per-metric margin multipliers persisted in `budget.toml`.
///
/// All four fields are independently optional, but `Margin::new`
/// rejects any incomplete configuration at use-time — the
/// `cargo budget-report --derive-limits` flow propagates that error so
/// a half-set `[margin]` block cannot silently degrade to no margin.
#[derive(serde::Deserialize, Default, Debug, Clone, Copy)]
struct MarginToml {
    #[serde(default)]
    cpu_margin: Option<f64>,
    #[serde(default)]
    memory_margin: Option<f64>,
    #[serde(default)]
    read_margin: Option<f64>,
    #[serde(default)]
    write_margin: Option<f64>,
}

impl MarginToml {
    /// Build a [`Margin`] from this record. None of the fields are
    /// allowed to be missing — the caller is responsible for sourcing
    /// missing values from the CLI / failing the run.
    fn into_margin(self) -> Result<Margin> {
        let cpu = self
            .cpu_margin
            .ok_or_else(|| Error::Message("missing margin.cpu_margin in budget.toml".into()))?;
        let memory = self
            .memory_margin
            .ok_or_else(|| Error::Message("missing margin.memory_margin in budget.toml".into()))?;
        let read = self
            .read_margin
            .ok_or_else(|| Error::Message("missing margin.read_margin in budget.toml".into()))?;
        let write = self
            .write_margin
            .ok_or_else(|| Error::Message("missing margin.write_margin in budget.toml".into()))?;
        Margin::new(cpu, memory, read, write)
    }

    /// True when every margin field is set. Used by `derive-mode` to
    /// reject a half-configured file before falling back to CLI args.
    fn is_complete(&self) -> bool {
        self.cpu_margin.is_some()
            && self.memory_margin.is_some()
            && self.read_margin.is_some()
            && self.write_margin.is_some()
    }
}

/// One scenario declaration in the `[[scenarios]]` table.
#[derive(serde::Deserialize, Default, Debug, Clone)]
struct ScenarioToml {
    /// (package, scenario_name) namespace prefix used to scope this
    /// scenario. Without a package, the scenario is treated as package
    /// `""`, which is rarely what callers want — the error path
    /// surfaces that problem.
    #[serde(default)]
    package: Option<String>,
    /// Names of component functions whose Tier B values sum into this
    /// scenario's Tier A limit.
    #[serde(default)]
    functions: Vec<String>,
}

/// Raw resource metrics returned by the Soroban `simulateTransaction` RPC.
///
/// Maps directly to the `resources` field of a `SorobanTransactionData` XDR
/// object decoded from the RPC response.
#[allow(dead_code)]
#[derive(serde::Deserialize, Debug)]
struct Resources {
    instructions: u64,
    disk_read_bytes: u64,
    write_bytes: u64,
}

/// Top-level wrapper for the deserialized `simulateTransaction` response.
///
/// Currently only carries the `resources` sub-object, but exists as a
/// named type so that additional RPC response fields can be added without
/// changing the extraction call-site.
#[allow(dead_code)]
#[derive(serde::Deserialize, Debug)]
struct TransactionData {
    #[serde(alias = "resources")]
    resources: Resources,
}

impl TransactionData {
    #[cfg(test)]
    fn parse_json(json_str: &str) -> anyhow::Result<Self> {
        let parsed_json: serde_json::Value =
            serde_json::from_str(json_str).context("Failed to parse JSON")?;
        serde_json::from_value(parsed_json).context("Failed to deserialize transaction data")
    }
}

/// Per-function configuration read from a `[functions.<name>]` section of
/// `budget.toml`.
///
/// Controls which CLI arguments are forwarded to the contract invocation
/// and which resource limits are enforced in `--check` mode.
#[derive(serde::Deserialize, Default, Debug)]
#[serde(deny_unknown_fields)]
struct FunctionConfig {
    #[serde(default)]
    args: Vec<String>,
    /// Inclusive upper bound on the measured CPU `Instructions` metric. `None`
    /// means this metric is reported but not enforced by `--check`.
    #[serde(default)]
    cpu_limit: Option<u64>,
    #[serde(default)]
    read_limit: Option<u64>,
    #[serde(default)]
    write_limit: Option<u64>,
    /// Optional per-function override for the regression tolerance.
    #[serde(default)]
    tolerance: Option<f64>,
}

#[derive(Clone, Copy)]
struct MeasuredResources {
    instructions: u64,
    read_bytes: u64,
    write_bytes: u64,
}

impl MeasuredResources {
    fn as_compare(self) -> Measurement {
        Measurement {
            cpu_instructions: self.instructions,
            read_bytes: self.read_bytes,
            write_bytes: self.write_bytes,
        }
    }
}

/// A single row in the budget report, representing one metric for one
/// exported function of one workspace package.
///
/// In `--check` mode the `limit` and `pass` fields are populated so that
/// consumers (table, JSON, CSV) can render per-metric pass/fail status.
#[derive(Serialize)]
struct CostReport {
    package: String,
    function: String,
    metric: &'static str,
    /// The measured value, or `None` if the simulation failed to produce one
    /// (only emitted in `--check` mode for functions declared in
    /// `budget.toml`).
    #[serde(skip_serializing_if = "Option::is_none")]
    value: Option<u32>,
    /// Configured upper bound for the metric, if any. Emitted in `--check`
    /// mode only.
    #[serde(skip_serializing_if = "Option::is_none")]
    limit: Option<u64>,
    /// `true` if the measured value is within the configured limit, `false`
    /// if it exceeds the limit **or** the simulation failed for a configured
    /// function. Emitted in `--check` mode only.
    #[serde(skip_serializing_if = "Option::is_none")]
    pass: Option<bool>,
}

/// A `CostReport` formatted for rendering in the plain-text [`Table`] output.
///
/// Only rows with a measured value (`value.is_some()`) are included in the
/// table; simulation failures and `--check`-only stubs are filtered out
/// before this type is constructed.
#[derive(Tabled)]
struct TableCostReport {
    package: String,
    function: String,
    metric: &'static str,
    value: String,
}

/// Returns the configured limit (if any) for the given metric name.
fn limit_for_metric(func_config: &FunctionConfig, metric: &str) -> Option<u64> {
    match metric {
        "CPU Instructions" => func_config.cpu_limit,
        "Read Bytes" => func_config.read_limit,
        "Write Bytes" => func_config.write_limit,
        _ => None,
    }
}

/// Given a measured value and an optional configured limit, returns the
/// `(limit, pass)` pair that should be attached to a `CostReport`.
///
/// * No limit configured → `(None, None)`; the metric is reported but not
///   enforced.
/// * Limit configured and value is within it → `(Some(limit), Some(true))`.
/// * Limit configured and value exceeds it → `(Some(limit), Some(false))`;
///   the caller should mark the check as failed.
fn evaluate_check(value: u32, limit: Option<u64>) -> (Option<u64>, Option<bool>) {
    match limit {
        Some(limit_value) => (Some(limit_value), Some(u64::from(value) <= limit_value)),
        None => (None, None),
    }
}

/// Emit one stub `CostReport` per metric (`CPU Instructions`, `Read Bytes`,
/// `Write Bytes`) so that the `--check` JSON output and check summary make
/// the failure visible per metric.
///
/// * Metrics with a configured `*_limit` get `value: None, limit: Some(n),
///   pass: Some(false)` — the consumer can read the breached limit.
/// * Metrics without a configured limit get `value: None, limit: None,
///   pass: Some(false)` — still a hook for `--check --json` consumers, but
///   the table filter (`value.is_some()`) keeps it out of the plain-text
///   report and the summary lines remain unchanged.
///
/// The caller has already set the `checks_failed` flag for the function as a
/// whole, so emitting one entry per metric — even metrics without a limit —
/// does not change the exit-code semantics.
fn emit_check_failure_entries(
    reports: &mut Vec<CostReport>,
    package_name: &str,
    function: &str,
    func_config: &FunctionConfig,
) {
    for metric in ["CPU Instructions", "Read Bytes", "Write Bytes"] {
        let limit = limit_for_metric(func_config, metric);
        reports.push(CostReport {
            package: package_name.to_string(),
            function: function.to_string(),
            metric,
            value: None,
            limit,
            pass: Some(false),
        });
    }
}

/// Formats a `u64` value with commas for readability and appends the
/// appropriate unit suffix (`inst.` for instructions, `B` for bytes).
///
/// # Arguments
///
/// * `value` - The raw numeric value to format.
/// * `metric` - The metric name; if it contains `"Bytes"` the suffix is
///   `B`, otherwise `inst.`.
fn format_with_commas_and_units(value: u64, metric: &str) -> String {
    let value_str = value.to_string();
    let mut result = String::new();
    let mut digit_count = 0;
    for ch in value_str.chars().rev() {
        if digit_count == 3 {
            result.push(',');
            digit_count = 0;
        }
        result.push(ch);
        digit_count += 1;
    }
    let formatted = result.chars().rev().collect::<String>();

    if metric.contains("Bytes") {
        format!("{} B", formatted)
    } else {
        format!("{} inst.", formatted)
    }
}

/// Extracts CPU instructions, read bytes, and write bytes from a
/// `simulateTransaction` JSON-RPC response.
///
/// The response must contain a `result.transactionData` field holding a
/// base64-encoded `SorobanTransactionData` XDR blob.
///
/// # Errors
///
/// Returns an error if the RPC response contains an `"error"` field, if
/// `transactionData` is missing or not a string, or if the base64 XDR
/// cannot be decoded.
fn extract_metrics(rpc_response: &serde_json::Value) -> Result<(u32, u32, u32)> {
    if let Some(error) = rpc_response.get("error") {
        return Err(Error::Rpc(error.to_string()));
    }

    if let Some(error) = rpc_response.get("result").and_then(|r| r.get("error")) {
        let err_msg = error.as_str().unwrap_or("");
        if !err_msg.is_empty() {
            return Err(Error::Rpc(err_msg.to_string()));
        } else {
            return Err(Error::Rpc(error.to_string()));
        }
    }

    let tx_data_b64 = rpc_response["result"]["transactionData"]
        .as_str()
        .ok_or_else(|| Error::MissingField("transactionData".into()))?;

    // Decode the transaction data natively using the stellar-xdr crate
    // to avoid the overhead and instability of shelling out to the stellar CLI.
    let tx_data = SorobanTransactionData::from_xdr_base64(tx_data_b64, Limits::none())
        .map_err(|e| Error::Xdr(format!("Failed to decode SorobanTransactionData: {}", e)))?;

    Ok((
        tx_data.resources.instructions,
        tx_data.resources.read_bytes,
        tx_data.resources.write_bytes,
    ))
}

/// Builds the `stellar contract invoke --build-only -- <function> [args..]`
/// argument list for one exported function.
///
/// The resulting argument vector is passed directly to `Command::new("stellar")`.
///
/// # Arguments
///
/// * `contract_id` - The deployed contract ID (hex string).
/// * `source` - The Stellar source account keypair name.
/// * `network` - The target network passphrase or alias.
/// * `function` - The exported function name to invoke.
/// * `func_args` - Additional CLI arguments forwarded after the `--` separator.
fn build_invoke_args(
    contract_id: &str,
    source: &str,
    network: &str,
    function: &str,
    func_args: &[String],
) -> Vec<String> {
    let mut invoke_args = vec![
        "contract".to_string(),
        "invoke".to_string(),
        "--id".to_string(),
        contract_id.to_string(),
        "--source".to_string(),
        source.to_string(),
        "--network".to_string(),
        network.to_string(),
        "--build-only".to_string(),
        "--".to_string(),
        function.to_string(),
    ];
    invoke_args.extend(func_args.iter().cloned());
    invoke_args
}

/// Builds the JSON-RPC `simulateTransaction` request body for a base64 XDR
/// transaction envelope.
///
/// The request conforms to the Stellar JSON-RPC v2.0 specification and
/// contains a single `params.transaction` field with the base64-encoded
/// XDR envelope produced by `stellar contract invoke --build-only`.
///
/// # Arguments
///
/// * `b64_xdr` - The base64-encoded XDR transaction envelope.
fn build_rpc_payload(b64_xdr: &str) -> serde_json::Value {
    serde_json::json!({
        "jsonrpc": "2.0",
        "id": 1,
        "method": "simulateTransaction",
        "params": {
            "transaction": b64_xdr
        }
    })
}

/// POSTs a `simulateTransaction` JSON-RPC request for `b64_xdr` and returns
/// the parsed response body.
///
/// Uses `curl` to send the request to the Soroban RPC endpoint. The
/// request body is piped via stdin to avoid shell-quoting issues.
///
/// # Errors
///
/// Returns an error if `curl` cannot be spawned, the request fails, or
/// the response body is not valid JSON.
fn simulate_transaction_rpc(b64_xdr: &str) -> Result<serde_json::Value> {
    let rpc_payload = build_rpc_payload(b64_xdr);

    let mut curl = Command::new("curl")
        .args([
            "-s",
            "-X",
            "POST",
            "-H",
            "Content-Type: application/json",
            "-d",
            "@-",
            "https://soroban-testnet.stellar.org:443",
        ])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .map_err(|e| Error::CommandFailed(format!("failed to execute curl: {}", e)))?;

    {
        let stdin = curl
            .stdin
            .as_mut()
            .ok_or_else(|| Error::CommandFailed("Failed to open stdin".into()))?;
        stdin
            .write_all(rpc_payload.to_string().as_bytes())
            .map_err(|e| Error::CommandFailed(format!("failed to write to stdin: {}", e)))?;
    }

    let curl_output = curl
        .wait_with_output()
        .map_err(|e| Error::CommandFailed(format!("failed to read curl output: {}", e)))?;
    serde_json::from_slice(&curl_output.stdout)
        .map_err(|e| Error::Message(format!("Failed to parse RPC response: {}", e)))
}

/// Simulates one exported function end-to-end: runs
/// `stellar contract invoke --build-only` to build the transaction, then
/// POSTs it to `simulateTransaction` and decodes the reported resource
/// usage.
///
/// Returns `Err` only for a spawn/IO failure on the `stellar`/`curl` child
/// processes — the tool cannot proceed without those binaries. A
/// *recoverable* simulation failure (non-zero invoke exit, an RPC `error`
/// field, or an undecodable response) is reported as
/// `Ok(SimulationOutcome::Failed(..))` so the caller can move on to the next
/// function instead of aborting the whole report.
fn simulate_function(
    contract_id: &str,
    source: &str,
    network: &str,
    function: &str,
    func_args: &[String],
) -> Result<SimulationOutcome> {
    let invoke_args = build_invoke_args(contract_id, source, network, function, func_args);
    let invoke_output = Command::new("stellar")
        .args(&invoke_args)
        .output()
        .map_err(|e| {
            Error::CommandFailed(format!("failed to execute stellar-cli invoke: {}", e))
        })?;

    if !invoke_output.status.success() {
        let stderr = String::from_utf8_lossy(&invoke_output.stderr).to_string();
        return Ok(SimulationOutcome::Failed(SimulationFailure::Invoke(stderr)));
    }

    let b64_xdr = String::from_utf8_lossy(&invoke_output.stdout)
        .trim()
        .to_string();
    let rpc_resp = simulate_transaction_rpc(&b64_xdr)?;

    if let Some(error) = rpc_resp.get("error") {
        return Ok(SimulationOutcome::Failed(SimulationFailure::Rpc(
            error.to_string(),
        )));
    }

    // Capture the raw transactionData XDR before decode, so --validate
    // can re-decode it through the Stellar CLI independently.
    let tx_data_xdr_b64 = rpc_resp["result"]["transactionData"]
        .as_str()
        .map(|s| s.to_string());

    match extract_metrics(&rpc_resp) {
        Ok((instructions, read_bytes, write_bytes)) => Ok(SimulationOutcome::Metrics {
            instructions,
            read_bytes,
            write_bytes,
            transaction_data_xdr: tx_data_xdr_b64.unwrap_or_default(),
        }),
        Err(err) => Ok(SimulationOutcome::Failed(
            SimulationFailure::MetricsExtraction(format!("{:#}", err)),
        )),
    }
}

/// Loads and parses a `budget.toml` configuration file.
///
/// If the file does not exist, returns a default (empty) configuration
/// so that callers can proceed without explicit error handling.
///
/// # Errors
///
/// Returns an error if the file exists but cannot be read or parsed.
fn load_budget_toml<P: AsRef<Path>>(path: P) -> Result<BudgetToml> {
    match std::fs::read_to_string(&path) {
        Ok(contents) => {
            let trimmed = contents.trim();
            if trimmed.is_empty()
                || trimmed
                    .lines()
                    .all(|line| line.trim().is_empty() || line.trim_start().starts_with('#'))
            {
                return Ok(BudgetToml::default());
            }

            toml::from_str(&contents).map_err(Error::Toml)
        }
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(BudgetToml::default()),
        Err(err) => Err(Error::Io(err)),
    }
}

fn resolve_tolerance(cli_override: Option<&str>, config: &BudgetToml) -> Result<Tolerance> {
    if let Some(raw) = cli_override {
        return parse_tolerance(raw).map_err(|e| Error::Message(e.to_string()));
    }
    if let Some(t) = config.tolerance {
        return Ok(Tolerance::new(t));
    }
    Ok(Tolerance::default())
}

#[derive(serde::Serialize)]
struct CheckReportJson<'r> {
    has_regressions: bool,
    regression_count: usize,
    default_tolerance: f64,
    regressions: Vec<RegressionJson<'r>>,
    improvements: Vec<ImprovementJson<'r>>,
    new_entries: Vec<NewEntryJson<'r>>,
    stale_entries: Vec<StaleEntryJson<'r>>,
}

#[derive(serde::Serialize)]
struct RegressionJson<'r> {
    package: &'r str,
    function: &'r str,
    metric: &'r str,
    baseline: u64,
    current: u64,
    tolerance: f64,
    max_allowed: u64,
}

#[derive(serde::Serialize)]
struct ImprovementJson<'r> {
    package: &'r str,
    function: &'r str,
    metric: &'r str,
    baseline: u64,
    current: u64,
    tolerance: f64,
}

#[derive(serde::Serialize)]
struct NewEntryJson<'r> {
    package: &'r str,
    function: &'r str,
}

#[derive(serde::Serialize)]
struct StaleEntryJson<'r> {
    package: &'r str,
    function: &'r str,
}

fn render_check_report_json(
    report: &compare::CheckReport,
    default_tolerance: Tolerance,
) -> serde_json::Value {
    let mut regressions = Vec::new();
    let mut improvements = Vec::new();
    for func in &report.compared {
        for m in &func.metrics {
            match m.verdict {
                compare::Verdict::Regression => {
                    regressions.push(RegressionJson {
                        package: &func.package,
                        function: &func.function,
                        metric: m.metric.label(),
                        baseline: m.baseline,
                        current: m.current,
                        tolerance: m.tolerance.value,
                        max_allowed: max_allowed_metric(m.baseline, m.tolerance.value),
                    });
                }
                compare::Verdict::Improvement => {
                    improvements.push(ImprovementJson {
                        package: &func.package,
                        function: &func.function,
                        metric: m.metric.label(),
                        baseline: m.baseline,
                        current: m.current,
                        tolerance: m.tolerance.value,
                    });
                }
                compare::Verdict::Pass => {}
            }
        }
    }
    let new_entries: Vec<_> = report
        .new
        .iter()
        .map(|e| NewEntryJson {
            package: &e.package,
            function: &e.function,
        })
        .collect();
    let stale_entries: Vec<_> = report
        .stale
        .iter()
        .map(|e| StaleEntryJson {
            package: &e.package,
            function: &e.function,
        })
        .collect();
    let summary = CheckReportJson {
        has_regressions: report.has_regressions(),
        regression_count: report.regression_count(),
        default_tolerance: default_tolerance.value,
        regressions,
        improvements,
        new_entries,
        stale_entries,
    };
    serde_json::to_value(summary).expect("CheckReportJson serialization is infallible")
}

/// Scaffold a commented `budget.toml` template. Errors if the file already
/// exists and `force` is not set.
fn scaffold_init(force: bool, quiet: bool) -> Result<()> {
    let path = Path::new("budget.toml");
    if path.exists() && !force {
        return Err(Error::Message(
            "budget.toml already exists; use --force to overwrite".into(),
        ));
    }
    std::fs::write(path, BUDGET_TOML_TEMPLATE)
        .map_err(|e| Error::Message(format!("failed to write {}: {}", path.display(), e)))?;
    if !quiet {
        eprintln!("Wrote {}", path.display());
    }
    Ok(())
}

/// Run environment preflight checks before building or deploying.
///
/// Each check fails fast with an actionable error message. Checks that are
/// not applicable (e.g. rustup not installed) are silently skipped.
fn run_preflight_checks(quiet: bool) -> Result<()> {
    // ── stellar CLI ─────────────────────────────────────────────────────
    if !quiet {
        eprint!("Checking Stellar CLI... ");
    }
    let stellar_check = Command::new("stellar").arg("--version").output();
    match stellar_check {
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            return Err(Error::Message(
                "Stellar CLI is not installed or not on PATH.\n\
                 Install it with:  cargo install --locked stellar-cli\n\
                 See: https://github.com/stellar/stellar-cli"
                    .to_string(),
            ));
        }
        Err(e) => {
            return Err(Error::CommandFailed(format!(
                "failed to execute stellar --version: {}",
                e
            )));
        }
        Ok(output) if !output.status.success() => {
            return Err(Error::CommandFailed(format!(
                "Stellar CLI failed to run.\n\
                 stderr: {}",
                String::from_utf8_lossy(&output.stderr)
            )));
        }
        Ok(_output) => {
            if !quiet {
                eprintln!("found");
            }
        }
    }
    // ── wasm32 target ───────────────────────────────────────────────────
    if !quiet {
        eprint!("Checking wasm32-unknown-unknown target... ");
    }
    let rustup_check = Command::new("rustup")
        .args(["target", "list", "--installed"])
        .output();
    match rustup_check {
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            // rustup is not installed — skip the check silently.
            if !quiet {
                eprintln!("skipped (rustup not found)");
            }
        }
        Err(e) => {
            return Err(Error::CommandFailed(format!(
                "failed to execute rustup: {}",
                e
            )));
        }
        Ok(output) => {
            let installed = String::from_utf8_lossy(&output.stdout);
            if installed
                .lines()
                .any(|line| line.trim() == "wasm32-unknown-unknown")
            {
                if !quiet {
                    eprintln!("found");
                }
            } else {
                return Err(Error::Message(
                    "wasm32-unknown-unknown target is not installed.\n\
                     Install it with:  rustup target add wasm32-unknown-unknown"
                        .to_string(),
                ));
            }
        }
    }

    Ok(())
}

/// Deploys a contract WASM to the network with automatic retry on
/// friendbot-related transient failures.
///
/// The `stellar contract deploy` command implicitly triggers friendbot
/// funding for the source account on testnet. Friendbot may return 429
/// (rate-limited) or the account may not be confirmed on-ledger yet.
/// This function makes up to `MAX_DEPLOY_ATTEMPTS` total attempts with
/// exponential backoff before giving up.
fn deploy_contract_with_retry(
    wasm_path: &Path,
    source: &str,
    network: &str,
    package_name: &str,
) -> Result<String> {
    let mut last_error = String::new();

    for attempt in 0..MAX_DEPLOY_ATTEMPTS {
        if attempt > 0 {
            let delay = INITIAL_RETRY_DELAY_SECS * 2u64.pow(attempt - 1);
            eprintln!(
                "Deploy attempt {}/{} failed. Retrying in {} s...",
                attempt, MAX_DEPLOY_ATTEMPTS, delay
            );
            thread::sleep(Duration::from_secs(delay));
        }

        let deploy_output = Command::new("stellar")
            .args([
                "contract",
                "deploy",
                "--wasm",
                wasm_path
                    .to_str()
                    .ok_or_else(|| Error::Message("wasm path is not valid UTF-8".into()))?,
                "--source",
                source,
                "--network",
                network,
            ])
            .output()
            .map_err(|e| {
                Error::CommandFailed(format!("failed to execute stellar-cli deploy: {}", e))
            })?;

        if deploy_output.status.success() {
            let contract_id = String::from_utf8_lossy(&deploy_output.stdout)
                .trim()
                .to_string();
            return Ok(contract_id);
        }

        last_error = String::from_utf8_lossy(&deploy_output.stderr).to_string();
    }

    Err(Error::Message(format!(
        "Failed to deploy {} after {} attempts. Ensure your source account is funded.\nLast error: {}",
        package_name, MAX_DEPLOY_ATTEMPTS, last_error
    )))
}

fn run_derive_mode(args: &BudgetReportArgs, toml_config: &BudgetToml) -> Result<()> {
    let Mode::Derive(out_env, out_provenance) = Mode::from_args(args) else {
        return Err(Error::Message(
            "internal: run_derive_mode called outside Derive mode".into(),
        ));
    };

    // 1) Read the Tier B JSON report.
    let from_path = args.from.as_deref().unwrap_or("-");
    let source_label = if from_path == "-" {
        "<stdin>".to_string()
    } else {
        from_path.to_string()
    };
    let from_pathbuf = std::path::PathBuf::from(from_path);
    let measurements = derive::load_tier_b_report(&from_pathbuf)?;

    // 2) Resolve the margin. CLI overrides win over `budget.toml`.
    //    Detect missing-vs-present on the CLI side first so a partial
    //    CLI override errors out instead of falling through to the
    //    toml fallback (which would silently change behaviour).
    fn parse_cli_margin(field: &str, raw: Option<&String>) -> Result<Option<f64>> {
        match raw {
            None => Ok(None),
            Some(text) => text
                .trim()
                .parse::<f64>()
                .map(Some)
                .map_err(|e| Error::Message(format!("invalid --margin-{field} `{text}`: {e}"))),
        }
    }
    let cli_parts = [
        ("cpu", parse_cli_margin("cpu", args.margin_cpu.as_ref())?),
        (
            "memory",
            parse_cli_margin("memory", args.margin_memory.as_ref())?,
        ),
        ("read", parse_cli_margin("read", args.margin_read.as_ref())?),
        (
            "write",
            parse_cli_margin("write", args.margin_write.as_ref())?,
        ),
    ];
    let cli_any = cli_parts.iter().any(|(_, v)| v.is_some());

    let margin = if cli_any {
        let missing: Vec<&str> = cli_parts
            .iter()
            .filter_map(|(name, v)| if v.is_none() { Some(*name) } else { None })
            .collect();
        if !missing.is_empty() {
            return Err(Error::Message(format!(
                "CLI margin is partially set; supply all four \
                 --margin-{{cpu,memory,read,write}} flags or none of them \
                 (missing: {missing:?})"
            )));
        }
        let cpu = cli_parts[0].1.unwrap();
        let memory = cli_parts[1].1.unwrap();
        let read = cli_parts[2].1.unwrap();
        let write = cli_parts[3].1.unwrap();
        Margin::new(cpu, memory, read, write)?
    } else {
        match toml_config
            .margin
            .and_then(|m| if m.is_complete() { Some(m) } else { None })
        {
            Some(m) => m.into_margin()?,
            None => {
                return Err(Error::Message(
                    "no margin supplied; pass --margin-cpu / --margin-memory / \
                     --margin-read / --margin-write, or add a complete [margin] \
                     section to budget.toml"
                        .into(),
                ));
            }
        }
    };

    // 3) Lift budget.toml scenarios into the derivation config.
    let scenarios: BTreeMap<String, Vec<String>> = toml_config
        .scenarios
        .iter()
        .map(|(name, s)| {
            let key = match &s.package {
                Some(pkg) => format!("{pkg}::{name}"),
                None => format!("::{name}"),
            };
            (key, s.functions.clone())
        })
        .collect();
    let config = DerivationConfig { margin, scenarios };

    // 4) Run the derivation and write the outputs atomically.
    let derivation = derive::Derivation::from_report(&measurements, &config)?;
    let timestamp_utc = build_utc_timestamp();
    let provenance = out_provenance.unwrap_or_else(|| default_provenance_path(&out_env));
    derive::write_outputs(
        &out_env,
        Some(&provenance),
        &derivation,
        &source_label,
        &margin,
        args.profile.as_deref(),
        &timestamp_utc,
    )?;

    if !args.quiet {
        eprintln!(
            "Wrote {} ({} limits) and {}",
            out_env.display(),
            derivation.limits.len(),
            provenance.display(),
        );
    }
    Ok(())
}

/// Replace `tier-a-limits.env` / `tier-a-limits.json` / etc. with the
/// matching `*.provenance.md` sibling. The split keeps the standard
/// env/provenance pairing intuitive for the common case.
fn default_provenance_path(out_env: &std::path::Path) -> std::path::PathBuf {
    out_env.with_extension("provenance.md")
}

/// UTC ISO-8601 timestamp at second precision — enough granularity
/// for the provenance header without depending on `chrono`.
fn build_utc_timestamp() -> String {
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_err(|e| Error::Message(format!("system time error: {e}")))
        .map(|d| {
            // Approximate UTC seconds-since-epoch using a 0-based
            // bijection: 86400 seconds/day, 365.25 days/year. Good
            // enough for an audit-trail timestamp; rounding to days
            // would also be acceptable.
            d.as_secs()
        })
        .unwrap_or(0);
    // The header timestamp is descriptive, not asserted, so it is
    // fine to format it loosely. The string-form here is the
    // seconds-since-epoch expressed in ISO-8601 by hand: the
    // calendar math below is intentionally simple (no leap rules
    // beyond the standard 4/100/400-year rule) and is sufficient
    // for human-readable audit trail of when the derivation ran.
    format_unix_timestamp_as_iso8601(now)
}

fn format_unix_timestamp_as_iso8601(secs: u64) -> String {
    // Split into days + remainder; convert days to Y-M-D.
    let days = secs / 86_400;
    let rem_secs = secs % 86_400;
    let hh = rem_secs / 3600;
    let mm = (rem_secs % 3600) / 60;
    let ss = rem_secs % 60;
    let (y, m, d) = days_to_ymd(days);
    format!("{y:04}-{m:02}-{d:02}T{hh:02}:{mm:02}:{ss:02}Z")
}

/// Days-since-epoch → (year, month, day). Uses the proleptic Gregorian
/// calendar with the standard century-leap corrections.
fn days_to_ymd(days_since_epoch: u64) -> (u64, u64, u64) {
    let mut year: u64 = 1970;
    let mut remaining = days_since_epoch;
    loop {
        let leap = is_leap(year);
        let len = if leap { 366 } else { 365 };
        if remaining < len {
            break;
        }
        remaining -= len;
        year += 1;
    }
    let leap = is_leap(year);
    let month_lengths = [
        31u64,
        if leap { 29 } else { 28 },
        31,
        30,
        31,
        30,
        31,
        31,
        30,
        31,
        30,
        31,
    ];
    let mut month = 1u64;
    for &len in &month_lengths {
        if remaining < len {
            break;
        }
        remaining -= len;
        month += 1;
    }
    let day = remaining + 1;
    (year, month, day)
}

fn is_leap(y: u64) -> bool {
    (y % 4 == 0 && y % 100 != 0) || y % 400 == 0
}

fn main() -> anyhow::Result<()> {
    let CargoCli::BudgetReport(args) = CargoCli::parse();

    // ── --init: scaffold a template and exit ──────────────────────────
    if args.init {
        scaffold_init(args.force, args.quiet)?;
        return Ok(());
    }

    // ── --derive-limits: read Tier B JSON → write env file, no simulation ──
    // Must run *before* the preflight checks because derivation does
    // not need the `stellar` CLI, network access, or a built WASM.
    // Splitting here keeps the otherwise-expensive setup out of the
    // derivation path entirely.
    if matches!(Mode::from_args(&args), Mode::Derive(..)) {
        let toml_config = load_budget_toml("budget.toml")?;
        run_derive_mode(&args, &toml_config)?;
        return Ok(());
    }

    // ── Preflight environment checks ──────────────────────────────────
    run_preflight_checks(args.quiet)?;

    let toml_config = load_budget_toml("budget.toml")?;
    let default_tolerance = resolve_tolerance(args.tolerance.as_deref(), &toml_config)
        .context("failed to resolve tolerance")?;

    let mode = Mode::from_args(&args);

    let network = args
        .network
        .or(toml_config.network.clone())
        .context("missing --network or budget.toml network field")?;
    let source = args
        .source
        .or(toml_config.source.clone())
        .context("missing --source or budget.toml source field")?;

    if !args.quiet {
        eprintln!("Discovering workspace members...");
    }
    let metadata = MetadataCommand::new()
        .no_deps()
        .exec()
        .context("failed to execute cargo metadata")?;

    let mut reports = Vec::new();
    // `measurements` is the basis for both the legacy table output and the
    // snapshot/baseline modes. The BTreeMap ordering carries through to the
    // baseline file for stable PR diffs.
    let mut measurements: BTreeMap<String, BTreeMap<String, MeasuredResources>> = BTreeMap::new();
    let mut has_errors = false;
    let mut checks_failed = false;
    let mut validation_failed = false;

    let build_profile = args.profile.as_deref().unwrap_or("release");

    for package in metadata.packages {
        let is_cdylib = package
            .targets
            .iter()
            .any(|target| target.crate_types.iter().any(|ct| *ct == "cdylib"));
        if !is_cdylib {
            continue;
        }

        if !args.quiet {
            eprintln!("Building package '{}' for wasm32...", package.name);
        }
        let build_status = Command::new("cargo")
            .args([
                "build",
                "-p",
                &package.name,
                "--target",
                "wasm32-unknown-unknown",
                "--profile",
                build_profile,
            ])
            .status()
            .context("failed to build package")?;

        if !build_status.success() {
            anyhow::bail!("Failed to build {}", package.name);
        }

        // Locate the cdylib target to derive the correct WASM filename.
        // A crate's [lib] name may differ from its package name, so we
        // cannot rely on package.name.replace('-', "_").
        let cdylib_target = package
            .targets
            .iter()
            .find(|t| t.crate_types.iter().any(|ct| *ct == "cdylib"));
        let wasm_name = match cdylib_target {
            Some(target) => target.name.clone(),
            None => {
                eprintln!(
                    "Warning: no cdylib target found for package '{}' — skipping",
                    package.name
                );
                continue;
            }
        };
        let wasm_path = metadata
            .target_directory
            .join("wasm32-unknown-unknown")
            .join(build_profile)
            .join(format!("{}.wasm", wasm_name));

        if !wasm_path.exists() {
            eprintln!(
                "Error: WASM not found at {}\n  Package: {} (lib target: {})\n  The `cargo build` step above should have produced a cdylib WASM at this path.",
                wasm_path.as_str(),
                package.name,
                wasm_name,
            );
            has_errors = true;
            continue;
        }

        // Parse WASM exports
        let wasm_bytes = std::fs::read(&wasm_path)?;
        let wasm_size: u32 = wasm_bytes.len().try_into().unwrap_or(u32::MAX);
        let mut exported_fns: HashSet<String> = HashSet::new();

        for payload in WasmParser::new(0).parse_all(&wasm_bytes) {
            if let wasmparser::Payload::ExportSection(export_section) = payload? {
                for export_item in export_section {
                    let export_item = export_item?;
                    if export_item.kind == wasmparser::ExternalKind::Func {
                        let name = export_item.name.to_string();
                        // Ignore internal and common exports
                        if !name.starts_with('_') && name != "memory" {
                            exported_fns.insert(name);
                        }
                    }
                }

                let contents = fs::read_to_string(&entry_path).with_context(|| {
                    format!("failed to read snapshot {}", entry_path.display())
                })?;
                let snapshot: Snapshot = serde_json::from_str(&contents).with_context(|| {
                    format!("failed to parse snapshot {}", entry_path.display())
                })?;
                snapshots.push(snapshot);
            }
        }

        eprintln!("Contract deployed at: {}", contract_id);

        for function in exported_fns {
            if !args.quiet {
                eprintln!("Simulating function '{}'...", function);
            }

            let func_config = toml_config.functions.get(&function);
            let func_args = func_config.map(|cfg| cfg.args.clone()).unwrap_or_default();

            match simulate_function(&contract_id, &source, &network, &function, &func_args)? {
                SimulationOutcome::Metrics {
                    instructions,
                    read_bytes,
                    write_bytes,
                    transaction_data_xdr,
                } => {
                    // Record the measurement for baseline/snapshot mode. This
                    // was previously only wired up in stale pre-refactor
                    // code; it belongs here in the success arm.
                    let measured = MeasuredResources {
                        instructions: instructions as u64,
                        read_bytes: read_bytes as u64,
                        write_bytes: write_bytes as u64,
                    };
                    measurements
                        .entry(package.name.clone())
                        .or_default()
                        .insert(function.clone(), measured);

                    // Build three CostReport entries for this function. In
                    // --check mode, attach the configured limit and
                    // pass/fail to each entry.
                    for (metric, value) in [
                        ("CPU Instructions", instructions),
                        ("Read Bytes", read_bytes),
                        ("Write Bytes", write_bytes),
                        ("WASM Bytes", wasm_size),
                    ] {
                        let limit = func_config.and_then(|cfg| limit_for_metric(cfg, metric));
                        let (entry_limit, pass) = evaluate_check(value, limit);
                        if pass == Some(false) {
                            checks_failed = true;
                        }
                        reports.push(CostReport {
                            package: package.name.to_string(),
                            function: function.clone(),
                            metric,
                            value: Some(value),
                            limit: entry_limit,
                            pass,
                        });
                    }

                    // ── Optional Stellar CLI validation ──────────────
                    if args.validate {
                        let v_result = validate::validate_metrics(
                            &transaction_data_xdr,
                            instructions,
                            read_bytes,
                            write_bytes,
                        );
                        match v_result {
                            validate::ValidationResult::Match => {
                                if !args.quiet {
                                    eprintln!("  ✓ validation passed for '{}'", function);
                                }
                            }
                            validate::ValidationResult::Mismatch { diagnostics } => {
                                validation_failed = true;
                                eprintln!(
                                    "  ✗ VALIDATION FAILED for '{}' in package '{}':",
                                    function, package.name
                                );
                                for d in &diagnostics {
                                    eprintln!("    {}", d);
                                }
                            }
                            validate::ValidationResult::Skipped { reason } => {
                                if !args.quiet {
                                    eprintln!(
                                        "  - validation skipped for '{}': {}",
                                        function, reason
                                    );
                                }
                            }
                        }
                    }
                }
                SimulationOutcome::Failed(failure) => {
                    has_errors = true;
                    if !args.quiet {
                        match &failure {
                            SimulationFailure::Invoke(stderr) => {
                                eprintln!(
                                    "Warning: Simulation failed for {}: {}",
                                    function, stderr
                                );
                            }
                            SimulationFailure::Rpc(error) => {
                                eprintln!("Warning: RPC error for {}: {}", function, error);
                            }
                            SimulationFailure::MetricsExtraction(err) => {
                                eprintln!(
                                    "Warning: Failed to extract metrics for {}: {}",
                                    function, err
                                );
                            }
                        }
                    }
                    if let (true, Some(function_config)) = (args.check, func_config) {
                        // A configured function that won't simulate cannot
                        // satisfy any of its declared limits; record this as
                        // a check failure even if no `*_limit` is set on
                        // this row of budget.toml.
                        checks_failed = true;
                        emit_check_failure_entries(
                            &mut reports,
                            &package.name,
                            &function,
                            function_config,
                        );
                    }
                }
            }
        }
    }

    if measurements.is_empty() {
        if !args.quiet {
            eprintln!("No successful simulations to report.");
        }
        if has_errors || (args.check && checks_failed) || validation_failed {
            std::process::exit(1);
        }
    }
}

    // Per-function tolerance overrides from `budget.toml` (top-level plus
    // per-function). Built once so Mode::Check (baseline regression) and the
    // regular --check path below use the same input.
    let tolerance_overrides: BTreeMap<String, Tolerance> = toml_config
        .functions
        .iter()
        .filter_map(|(name, fc)| fc.tolerance.map(|t| (name.clone(), Tolerance::new(t))))
        .collect();

    // Re-shape the local `MeasuredResources` map into the `compare::Measurement`
    // shape so the baseline modes (`--record-baseline`, `--check-baseline`)
    // can hand it to `build_baseline` / `check_against_baseline` without a
    // second walk over the per-package data.
    let measurement_map: BTreeMap<String, BTreeMap<String, Measurement>> = measurements
        .iter()
        .map(|(pkg, fns)| {
            (
                pkg.clone(),
                fns.iter()
                    .map(|(name, m)| (name.clone(), m.as_compare()))
                    .collect(),
            )
        })
        .collect();

    match mode {
        Mode::Record(path) => {
            let baseline = build_baseline(&measurement_map);
            baseline
                .save(&path)
                .with_context(|| format!("failed to save baseline to {}", path.display()))?;
            eprintln!("Recorded baseline to {}", path.display());
            return Ok(());
        }
        Mode::Check(path) => {
            let baseline = Baseline::load(&path)
                .with_context(|| format!("failed to load baseline {}", path.display()))?;
            let report = check_against_baseline(
                &baseline,
                &measurement_map,
                default_tolerance,
                &tolerance_overrides,
            );
            if args.json {
                let json = render_check_report_json(&report, default_tolerance);
                println!(
                    "{}",
                    serde_json::to_string_pretty(&json).context("Failed to serialize JSON")?
                );
            } else {
                print!("{}", render_report_text(&report));
            }
            if report.has_regressions() {
                std::process::exit(1);
            }
            return Ok(());
        }
        Mode::Derive(_, _) => unreachable!("derive mode returns early before this point"),
        Mode::Report => {} // Fall through to the legacy rendering below.
    }

    if args.csv {
        let mut csv_writer = csv::Writer::from_writer(std::io::stdout());
        if args.check {
            csv_writer
                .write_record(["package", "function", "metric", "value", "limit", "pass"])
                .context("Failed to write CSV header")?;
            for report in &reports {
                let value_str = report.value.map(|val| val.to_string()).unwrap_or_default();
                let limit_str = report.limit.map(|lim| lim.to_string()).unwrap_or_default();
                let pass_str = report.pass.map(|p| p.to_string()).unwrap_or_default();
                csv_writer
                    .write_record([
                        report.package.as_str(),
                        report.function.as_str(),
                        report.metric,
                        value_str.as_str(),
                        limit_str.as_str(),
                        pass_str.as_str(),
                    ])
                    .context("Failed to write CSV record")?;
            }
        } else {
            csv_writer
                .write_record(["package", "function", "metric", "value"])
                .context("Failed to write CSV header")?;
            for report in &reports {
                if report.value.is_some() {
                    let value_str = report.value.map(|val| val.to_string()).unwrap_or_default();
                    csv_writer
                        .write_record([
                            report.package.as_str(),
                            report.function.as_str(),
                            report.metric,
                            value_str.as_str(),
                        ])
                        .context("Failed to write CSV record")?;
                }
            }
        }
        csv_writer.flush().context("Failed to flush CSV writer")?;
    } else if args.json {
        let json_output =
            serde_json::to_string_pretty(&reports).context("Failed to serialize report to JSON")?;
        println!("{}", json_output);
    } else {
        // The plain text report path is preserved byte-for-byte when
        // `--check` is not passed: only entries with a measured value are
        // rendered in the table, and summary text is unchanged.
        println!("\n=== WORKSPACE BUDGET REPORT ===");
        let table_reports: Vec<TableCostReport> = reports
            .iter()
            .filter(|report| report.value.is_some())
            .map(|report| {
                let value = report.value.unwrap_or(0);
                let formatted = format_with_commas_and_units(u64::from(value), report.metric);
                TableCostReport {
                    package: report.package.clone(),
                    function: report.function.clone(),
                    metric: report.metric,
                    value: formatted,
                }
            })
            .collect();
        let table = Table::new(table_reports).to_string();
        println!("{}", table);
        println!("\nSummary: The values above are simulated resource amounts, not fees. They are three of the inputs to the non-refundable resource fee.");
        println!("* Not measured: transaction size, ledger footprint entry counts, refundable fees (rent, events, return value), the inclusion fee, and therefore the total fee charged.");
        println!("* Note: These are simulated numbers on testnet and may vary slightly depending on ledger state.");
        println!("* See the \"Measurement scope\" section of the Tool Reference for what to use instead when you need those figures.");

        // Fixed: was `if check` — `check` is not in scope here, this needs
        // to read the CLI flag `args.check`.
        if args.check {
            println!("\n=== BUDGET CHECKS ===");
            let mut passed: usize = 0;
            let mut failed: usize = 0;
            for report in &reports {
                let Some(pass) = report.pass else {
                    continue;
                };
                let status = if pass { "PASS" } else { "FAIL" };
                let value_str = match report.value {
                    Some(v) => format_with_commas_and_units(u64::from(v), report.metric),
                    None => "<simulation failed>".to_string(),
                };
                let limit_str = report
                    .limit
                    .map(|limit_val| {
                        // Limits wider than u32::MAX are not representable in
                        // the table's units, but anything close to the
                        // practical ceiling formats fine.
                        let display_value = u32::try_from(limit_val).unwrap_or(u32::MAX);
                        format_with_commas_and_units(u64::from(display_value), report.metric)
                    })
                    .unwrap_or_else(|| "-".to_string());
                println!(
                    "{}::{} [{}] value={} limit={} {}",
                    report.package, report.function, report.metric, value_str, limit_str, status
                );
                if pass {
                    passed += 1;
                } else {
                    failed += 1;
                }
            }
            println!("Summary: {} check(s) passed, {} failed", passed, failed);
        }
    }
    // PR #195: `--check` exits non-zero when any limit was breached so CI can
    // gate on the result. Mirrors the empty-measurements branch above.
    if (args.check && checks_failed) || validation_failed {
        std::process::exit(1);
    }
    Ok(())
}

mod module_4;
pub mod validate;

#[derive(Debug, Clone, PartialEq, Eq)]
enum Mode {
    Report,
    Record(PathBuf),
    Check(PathBuf),
    /// Tier A limit derivation. The path is the destination env file.
    /// The optional secondary path, when present, is the destination
    /// for the Markdown provenance sidecar (or `None` to derive the
    /// default `<OUT>.provenance.md` next to it).
    Derive(PathBuf, Option<PathBuf>),
}

impl Mode {
    fn from_args(args: &BudgetReportArgs) -> Self {
        if let Some(out) = &args.derive_limits {
            let provenance = args.provenance_out.as_deref().map(PathBuf::from);
            return Mode::Derive(PathBuf::from(out), provenance);
        }
        if let Some(p) = &args.record_baseline {
            Mode::Record(PathBuf::from(p))
        } else if let Some(p) = &args.check_baseline {
            Mode::Check(PathBuf::from(p))
        } else {
            Mode::Report
        }
    }
}

#[cfg(test)]
mod module_8;

#[cfg(test)]
mod module_18;

/// Serializes tests that mutate the process working directory.
#[cfg(test)]
static TEST_CWD_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};
    use stellar_xdr::curr::WriteXdr;

    const SHARED_BUDGET_TOML: &str = include_str!("../fixtures/shared_budget.toml");

    fn unique_test_path() -> PathBuf {
        let mut path = std::env::temp_dir();
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time is before UNIX_EPOCH")
            .as_nanos();
        path.push(format!("cargo_budget_report_test_{}.toml", nanos));
        path
    }

    // --- Network simulation loop helper tests ---

    #[test]
    fn build_invoke_args_without_function_args() {
        let invoke_args = build_invoke_args("CCONTRACT", "alice", "testnet", "do_work", &[]);
        assert_eq!(
            invoke_args,
            vec![
                "contract",
                "invoke",
                "--id",
                "CCONTRACT",
                "--source",
                "alice",
                "--network",
                "testnet",
                "--build-only",
                "--",
                "do_work",
            ]
        );
    }

    #[test]
    fn build_invoke_args_appends_function_args_after_separator() {
        let func_args = vec!["--n".to_string(), "10000".to_string()];
        let invoke_args = build_invoke_args("CCONTRACT", "alice", "testnet", "do_work", &func_args);
        assert_eq!(
            invoke_args,
            vec![
                "contract",
                "invoke",
                "--id",
                "CCONTRACT",
                "--source",
                "alice",
                "--network",
                "testnet",
                "--build-only",
                "--",
                "do_work",
                "--n",
                "10000",
            ]
        );
    }

    #[test]
    fn build_rpc_payload_wraps_xdr_in_simulate_transaction_request() {
        let payload = build_rpc_payload("AAAAAgAAAAA=");
        assert_eq!(payload["jsonrpc"], "2.0");
        assert_eq!(payload["method"], "simulateTransaction");
        assert_eq!(payload["params"]["transaction"], "AAAAAgAAAAA=");
    }

    #[test]
    fn build_rpc_payload_empty_xdr_is_still_well_formed() {
        let payload = build_rpc_payload("");
        assert_eq!(payload["params"]["transaction"], "");
    }

    // --- Metric extraction tests ---

    const FIXTURE_INSTRUCTIONS: u32 = 1_000_000;
    const FIXTURE_READ_BYTES: u32 = 2_048;
    const FIXTURE_WRITE_BYTES: u32 = 4_096;
    const FIXTURE_RESOURCE_FEE: i64 = 0;

    fn make_fixture_tx_data() -> SorobanTransactionData {
        use stellar_xdr::curr::{ExtensionPoint, LedgerFootprint, VecM};
        SorobanTransactionData {
            ext: ExtensionPoint::V0,
            resources: stellar_xdr::curr::SorobanResources {
                footprint: LedgerFootprint {
                    read_only: VecM::default(),
                    read_write: VecM::default(),
                },
                instructions: FIXTURE_INSTRUCTIONS,
                read_bytes: FIXTURE_READ_BYTES,
                write_bytes: FIXTURE_WRITE_BYTES,
            },
            resource_fee: FIXTURE_RESOURCE_FEE,
        }
    }

    fn fixture_rpc_response_json() -> serde_json::Value {
        let tx_data = make_fixture_tx_data();
        let b64 = tx_data
            .to_xdr_base64(Limits::none())
            .expect("failed to encode fixture SorobanTransactionData");
        serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "result": {
                "transactionData": b64
            }
        })
    }

    #[test]
    fn extract_metrics_from_programmatic_rpc_response() {
        let rpc_json = fixture_rpc_response_json();
        let (instructions, read_bytes, write_bytes) =
            extract_metrics(&rpc_json).expect("extraction should succeed");
        assert_eq!(instructions, FIXTURE_INSTRUCTIONS);
        assert_eq!(read_bytes, FIXTURE_READ_BYTES);
        assert_eq!(write_bytes, FIXTURE_WRITE_BYTES);
    }

    #[test]
    fn extract_metrics_from_fixture_file() {
        let fixture_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("fixtures")
            .join("simulate_transaction_response_valid.json");
        let fixture_json: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(&fixture_path).expect("failed to read fixture file"),
        )
        .expect("failed to parse fixture JSON");

        let meta = &fixture_json["_metadata"];
        assert_eq!(meta["network"].as_str(), Some("testnet"));
        assert!(meta["protocol_version"].as_u64().is_some());

        let (instructions, read_bytes, write_bytes) =
            extract_metrics(&fixture_json).expect("extraction from fixture should succeed");
        assert_eq!(instructions, FIXTURE_INSTRUCTIONS);
        assert_eq!(read_bytes, FIXTURE_READ_BYTES);
        assert_eq!(write_bytes, FIXTURE_WRITE_BYTES);
    }

    #[test]
    fn extract_metrics_fails_on_rpc_error() {
        let rpc_json = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "error": {
                "code": -32600,
                "message": "Invalid Request"
            }
        });
        let result = extract_metrics(&rpc_json);
        assert!(result.is_err());
        let err = format!("{:#}", result.as_ref().unwrap_err());
        assert!(
            err.contains("Invalid Request"),
            "error should mention the RPC error message, got: {}",
            err
        );
    }

    #[test]
    fn extract_metrics_fails_on_missing_transaction_data() {
        let rpc_json = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "result": {
                "some_other_field": "no transaction data here"
            }
        });
        let result = extract_metrics(&rpc_json);
        assert!(result.is_err());
        let err = format!("{:#}", result.unwrap_err());
        assert!(
            err.contains("transactionData"),
            "error should mention transactionData, got: {}",
            err
        );
    }

    #[test]
    fn extract_metrics_fails_on_invalid_xdr() {
        let rpc_json = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "result": {
                "transactionData": "this-is-not-valid-base64-xdr!!!"
            }
        });
        let result = extract_metrics(&rpc_json);
        assert!(result.is_err(), "extraction should fail on invalid XDR");
    }

    #[test]
    fn extract_metrics_from_malformed_fixture_file() {
        let fixture_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("fixtures")
            .join("simulate_transaction_response_malformed.json");
        let fixture_json: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(&fixture_path).expect("failed to read malformed fixture file"),
        )
        .expect("failed to parse malformed JSON");

        let result = extract_metrics(&fixture_json);
        assert!(
            result.is_err(),
            "extraction should fail on malformed response"
        );
        let err = format!("{:#}", result.unwrap_err());
        assert!(
            err.contains("No transaction data available"),
            "Expected specific error message"
        );
    }

    #[test]
    fn extract_metrics_from_cpu_exceeded_fixture_file() {
        let fixture_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("fixtures")
            .join("simulate_transaction_response_cpu_exceeded.json");
        let fixture_json: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(&fixture_path)
                .expect("failed to read cpu exceeded fixture file"),
        )
        .expect("failed to parse cpu exceeded JSON");

        let result = extract_metrics(&fixture_json);
        assert!(
            result.is_err(),
            "extraction should fail on cpu exceeded response"
        );
        let err = format!("{:#}", result.unwrap_err());
        assert!(
            err.contains("CPU budget exceeded"),
            "Expected error to mention CPU budget exceeded, got: {}",
            err
        );
    }

    #[test]
    fn extract_metrics_fails_on_non_string_transaction_data() {
        let rpc_json = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "result": {
                "transactionData": 12345
            }
        });
        let result = extract_metrics(&rpc_json);
        assert!(
            result.is_err(),
            "extraction should fail when transactionData is not a string"
        );
    }

    // --- Budget toml loading tests ---

    #[test]
    fn missing_budget_toml_returns_default() {
        let path = unique_test_path();
        let _ = fs::remove_file(&path);

        let config = load_budget_toml(&path).expect("missing file should return default");
        assert!(config.network.is_none());
        assert!(config.source.is_none());
        assert!(config.functions.is_empty());
        assert!(config.tolerance.is_none());
    }

    #[test]
    fn empty_budget_toml_returns_default() {
        let path = unique_test_path();
        fs::write(&path, "\n\n").expect("failed to write empty budget.toml");

        let config = load_budget_toml(&path).expect("empty file should return default");
        assert!(config.network.is_none());
        assert!(config.source.is_none());
        assert!(config.functions.is_empty());
    }

    #[test]
    fn malformed_budget_toml_errors_with_parse_message() {
        let path = unique_test_path();
        fs::write(
            &path,
            "network = \"testnet\"\n[functions.do_expensive_work]\nargs = \"--n 10\"\n",
        )
        .expect("failed to write malformed budget.toml");

        let err = load_budget_toml(&path).unwrap_err();
        let err_text = err.to_string();

        assert!(
            err_text.contains("TOML error"),
            "expected TOML error in message, got: {}",
            err_text
        );
        assert!(err_text.contains("line") || err_text.contains("Line"));
        assert!(err_text.contains("column") || err_text.contains("Column"));
    }

    #[test]
    fn budget_toml_parses_global_and_per_function_tolerance() {
        let path = unique_test_path();
        fs::write(
            &path,
            "network = \"testnet\"\ntolerance = 0.10\n\
             [functions.do_expensive_work]\nargs = [\"--n\", \"10\"]\ntolerance = 0.05\n",
        )
        .expect("failed to write budget.toml");
        let config = load_budget_toml(&path).expect("parse should succeed");
        assert_eq!(config.tolerance, Some(0.10));
        let func = config
            .functions
            .get("do_expensive_work")
            .expect("function present");
        assert_eq!(func.tolerance, Some(0.05));
    }

    // --- Tolerance resolution ----------------------------------------------

    #[test]
    fn resolve_tolerance_precedence_cli_over_toml_over_default() {
        let config = BudgetToml {
            tolerance: Some(0.25),
            ..Default::default()
        };
        let t = resolve_tolerance(Some("0.42"), &config).expect("cli should win");
        assert!((t.value - 0.42).abs() < f64::EPSILON);

        let t = resolve_tolerance(None, &config).expect("toml should win");
        assert!((t.value - 0.25).abs() < f64::EPSILON);

        let empty = BudgetToml::default();
        let t = resolve_tolerance(None, &empty).expect("default should win");
        assert!((t.value - 0.10).abs() < f64::EPSILON);
    }

    #[test]
    fn resolve_tolerance_rejects_invalid_cli() {
        let config = BudgetToml::default();
        let err = resolve_tolerance(Some("nope"), &config)
            .unwrap_err()
            .to_string();
        assert!(err.contains("tolerance must be a number"), "got: {err}");
    }

    // --- Mode dispatch ------------------------------------------------------

    #[test]
    fn mode_defaults_to_report_when_no_flags() {
        let args = BudgetReportArgs {
            init: false,
            force: false,
            network: None,
            source: None,
            json: false,
            check: false,
            csv: false,
            record_baseline: None,
            check_baseline: None,
            tolerance: None,
            quiet: false,
            validate: false,
            profile: None,
            derive_limits: None,
            from: None,
            margin_cpu: None,
            margin_memory: None,
            margin_read: None,
            margin_write: None,
            provenance_out: None,
        };
        assert_eq!(Mode::from_args(&args), Mode::Report);
    }

    #[test]
    fn mode_distinguishes_record_and_check() {
        let record = BudgetReportArgs {
            init: false,
            force: false,
            network: None,
            source: None,
            json: false,
            check: false,
            csv: false,
            record_baseline: Some("budget-baseline.toml".to_string()),
            check_baseline: None,
            tolerance: None,
            quiet: false,
            validate: false,
            profile: None,
            derive_limits: None,
            from: None,
            margin_cpu: None,
            margin_memory: None,
            margin_read: None,
            margin_write: None,
            provenance_out: None,
        };
        assert_eq!(
            Mode::from_args(&record),
            Mode::Record(PathBuf::from("budget-baseline.toml"))
        );

        let check = BudgetReportArgs {
            init: false,
            force: false,
            network: None,
            source: None,
            json: false,
            check: false,
            csv: false,
            record_baseline: None,
            check_baseline: Some("custom.toml".to_string()),
            tolerance: None,
            quiet: false,
            validate: false,
            profile: None,
            derive_limits: None,
            from: None,
            margin_cpu: None,
            margin_memory: None,
            margin_read: None,
            margin_write: None,
            provenance_out: None,
        };
        assert_eq!(
            Mode::from_args(&check),
            Mode::Check(PathBuf::from("custom.toml"))
        );
    }

    #[test]
    fn mode_detects_derive() {
        let args = BudgetReportArgs {
            init: false,
            force: false,
            network: None,
            source: None,
            json: false,
            check: false,
            csv: false,
            record_baseline: None,
            check_baseline: None,
            tolerance: None,
            quiet: false,
            validate: false,
            profile: None,
            derive_limits: Some("tier-a-limits.env".to_string()),
            from: None,
            margin_cpu: None,
            margin_memory: None,
            margin_read: None,
            margin_write: None,
            provenance_out: None,
        };
        match Mode::from_args(&args) {
            Mode::Derive(out, _) => assert_eq!(out, PathBuf::from("tier-a-limits.env")),
            other => panic!("expected Derive mode, got {other:?}"),
        }
    }

    #[test]
    fn shared_budget_toml_parses_with_foreign_sections() {
        let config: BudgetToml = toml::from_str(SHARED_BUDGET_TOML)
            .expect("shared budget.toml with foreign [lints] section should parse");
        assert_eq!(config.network.as_deref(), Some("testnet"));
        assert_eq!(config.source.as_deref(), Some("alice"));
        assert!(config.functions.contains_key("do_expensive_work"));
        assert!(config.functions.contains_key("require_auth_only"));
    }

    #[test]
    fn unknown_function_keys_produce_error() {
        let err =
            toml::from_str::<BudgetToml>("[functions.do_expensive_work]\ncpu_lmit = 5000000\n")
                .unwrap_err();
        let err_text = err.to_string();
        assert!(
            err_text.contains("unknown field") || err_text.contains("cpu_lmit"),
            "expected error mentioning unknown field or the offending key, got: {err_text}"
        );
    }

    #[test]
    fn known_function_key_spelling_produces_correct_deserialization() {
        let config: BudgetToml = toml::from_str(
            r#"
[functions.do_expensive_work]
cpu_limit = 5000000
read_limit = 5000
write_limit = 1000
"#,
        )
        .expect("valid function config should parse");
        let func = &config.functions["do_expensive_work"];
        assert_eq!(func.cpu_limit, Some(5000000));
        assert_eq!(func.read_limit, Some(5000));
        assert_eq!(func.write_limit, Some(1000));
    }

    // --- TransactionData deserialization tests ---

    #[test]
    fn transaction_data_parsing_deserializes_successfully() {
        let json_str = r#"{"resources": {"instructions": 1000, "disk_read_bytes": 2048, "write_bytes": 3072}}"#;
        let tx_data = TransactionData::parse_json(json_str).expect("Parsing should succeed");
        assert_eq!(tx_data.resources.instructions, 1000);
        assert_eq!(tx_data.resources.disk_read_bytes, 2048);
        assert_eq!(tx_data.resources.write_bytes, 3072);
    }

    #[test]
    fn transaction_data_parsing_fails_on_missing_field() {
        let json_str = r#"{"resources": {"instructions": 1000, "disk_read_bytes": 2048}}"#;
        let result = TransactionData::parse_json(json_str);
        assert!(result.is_err(), "Parsing should fail on missing field");
        let err_msg = format!("{:#}", result.unwrap_err());
        assert!(
            err_msg.contains("write_bytes"),
            "Error should mention missing field, got: {}",
            err_msg
        );
    }

    #[test]
    fn transaction_data_parsing_fails_on_non_numeric_field() {
        let json_str = r#"{"resources": {"instructions": "not-a-number", "disk_read_bytes": 2048, "write_bytes": 3072}}"#;
        let result = TransactionData::parse_json(json_str);
        assert!(result.is_err(), "Parsing should fail on non-numeric field");
        let err_msg = format!("{:#}", result.unwrap_err());
        assert!(
            err_msg.contains("invalid type") || err_msg.contains("not-a-number"),
            "Error should mention type mismatch, got: {}",
            err_msg
        );
    }

    // --- Cost value formatter tests ---

    #[test]
    fn json_output_has_the_versioned_report_schema() {
        let report = BudgetReport {
            schema_version: 1,
            snapshots: vec![Snapshot {
                name: "transfer".to_owned(),
                cpu: 123,
                memory: 456,
            }],
        };

        let value: serde_json::Value =
            serde_json::from_str(&report.render(OutputFormat::Json).unwrap()).unwrap();

        assert_eq!(value["schema_version"], 1);
        assert_eq!(value["snapshots"][0]["name"], "transfer");
        assert_eq!(value["snapshots"][0]["cpu"], 123);
        assert_eq!(value["snapshots"][0]["memory"], 456);
        assert_eq!(
            value.as_object().unwrap().keys().collect::<Vec<_>>(),
            vec!["schema_version", "snapshots"]
        );
    }

    #[test]
    fn json_is_selected_by_the_format_flag() {
        let cli = Cli::try_parse_from(["cargo-budget-report", "--format", "json"]).unwrap();
        assert_eq!(cli.format, OutputFormat::Json);
    }
}
