use crate::module_10::{Error, Result as Module10Result, SimulationFailure, SimulationOutcome};
mod compare;

use anyhow::{Context, Result};
use cargo_metadata::MetadataCommand;
use clap::Parser;
use compare::{
    build_baseline, check_against_baseline, max_allowed as max_allowed_metric, parse_tolerance,
    render_report_text, Baseline, Measurement, Tolerance,
};
use indicatif::{ProgressBar, ProgressStyle};
use serde::Serialize;
use std::collections::{BTreeMap, HashMap, HashSet};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::thread;
use std::time::Duration;
use stellar_xdr::curr::{Limits, ReadXdr, SorobanTransactionData};
use tabled::{Table, Tabled};
use wasmparser::Parser as WasmParser;

mod module_10;

/// Maximum number of total deployment attempts (1 initial + 3 retries)
/// when friendbot funding is suspected to have failed transiently
/// (rate-limiting, network hiccups, or the account not being fully
/// confirmed on-ledger yet).
const MAX_DEPLOY_ATTEMPTS: u32 = 4;

/// Initial backoff delay between deployment retries. Doubles on each
/// subsequent attempt (2 s → 4 s → 8 s).
const INITIAL_RETRY_DELAY_SECS: u64 = 2;

/// Commented budget.toml template written by `cargo budget-report --init`.
const BUDGET_TOML_TEMPLATE: &str = r#"# -- Budget report configuration ---------------------------------------------
# Generated by `cargo budget-report --init`.
# See https://github.com/Tollcraft/soroban-budget-assert for the full reference.

# Target network for contract simulation.
# Supported values: "testnet", "futurenet", "local" (for a local container),
# or any custom network defined in your Stellar CLI config.
network = "testnet"

# Stellar source account keypair name (as configured in your Stellar CLI).
source = "alice"

# -- Per-function configuration ----------------------------------------------
# Declare one section per contract function you want to simulate and
# optionally enforce limits against.
#
#   [functions.<function_name>]
#   args = ["--arg1", "value1"]   # CLI arguments forwarded to the function
#   cpu_limit  = 5000000          # optional, inclusive CPU instruction limit
#   read_limit = 5000             # optional, inclusive read-bytes limit
#   write_limit = 1000            # optional, inclusive write-bytes limit
#
# A missing `*_limit` field means that metric is reported but not enforced.
# See `cargo budget-report --check` for limit enforcement.
# Unknown keys inside a [functions.*] block produce an error.
#
# Foreign top-level sections (e.g. [lints] for soroban-cost-linter) are
# silently accepted so that both tools can share a single budget.toml.

[functions.do_expensive_work]
args = ["--n", "10000"]
cpu_limit = 5000000
read_limit = 5000
write_limit = 1000
"#;

/// Top-level CLI entry point for `cargo budget-report`.
///
/// Wraps the binary in a `cargo <subcommand>` compatible enum so it can be
/// invoked as `cargo budget-report [OPTIONS]`.
#[derive(Parser, Debug)]
#[command(name = "cargo", bin_name = "cargo")]
enum CargoCli {
    BudgetReport(BudgetReportArgs),
}

/// CLI arguments for `cargo budget-report`.
///
/// All fields are optional; missing values fall back to the corresponding
/// `budget.toml` configuration when available.
#[derive(Parser, Debug, Default)]
struct BudgetReportArgs {
    /// Scaffold a commented `budget.toml` template and exit.
    #[arg(long)]
    init: bool,

    /// Allow `--init` to overwrite an existing `budget.toml`.
    #[arg(long)]
    force: bool,

    #[arg(long)]
    network: Option<String>,

    #[arg(long)]
    source: Option<String>,

    #[arg(long, default_value_t = false)]
    json: bool,

    /// Enforce per-function limits declared in `budget.toml`.
    ///
    /// When set, each measured metric is compared against its configured
    /// `cpu_limit` / `read_limit` / `write_limit`. A missing limit means the
    /// metric is reported but **not** enforced. The process exits with a
    /// non-zero status when any limit is breached, or when a function that
    /// has a `budget.toml` entry fails to simulate. Functions that are not
    /// declared in `budget.toml` are reported only.
    #[arg(long, default_value_t = false)]
    check: bool,

    /// Emit the report as CSV instead of a table or JSON.
    #[arg(long, default_value_t = false)]
    csv: bool,

    /// Write a new resource-usage baseline snapshot to this path and exit.
    #[arg(long)]
    record_baseline: Option<String>,

    /// Check current measurements against an existing baseline snapshot at
    /// this path, applying the configured regression tolerance.
    #[arg(long)]
    check_baseline: Option<String>,

    /// Override the regression tolerance (e.g. "0.10" for 10%). Takes
    /// precedence over `tolerance` in `budget.toml`.
    #[arg(long)]
    tolerance: Option<String>,

    /// Suppress non-essential progress messages and warnings on stderr.
    ///
    /// The final report (table, JSON, or CSV) is still printed to stdout.
    /// Fatal errors from child-process spawn failures or hard contract
    /// build failures are not suppressed — they always go to stderr
    /// regardless of this flag.
    #[arg(long, default_value_t = false)]
    quiet: bool,

    /// Cargo build profile to use when compiling the contract WASM.
    ///
    /// Defaults to `release` when not provided. Custom profiles (e.g.
    /// `release-opt`) must be defined in the project's `Cargo.toml`.
    #[arg(long)]
    profile: Option<String>,

    /// Highlight functions whose any metric exceeds this share (0-100)
    /// of the corresponding network resource limit. A value of 0 disables
    /// highlighting.
    ///
    /// The network limits are fetched from the Soroban RPC endpoint in
    /// real time, so they reflect the current protocol's actual ceiling.
    #[arg(long, default_value_t = 0.0)]
    share_threshold: f64,
}

/// Top-level configuration deserialized from `budget.toml`.
///
/// Contains optional network and source-account overrides, plus a map of
/// per-function budget configurations keyed by exported function name.
#[derive(serde::Deserialize, Default, Debug)]
struct BudgetToml {
    network: Option<String>,
    source: Option<String>,
    /// Global default tolerance, used unless overridden per function or by `--tolerance`.
    #[serde(default)]
    tolerance: Option<f64>,
    #[serde(default)]
    functions: HashMap<String, FunctionConfig>,
}

/// Raw resource metrics returned by the Soroban `simulateTransaction` RPC.
///
/// Maps directly to the `resources` field of a `SorobanTransactionData` XDR
/// object decoded from the RPC response.
#[allow(dead_code)]
#[derive(serde::Deserialize, Debug)]
struct Resources {
    instructions: u64,
    disk_read_bytes: u64,
    write_bytes: u64,
}

/// Top-level wrapper for the deserialized `simulateTransaction` response.
///
/// Currently only carries the `resources` sub-object, but exists as a
/// named type so that additional RPC response fields can be added without
/// changing the extraction call-site.
#[allow(dead_code)]
#[derive(serde::Deserialize, Debug)]
struct TransactionData {
    #[serde(alias = "resources")]
    resources: Resources,
}

impl TransactionData {
    #[cfg(test)]
    fn parse_json(json_str: &str) -> anyhow::Result<Self> {
        let parsed_json: serde_json::Value =
            serde_json::from_str(json_str).context("Failed to parse JSON")?;
        serde_json::from_value(parsed_json).context("Failed to deserialize transaction data")
    }
}

/// Network resource limits as reported by the Soroban JSON-RPC
/// `getNetworkLimits` method.
///
/// These values define the per-transaction ceiling that Soroban
/// enforces on the current protocol. They change with protocol
/// upgrades, so they are fetched from the network at report time
/// rather than hardcoded (see the fallback block below for the
/// documented hardcoded defaults).
#[derive(Debug, Clone)]
struct NetworkLimits {
    max_instructions: u64,
    max_read_bytes: u64,
    max_write_bytes: u64,
}

/// Maps a Soroban network name or alias to its JSON-RPC endpoint URL.
///
/// Known networks return their canonical Soroban RPC URL. For any
/// other name (including custom networks), this function returns
/// `None`, leaving the caller to fall back gracefully.
fn soroban_rpc_url(network: &str) -> Option<&'static str> {
    match network {
        "testnet" => Some("https://soroban-testnet.stellar.org:443"),
        "futurenet" => Some("https://soroban-futurenet.stellar.org:443"),
        "pubnet" => Some("https://soroban-public.stellar.org:443"),
        "local" => Some("http://localhost:8000"),
        _ => None,
    }
}

/// Fetches the current network resource limits via the Soroban
/// JSON-RPC `getNetworkLimits` method.
///
/// Returns an error if the RPC call fails or the response cannot be
/// parsed, so callers can fall back to documented hardcoded defaults.
fn fetch_network_limits(rpc_url: &str) -> anyhow::Result<NetworkLimits> {
    let payload = serde_json::json!({
        "jsonrpc": "2.0",
        "id": 1,
        "method": "getNetworkLimits",
        "params": {}
    });

    let mut curl = Command::new("curl")
        .args([
            "-s",
            "-X",
            "POST",
            "-H",
            "Content-Type: application/json",
            "-d",
            "@-",
            rpc_url,
        ])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .context("failed to execute curl for getNetworkLimits")?;

    {
        let stdin = curl.stdin.as_mut().context("Failed to open stdin for getNetworkLimits")?;
        stdin
            .write_all(payload.to_string().as_bytes())
            .context("Failed to write getNetworkLimits payload to stdin")?;
    }

    let output = curl
        .wait_with_output()
        .context("Failed to read getNetworkLimits output")?;

    let json: serde_json::Value = serde_json::from_slice(&output.stdout)
        .context("Failed to parse getNetworkLimits response")?;

    let result = json.get("result").ok_or_else(|| {
        anyhow::anyhow!("getNetworkLimits response missing 'result' field")
    })?;

    Ok(NetworkLimits {
        max_instructions: result
            .get("maxInstructions")
            .and_then(|v| v.as_u64())
            .context("getNetworkLimits missing maxInstructions")?,
        max_read_bytes: result
            .get("maxReadBytes")
            .and_then(|v| v.as_u64())
            .context("getNetworkLimits missing maxReadBytes")?,
        max_write_bytes: result
            .get("maxWriteBytes")
            .and_then(|v| v.as_u64())
            .context("getNetworkLimits missing maxWriteBytes")?,
    })
}

/// Hardcoded network resource limits as a fallback when the live
/// RPC call cannot be reached (e.g. `--network local` or offline
/// environments).
///
/// These values correspond to **Soroban Protocol version 21**
/// (the current protocol on testnet as of late 2024). They MUST be
/// reviewed and updated when the protocol is upgraded.
const FALLBACK_NETWORK_LIMITS: NetworkLimits = NetworkLimits {
    max_instructions: 10_000_000,
    max_read_bytes: 100_000,
    max_write_bytes: 100_000,
};

/// Fetches network resource limits, falling back to documented
/// protocol-versioned hardcoded defaults when the RPC is unreachable.
///
/// The fallback is clearly tied to Soroban Protocol v21 so that
/// consumers know when it may be stale.
fn get_network_limits(network: &str) -> NetworkLimits {
    let rpc_url = soroban_rpc_url(network);
    match rpc_url {
        Some(url) => fetch_network_limits(url).unwrap_or_else(|e| {
            eprintln!(
                "Warning: could not fetch network limits from {}: {} — \
                 using documented fallback limits (Soroban Protocol v21)",
                url, e
            );
            FALLBACK_NETWORK_LIMITS.clone()
        }),
        None => {
            eprintln!(
                "Warning: unknown network `{}` for Soroban RPC — \
                 using documented fallback limits (Soroban Protocol v21)",
                network
            );
            FALLBACK_NETWORK_LIMITS.clone()
        }
    }
}

/// Per-function configuration read from a `[functions.<name>]` section of
/// `budget.toml`.
///
/// Controls which CLI arguments are forwarded to the contract invocation
/// and which resource limits are enforced in `--check` mode.
#[derive(serde::Deserialize, Default, Debug)]
#[serde(deny_unknown_fields)]
struct FunctionConfig {
    #[serde(default)]
    args: Vec<String>,
    /// Inclusive upper bound on the measured CPU `Instructions` metric. `None`
    /// means this metric is reported but not enforced by `--check`.
    #[serde(default)]
    cpu_limit: Option<u64>,
    #[serde(default)]
    read_limit: Option<u64>,
    #[serde(default)]
    write_limit: Option<u64>,
    /// Optional per-function override for the regression tolerance.
    #[serde(default)]
    tolerance: Option<f64>,
}

#[derive(Clone, Copy)]
struct MeasuredResources {
    instructions: u64,
    read_bytes: u64,
    write_bytes: u64,
}

impl MeasuredResources {
    fn as_compare(self) -> Measurement {
        Measurement {
            cpu_instructions: self.instructions,
            read_bytes: self.read_bytes,
            write_bytes: self.write_bytes,
        }
    }
}

/// A single row in the budget report, representing one metric for one
/// exported function of one workspace package.
///
/// In `--check` mode the `limit` and `pass` fields are populated so that
/// consumers (table, JSON, CSV) can render per-metric pass/fail status.
#[derive(Serialize, Default)]
struct CostReport {
    package: String,
    function: String,
    metric: &'static str,
    /// The measured value, or `None` if the simulation failed to produce one
    /// (only emitted in `--check` mode for functions declared in
    /// `budget.toml`).
    #[serde(skip_serializing_if = "Option::is_none")]
    value: Option<u32>,
    /// Configured upper bound for the metric, if any. Emitted in `--check`
    /// mode only.
    #[serde(skip_serializing_if = "Option::is_none")]
    limit: Option<u64>,
    /// `true` if the measured value is within the configured limit, `false`
    /// if it exceeds the limit **or** the simulation failed for a configured
    /// function. Emitted in `--check` mode only.
    #[serde(skip_serializing_if = "Option::is_none")]
    pass: Option<bool>,
    /// The network resource limit (instructions, read bytes, or write bytes)
    /// that this metric's value is measured against. `None` for metrics
    /// that have no corresponding network limit (e.g. `WASM Bytes`).
    #[serde(skip_serializing_if = "Option::is_none")]
    resource_limit: Option<u64>,
    /// The measured value as a percentage of the corresponding network
    /// resource limit (0-100). `None` when no network limit is available.
    #[serde(skip_serializing_if = "Option::is_none")]
    share_pct: Option<f64>,
}

/// A `CostReport` formatted for rendering in the plain-text [`Table`] output.
///
/// Only rows with a measured value (`value.is_some()`) are included in the
/// table; simulation failures and `--check`-only stubs are filtered out
/// before this type is constructed.
#[derive(Tabled)]
struct TableCostReport {
    package: String,
    function: String,
    metric: &'static str,
    value: String,
}

/// Returns the configured limit (if any) for the given metric name.
fn limit_for_metric(func_config: &FunctionConfig, metric: &str) -> Option<u64> {
    match metric {
        "CPU Instructions" => func_config.cpu_limit,
        "Read Bytes" => func_config.read_limit,
        "Write Bytes" => func_config.write_limit,
        _ => None,
    }
}

/// Given a measured value and an optional configured limit, returns the
/// `(limit, pass)` pair that should be attached to a `CostReport`.
///
/// * No limit configured → `(None, None)`; the metric is reported but not
///   enforced.
/// * Limit configured and value is within it → `(Some(limit), Some(true))`.
/// * Limit configured and value exceeds it → `(Some(limit), Some(false))`;
///   the caller should mark the check as failed.
fn evaluate_check(value: u32, limit: Option<u64>) -> (Option<u64>, Option<bool>) {
    match limit {
        Some(limit_value) => (Some(limit_value), Some(u64::from(value) <= limit_value)),
        None => (None, None),
    }
}

/// Emit one stub `CostReport` per metric (`CPU Instructions`, `Read Bytes`,
/// `Write Bytes`) so that the `--check` JSON output and check summary make
/// the failure visible per metric.
///
/// * Metrics with a configured `*_limit` get `value: None, limit: Some(n),
///   pass: Some(false)` — the consumer can read the breached limit.
/// * Metrics without a configured limit get `value: None, limit: None,
///   pass: Some(false)` — still a hook for `--check --json` consumers, but
///   the table filter (`value.is_some()`) keeps it out of the plain-text
///   report and the summary lines remain unchanged.
///
/// The caller has already set the `checks_failed` flag for the function as a
/// whole, so emitting one entry per metric — even metrics without a limit —
/// does not change the exit-code semantics.
fn emit_check_failure_entries(
    reports: &mut Vec<CostReport>,
    package_name: &str,
    function: &str,
    func_config: &FunctionConfig,
) {
    for metric in ["CPU Instructions", "Read Bytes", "Write Bytes"] {
        let limit = limit_for_metric(func_config, metric);
        reports.push(CostReport {
            package: package_name.to_string(),
            function: function.to_string(),
            metric,
            value: None,
            limit,
            pass: Some(false),
            resource_limit: None,
            share_pct: None,
        });
    }
}

/// Formats a `u64` value with commas for readability and appends the
/// appropriate unit suffix (`inst.` for instructions, `B` for bytes).
///
/// # Arguments
///
/// * `value` - The raw numeric value to format.
/// * `metric` - The metric name; if it contains `"Bytes"` the suffix is
///   `B`, otherwise `inst.`.
fn format_with_commas_and_units(value: u64, metric: &str) -> String {
    format_value_with_share(value, metric, None, 0.0)
}

/// Formats a `u64` value with commas and unit suffix (`inst.` or `B`).
///
/// If `share_pct` is provided, it is appended as a percentage
/// (e.g. `"901,816 inst. (12.3%)"`). When `threshold > 0.0` and the
/// share exceeds it, a `" ⚠"` warning marker is appended.
fn format_value_with_share(value: u64, metric: &str, share_pct: Option<f64>, threshold: f64) -> String {
    let value_str = value.to_string();
    let mut result = String::new();
    let mut digit_count = 0;
    for ch in value_str.chars().rev() {
        if digit_count == 3 {
            result.push(',');
            digit_count = 0;
        }
        result.push(ch);
        digit_count += 1;
    }
    let formatted = result.chars().rev().collect::<String>();

    let base = if metric.contains("Bytes") {
        format!("{} B", formatted)
    } else {
        format!("{} inst.", formatted)
    };

    if let Some(pct) = share_pct {
        let mut s = format!("{} ({:.1}%)", base, pct);
        if threshold > 0.0 && pct > threshold {
            s.push_str(" ⚠");
        }
        s
    } else {
        base
    }
}

/// Extracts CPU instructions, read bytes, and write bytes from a
/// `simulateTransaction` JSON-RPC response.
///
/// The response must contain a `result.transactionData` field holding a
/// base64-encoded `SorobanTransactionData` XDR blob.
///
/// # Errors
///
/// Returns an error if the RPC response contains an `"error"` field, if
/// `transactionData` is missing or not a string, or if the base64 XDR
/// cannot be decoded.
fn extract_metrics(rpc_response: &serde_json::Value) -> Module10Result<(u32, u32, u32)> {
    if let Some(error) = rpc_response.get("error") {
        return Err(Error::Rpc(error.to_string()));
    }

    if let Some(error) = rpc_response.get("result").and_then(|r| r.get("error")) {
        let err_msg = error.as_str().unwrap_or("");
        if !err_msg.is_empty() {
            return Err(Error::Rpc(err_msg.to_string()));
        } else {
            return Err(Error::Rpc(error.to_string()));
        }
    }

    let tx_data_b64 = rpc_response["result"]["transactionData"]
        .as_str()
        .ok_or_else(|| Error::MissingField("transactionData".into()))?;

    // Decode the transaction data natively using the stellar-xdr crate
    // to avoid the overhead and instability of shelling out to the stellar CLI.
    let tx_data = SorobanTransactionData::from_xdr_base64(tx_data_b64, Limits::none())
        .map_err(|e| Error::Xdr(format!("Failed to decode SorobanTransactionData: {}", e)))?;

    Ok((
        tx_data.resources.instructions,
        tx_data.resources.read_bytes,
        tx_data.resources.write_bytes,
    ))
}

/// Builds the `stellar contract invoke --build-only -- <function> [args..]`
/// argument list for one exported function.
///
/// The resulting argument vector is passed directly to `Command::new("stellar")`.
///
/// # Arguments
///
/// * `contract_id` - The deployed contract ID (hex string).
/// * `source` - The Stellar source account keypair name.
/// * `network` - The target network passphrase or alias.
/// * `function` - The exported function name to invoke.
/// * `func_args` - Additional CLI arguments forwarded after the `--` separator.
fn build_invoke_args(
    contract_id: &str,
    source: &str,
    network: &str,
    function: &str,
    func_args: &[String],
) -> Vec<String> {
    let mut invoke_args = vec![
        "contract".to_string(),
        "invoke".to_string(),
        "--id".to_string(),
        contract_id.to_string(),
        "--source".to_string(),
        source.to_string(),
        "--network".to_string(),
        network.to_string(),
        "--build-only".to_string(),
        "--".to_string(),
        function.to_string(),
    ];
    invoke_args.extend(func_args.iter().cloned());
    invoke_args
}

/// Builds the JSON-RPC `simulateTransaction` request body for a base64 XDR
/// transaction envelope.
///
/// The request conforms to the Stellar JSON-RPC v2.0 specification and
/// contains a single `params.transaction` field with the base64-encoded
/// XDR envelope produced by `stellar contract invoke --build-only`.
///
/// # Arguments
///
/// * `b64_xdr` - The base64-encoded XDR transaction envelope.
fn build_rpc_payload(b64_xdr: &str) -> serde_json::Value {
    serde_json::json!({
        "jsonrpc": "2.0",
        "id": 1,
        "method": "simulateTransaction",
        "params": {
            "transaction": b64_xdr
        }
    })
}

/// POSTs a `simulateTransaction` JSON-RPC request for `b64_xdr` and returns
/// the parsed response body.
///
/// Uses `curl` to send the request to the Soroban RPC endpoint. The
/// request body is piped via stdin to avoid shell-quoting issues.
///
/// # Errors
///
/// Returns an error if `curl` cannot be spawned, the request fails, or
/// the response body is not valid JSON.
fn simulate_transaction_rpc(b64_xdr: &str, rpc_url: &str) -> Module10Result<serde_json::Value> {
    let rpc_payload = build_rpc_payload(b64_xdr);

    let mut curl = Command::new("curl")
        .args([
            "-s",
            "-X",
            "POST",
            "-H",
            "Content-Type: application/json",
            "-d",
            "@-",
            rpc_url,
        ])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()
        .map_err(|e| Error::CommandFailed(format!("failed to execute curl: {}", e)))?;

    {
        let stdin = curl
            .stdin
            .as_mut()
            .ok_or_else(|| Error::CommandFailed("Failed to open stdin".into()))?;
        stdin
            .write_all(rpc_payload.to_string().as_bytes())
            .map_err(|e| Error::CommandFailed(format!("failed to write to stdin: {}", e)))?;
    }

    let curl_output = curl
        .wait_with_output()
        .map_err(|e| Error::CommandFailed(format!("failed to read curl output: {}", e)))?;
    serde_json::from_slice(&curl_output.stdout)
        .map_err(|e| Error::Message(format!("Failed to parse RPC response: {}", e)))
}

/// Simulates one exported function end-to-end: runs
/// `stellar contract invoke --build-only` to build the transaction, then
/// POSTs it to `simulateTransaction` and decodes the reported resource
/// usage.
///
/// Returns `Err` only for a spawn/IO failure on the `stellar`/`curl` child
/// processes — the tool cannot proceed without those binaries. A
/// *recoverable* simulation failure (non-zero invoke exit, an RPC `error`
/// field, or an undecodable response) is reported as
/// `Ok(SimulationOutcome::Failed(..))` so the caller can move on to the next
/// function instead of aborting the whole report.
fn simulate_function(
    contract_id: &str,
    source: &str,
    network: &str,
    function: &str,
    func_args: &[String],
) -> Module10Result<SimulationOutcome> {
    let invoke_args = build_invoke_args(contract_id, source, network, function, func_args);
    let invoke_output = Command::new("stellar")
        .args(&invoke_args)
        .output()
        .map_err(|e| {
            Error::CommandFailed(format!("failed to execute stellar-cli invoke: {}", e))
        })?;

    if !invoke_output.status.success() {
        let stderr = String::from_utf8_lossy(&invoke_output.stderr).to_string();
        return Ok(SimulationOutcome::Failed(SimulationFailure::Invoke(stderr)));
    }

    let b64_xdr = String::from_utf8_lossy(&invoke_output.stdout)
        .trim()
        .to_string();
    let rpc_url = soroban_rpc_url(network)
        .unwrap_or("https://soroban-testnet.stellar.org:443");
    let rpc_resp = simulate_transaction_rpc(&b64_xdr, rpc_url)?;

    if let Some(error) = rpc_resp.get("error") {
        return Ok(SimulationOutcome::Failed(SimulationFailure::Rpc(
            error.to_string(),
        )));
    }

    match extract_metrics(&rpc_resp) {
        Ok((instructions, read_bytes, write_bytes)) => Ok(SimulationOutcome::Metrics {
            instructions,
            read_bytes,
            write_bytes,
        }),
        Err(err) => Ok(SimulationOutcome::Failed(
            SimulationFailure::MetricsExtraction(format!("{:#}", err)),
        )),
    }
}

/// Loads and parses a `budget.toml` configuration file.
///
/// If the file does not exist, returns a default (empty) configuration
/// so that callers can proceed without explicit error handling.
///
/// # Errors
///
/// Returns an error if the file exists but cannot be read or parsed.
fn load_budget_toml<P: AsRef<Path>>(path: P) -> Module10Result<BudgetToml> {
    match std::fs::read_to_string(&path) {
        Ok(contents) => {
            let trimmed = contents.trim();
            if trimmed.is_empty()
                || trimmed
                    .lines()
                    .all(|line| line.trim().is_empty() || line.trim_start().starts_with('#'))
            {
                return Ok(BudgetToml::default());
            }

            toml::from_str(&contents).map_err(Error::Toml)
        }
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => Ok(BudgetToml::default()),
        Err(err) => Err(Error::Io(err)),
    }
}

fn resolve_tolerance(cli_override: Option<&str>, config: &BudgetToml) -> Result<Tolerance> {
    if let Some(raw) = cli_override {
        return parse_tolerance(raw);
    }
    if let Some(t) = config.tolerance {
        return Ok(Tolerance::new(t));
    }
    Ok(Tolerance::default())
}

#[derive(serde::Serialize)]
struct CheckReportJson<'r> {
    has_regressions: bool,
    regression_count: usize,
    default_tolerance: f64,
    regressions: Vec<RegressionJson<'r>>,
    improvements: Vec<ImprovementJson<'r>>,
    new_entries: Vec<NewEntryJson<'r>>,
    stale_entries: Vec<StaleEntryJson<'r>>,
}

#[derive(serde::Serialize)]
struct RegressionJson<'r> {
    package: &'r str,
    function: &'r str,
    metric: &'r str,
    baseline: u64,
    current: u64,
    tolerance: f64,
    max_allowed: u64,
}

#[derive(serde::Serialize)]
struct ImprovementJson<'r> {
    package: &'r str,
    function: &'r str,
    metric: &'r str,
    baseline: u64,
    current: u64,
    tolerance: f64,
}

#[derive(serde::Serialize)]
struct NewEntryJson<'r> {
    package: &'r str,
    function: &'r str,
}

#[derive(serde::Serialize)]
struct StaleEntryJson<'r> {
    package: &'r str,
    function: &'r str,
}

fn render_check_report_json(
    report: &compare::CheckReport,
    default_tolerance: Tolerance,
) -> serde_json::Value {
    let mut regressions = Vec::new();
    let mut improvements = Vec::new();
    for func in &report.compared {
        for m in &func.metrics {
            match m.verdict {
                compare::Verdict::Regression => {
                    regressions.push(RegressionJson {
                        package: &func.package,
                        function: &func.function,
                        metric: m.metric.label(),
                        baseline: m.baseline,
                        current: m.current,
                        tolerance: m.tolerance.value,
                        max_allowed: max_allowed_metric(m.baseline, m.tolerance.value),
                    });
                }
                compare::Verdict::Improvement => {
                    improvements.push(ImprovementJson {
                        package: &func.package,
                        function: &func.function,
                        metric: m.metric.label(),
                        baseline: m.baseline,
                        current: m.current,
                        tolerance: m.tolerance.value,
                    });
                }
                compare::Verdict::Pass => {}
            }
        }
    }
    let new_entries: Vec<_> = report
        .new
        .iter()
        .map(|e| NewEntryJson {
            package: &e.package,
            function: &e.function,
        })
        .collect();
    let stale_entries: Vec<_> = report
        .stale
        .iter()
        .map(|e| StaleEntryJson {
            package: &e.package,
            function: &e.function,
        })
        .collect();
    let summary = CheckReportJson {
        has_regressions: report.has_regressions(),
        regression_count: report.regression_count(),
        default_tolerance: default_tolerance.value,
        regressions,
        improvements,
        new_entries,
        stale_entries,
    };
    serde_json::to_value(summary).expect("CheckReportJson serialization is infallible")
}

/// Scaffold a commented `budget.toml` template. Errors if the file already
/// exists and `force` is not set.
fn scaffold_init(force: bool, quiet: bool) -> Module10Result<()> {
    let path = Path::new("budget.toml");
    if path.exists() && !force {
        return Err(Error::Message(
            "budget.toml already exists; use --force to overwrite".into(),
        ));
    }
    std::fs::write(path, BUDGET_TOML_TEMPLATE)
        .map_err(Error::Io)?;
    eprintln!("Wrote {}", path.display());
    Ok(())
}

/// Run environment preflight checks before building or deploying.
///
/// Each check fails fast with an actionable error message. Checks that are
/// not applicable (e.g. rustup not installed) are silently skipped.
fn run_preflight_checks(quiet: bool) -> Module10Result<()> {
    // ── stellar CLI ─────────────────────────────────────────────────────
    if !quiet {
        eprint!("Checking Stellar CLI... ");
    }
    let stellar_check = Command::new("stellar").arg("--version").output();
    match stellar_check {
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            return Err(Error::Message(
                "Stellar CLI is not installed or not on PATH.\n\
                 Install it with:  cargo install --locked stellar-cli\n\
                 See: https://github.com/stellar/stellar-cli"
                    .to_string(),
            ));
        }
        Err(e) => {
            return Err(Error::CommandFailed(format!(
                "failed to execute stellar --version: {}",
                e
            )));
        }
        Ok(output) if !output.status.success() => {
            return Err(Error::CommandFailed(format!(
                "Stellar CLI failed to run.\n\
                 stderr: {}",
                String::from_utf8_lossy(&output.stderr)
            )));
        }
        Ok(_output) => {
            if !quiet {
                eprintln!("found");
            }
        }
    }
    // ── wasm32 target ───────────────────────────────────────────────────
    if !quiet {
        eprint!("Checking wasm32-unknown-unknown target... ");
    }
    let rustup_check = Command::new("rustup")
        .args(["target", "list", "--installed"])
        .output();
    match rustup_check {
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            // rustup is not installed — skip the check silently.
            if !quiet {
                eprintln!("skipped (rustup not found)");
            }
        }
        Err(e) => {
            return Err(Error::CommandFailed(format!(
                "failed to execute rustup: {}",
                e
            )));
        }
        Ok(output) => {
            let installed = String::from_utf8_lossy(&output.stdout);
            if installed
                .lines()
                .any(|line| line.trim() == "wasm32-unknown-unknown")
            {
                if !quiet {
                    eprintln!("found");
                }
            } else {
                return Err(Error::Message(
                    "wasm32-unknown-unknown target is not installed.\n\
                     Install it with:  rustup target add wasm32-unknown-unknown"
                        .to_string(),
                ));
            }
        }
    }

    Ok(())
}

/// Deploys a contract WASM to the network with automatic retry on
/// friendbot-related transient failures.
///
/// The `stellar contract deploy` command implicitly triggers friendbot
/// funding for the source account on testnet. Friendbot may return 429
/// (rate-limited) or the account may not be confirmed on-ledger yet.
/// This function makes up to `MAX_DEPLOY_ATTEMPTS` total attempts with
/// exponential backoff before giving up.
fn deploy_contract_with_retry(
    wasm_path: &Path,
    source: &str,
    network: &str,
    package_name: &str,
) -> Module10Result<String> {
    let mut last_error = String::new();

    for attempt in 0..MAX_DEPLOY_ATTEMPTS {
        if attempt > 0 {
            let delay = INITIAL_RETRY_DELAY_SECS * 2u64.pow(attempt - 1);
            eprintln!(
                "Deploy attempt {}/{} failed. Retrying in {} s...",
                attempt, MAX_DEPLOY_ATTEMPTS, delay
            );
            thread::sleep(Duration::from_secs(delay));
        }

        let deploy_output = Command::new("stellar")
            .args([
                "contract",
                "deploy",
                "--wasm",
                wasm_path
                    .to_str()
                    .ok_or_else(|| Error::Message("wasm path is not valid UTF-8".into()))?,
                "--source",
                source,
                "--network",
                network,
            ])
            .output()
            .map_err(|e| {
                Error::CommandFailed(format!("failed to execute stellar-cli deploy: {}", e))
            })?;

        if deploy_output.status.success() {
            let contract_id = String::from_utf8_lossy(&deploy_output.stdout)
                .trim()
                .to_string();
            return Ok(contract_id);
        }

        last_error = String::from_utf8_lossy(&deploy_output.stderr).to_string();
    }

    Err(Error::Message(format!(
        "Failed to deploy {} after {} attempts. Ensure your source account is funded.\nLast error: {}",
        package_name, MAX_DEPLOY_ATTEMPTS, last_error
    )))
}

fn main() -> anyhow::Result<()> {
    let CargoCli::BudgetReport(args) = CargoCli::parse();

    // ── --init: scaffold a template and exit ──────────────────────────
    if args.init {
        scaffold_init(args.force, args.quiet)?;
        return Ok(());
    }

    // ── Preflight environment checks ──────────────────────────────────
    run_preflight_checks(args.quiet)?;

    let toml_config = load_budget_toml("budget.toml")?;
    let default_tolerance = resolve_tolerance(args.tolerance.as_deref(), &toml_config)
        .context("failed to resolve tolerance")?;

    let mode = Mode::from_args(&args);

    let network = args
        .network
        .or(toml_config.network.clone())
        .context("missing --network or budget.toml network field")?;
    let source = args
        .source
        .or(toml_config.source.clone())
        .context("missing --source or budget.toml source field")?;

    let network_limits = get_network_limits(&network);

    if !args.quiet {
        eprintln!("Discovering workspace members...");
    }
    let metadata = MetadataCommand::new()
        .no_deps()
        .exec()
        .context("failed to execute cargo metadata")?;

    let mut reports = Vec::new();
    // `measurements` is the basis for both the legacy table output and the
    // snapshot/baseline modes. The BTreeMap ordering carries through to the
    // baseline file for stable PR diffs.
    let mut measurements: BTreeMap<String, BTreeMap<String, MeasuredResources>> = BTreeMap::new();
    let mut has_errors = false;
    let mut checks_failed = false;

    let build_profile = args.profile.as_deref().unwrap_or("release");

    for package in metadata.packages {
        let is_cdylib = package
            .targets
            .iter()
            .any(|target| target.crate_types.iter().any(|ct| *ct == "cdylib"));
        if !is_cdylib {
            continue;
        }

        if !args.quiet {
            eprintln!("Building package '{}' for wasm32...", package.name);
        }
        let build_status = Command::new("cargo")
            .args([
                "build",
                "-p",
                &package.name,
                "--target",
                "wasm32-unknown-unknown",
                "--profile",
                build_profile,
            ])
            .status()
            .context("failed to build package")?;

        if !build_status.success() {
            anyhow::bail!("Failed to build {}", package.name);
        }

        // Locate wasm
        let wasm_name = package.name.replace('-', "_");
        let wasm_path = metadata
            .target_directory
            .join("wasm32-unknown-unknown")
            .join(build_profile)
            .join(format!("{}.wasm", wasm_name));

        if !wasm_path.exists() {
            if !args.quiet {
                eprintln!("Warning: WASM not found at {}", wasm_path);
            }
            continue;
        }

        // Parse WASM exports
        let wasm_bytes = std::fs::read(&wasm_path)?;
        let wasm_size: u32 = wasm_bytes.len().try_into().unwrap_or(u32::MAX);
        let mut exported_fns: HashSet<String> = HashSet::new();

        for payload in WasmParser::new(0).parse_all(&wasm_bytes) {
            if let wasmparser::Payload::ExportSection(export_section) = payload? {
                for export_item in export_section {
                    let export_item = export_item?;
                    if export_item.kind == wasmparser::ExternalKind::Func {
                        let name = export_item.name.to_string();
                        // Ignore internal and common exports
                        if !name.starts_with('_') && name != "memory" {
                            exported_fns.insert(name);
                        }
                    }
                }
            }
        }

        if exported_fns.is_empty() {
            if !args.quiet {
                eprintln!("No exported functions found in {}", package.name);
            }
            continue;
        }

        let spinner = if args.quiet {
            None
        } else {
            let pb = ProgressBar::new_spinner();
            pb.set_style(
                ProgressStyle::default_spinner()
                    .tick_strings(&["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏", "✔"])
                    .template("{spinner:.green} Deploying contract {msg}...")
                    .unwrap(),
            );
            pb.set_message(package.name.to_string());
            pb.enable_steady_tick(std::time::Duration::from_millis(100));
            Some(pb)
        };

        let contract_id =
            deploy_contract_with_retry(wasm_path.as_std_path(), &source, &network, &package.name)?;

        if let Some(spinner) = spinner {
            spinner.finish_and_clear();
        }

        eprintln!("Contract deployed at: {}", contract_id);

        for function in exported_fns {
            if !args.quiet {
                eprintln!("Simulating function '{}'...", function);
            }

            let func_config = toml_config.functions.get(&function);
            let func_args = func_config.map(|cfg| cfg.args.clone()).unwrap_or_default();

            match simulate_function(&contract_id, &source, &network, &function, &func_args)? {
                SimulationOutcome::Metrics {
                    instructions,
                    read_bytes,
                    write_bytes,
                } => {
                    // Record the measurement for baseline/snapshot mode. This
                    // was previously only wired up in stale pre-refactor
                    // code; it belongs here in the success arm.
                    let measured = MeasuredResources {
                        instructions: instructions as u64,
                        read_bytes: read_bytes as u64,
                        write_bytes: write_bytes as u64,
                    };
                    measurements
                        .entry(package.name.clone())
                        .or_default()
                        .insert(function.clone(), measured);

                    // Build three CostReport entries for this function. In
                    // --check mode, attach the configured limit and
                    // pass/fail to each entry.
                    for (metric, value) in [
                        ("CPU Instructions", instructions),
                        ("Read Bytes", read_bytes),
                        ("Write Bytes", write_bytes),
                        ("WASM Bytes", wasm_size),
                    ] {
                        let limit = func_config.and_then(|cfg| limit_for_metric(cfg, metric));
                        let (entry_limit, pass) = evaluate_check(value, limit);
                        if pass == Some(false) {
                            checks_failed = true;
                        }
                        let (resource_limit, share_pct) = match metric {
                            "CPU Instructions" => (
                                Some(network_limits.max_instructions),
                                Some(value as f64 / network_limits.max_instructions as f64 * 100.0),
                            ),
                            "Read Bytes" => (
                                Some(network_limits.max_read_bytes),
                                Some(value as f64 / network_limits.max_read_bytes as f64 * 100.0),
                            ),
                            "Write Bytes" => (
                                Some(network_limits.max_write_bytes),
                                Some(value as f64 / network_limits.max_write_bytes as f64 * 100.0),
                            ),
                            _ => (None, None),
                        };
                        reports.push(CostReport {
                            package: package.name.to_string(),
                            function: function.clone(),
                            metric,
                            value: Some(value),
                            limit: entry_limit,
                            pass,
                            resource_limit,
                            share_pct,
                        });
                    }
                }
                SimulationOutcome::Failed(failure) => {
                    has_errors = true;
                    if !args.quiet {
                        match &failure {
                            SimulationFailure::Invoke(stderr) => {
                                eprintln!(
                                    "Warning: Simulation failed for {}: {}",
                                    function, stderr
                                );
                            }
                            SimulationFailure::Rpc(error) => {
                                eprintln!("Warning: RPC error for {}: {}", function, error);
                            }
                            SimulationFailure::MetricsExtraction(err) => {
                                eprintln!(
                                    "Warning: Failed to extract metrics for {}: {}",
                                    function, err
                                );
                            }
                        }
                    }
                    if let (true, Some(function_config)) = (args.check, func_config) {
                        // A configured function that won't simulate cannot
                        // satisfy any of its declared limits; record this as
                        // a check failure even if no `*_limit` is set on
                        // this row of budget.toml.
                        checks_failed = true;
                        emit_check_failure_entries(
                            &mut reports,
                            &package.name,
                            &function,
                            function_config,
                        );
                    }
                }
            }
        }
    }

    if measurements.is_empty() {
        if !args.quiet {
            eprintln!("No successful simulations to report.");
        }
        if has_errors || (args.check && checks_failed) {
            std::process::exit(1);
        }
        return Ok(());
    }

    // Per-function tolerance overrides from `budget.toml` (top-level plus
    // per-function). Built once so Mode::Check (baseline regression) and the
    // regular --check path below use the same input.
    let tolerance_overrides: BTreeMap<String, Tolerance> = toml_config
        .functions
        .iter()
        .filter_map(|(name, fc)| fc.tolerance.map(|t| (name.clone(), Tolerance::new(t))))
        .collect();

    // Re-shape the local `MeasuredResources` map into the `compare::Measurement`
    // shape so the baseline modes (`--record-baseline`, `--check-baseline`)
    // can hand it to `build_baseline` / `check_against_baseline` without a
    // second walk over the per-package data.
    let measurement_map: BTreeMap<String, BTreeMap<String, Measurement>> = measurements
        .iter()
        .map(|(pkg, fns)| {
            (
                pkg.clone(),
                fns.iter()
                    .map(|(name, m)| (name.clone(), m.as_compare()))
                    .collect(),
            )
        })
        .collect();

    match mode {
        Mode::Record(path) => {
            let baseline = build_baseline(&measurement_map);
            baseline
                .save(&path)
                .with_context(|| format!("failed to save baseline to {}", path.display()))?;
            eprintln!("Recorded baseline to {}", path.display());
            return Ok(());
        }
        Mode::Check(path) => {
            let baseline = Baseline::load(&path)
                .with_context(|| format!("failed to load baseline {}", path.display()))?;
            let report = check_against_baseline(
                &baseline,
                &measurement_map,
                default_tolerance,
                &tolerance_overrides,
            );
            if args.json {
                let json = render_check_report_json(&report, default_tolerance);
                println!(
                    "{}",
                    serde_json::to_string_pretty(&json).context("Failed to serialize JSON")?
                );
            } else {
                print!("{}", render_report_text(&report));
            }
            if report.has_regressions() {
                std::process::exit(1);
            }
            return Ok(());
        }
        Mode::Report => {} // Fall through to the legacy rendering below.
    }

    if args.csv {
        let mut csv_writer = csv::Writer::from_writer(std::io::stdout());
        if args.check {
            csv_writer
                .write_record(["package", "function", "metric", "value", "limit", "pass"])
                .context("Failed to write CSV header")?;
            for report in &reports {
                let value_str = report.value.map(|val| val.to_string()).unwrap_or_default();
                let limit_str = report.limit.map(|lim| lim.to_string()).unwrap_or_default();
                let pass_str = report.pass.map(|p| p.to_string()).unwrap_or_default();
                csv_writer
                    .write_record([
                        report.package.as_str(),
                        report.function.as_str(),
                        report.metric,
                        value_str.as_str(),
                        limit_str.as_str(),
                        pass_str.as_str(),
                    ])
                    .context("Failed to write CSV record")?;
            }
        } else {
            csv_writer
                .write_record(["package", "function", "metric", "value"])
                .context("Failed to write CSV header")?;
            for report in &reports {
                if report.value.is_some() {
                    let value_str = report.value.map(|val| val.to_string()).unwrap_or_default();
                    csv_writer
                        .write_record([
                            report.package.as_str(),
                            report.function.as_str(),
                            report.metric,
                            value_str.as_str(),
                        ])
                        .context("Failed to write CSV record")?;
                }
            }
        }
        csv_writer.flush().context("Failed to flush CSV writer")?;
    } else if args.json {
        let json_output =
            serde_json::to_string_pretty(&reports).context("Failed to serialize report to JSON")?;
        println!("{}", json_output);
    } else {
        // The plain text report path is preserved byte-for-byte when
        // `--check` is not passed: only entries with a measured value are
        // rendered in the table, and summary text is unchanged.
        println!("\n=== WORKSPACE BUDGET REPORT ===");
        let table_reports: Vec<TableCostReport> = reports
            .iter()
            .filter(|report| report.value.is_some())
            .map(|report| {
                let value = report.value.unwrap_or(0);
                let formatted = format_value_with_share(
                    u64::from(value),
                    report.metric,
                    report.share_pct,
                    args.share_threshold,
                );
                TableCostReport {
                    package: report.package.clone(),
                    function: report.function.clone(),
                    metric: report.metric,
                    value: formatted,
                }
            })
            .collect();
        let table = Table::new(table_reports).to_string();
        println!("{}", table);
        println!("\nSummary: The values above are simulated resource amounts, not fees. They are three of the inputs to the non-refundable resource fee.");
        println!("* Not measured: transaction size, ledger footprint entry counts, refundable fees (rent, events, return value), the inclusion fee, and therefore the total fee charged.");
        println!("* Note: These are simulated numbers on testnet and may vary slightly depending on ledger state.");
        println!("* See the \"Measurement scope\" section of the Tool Reference for what to use instead when you need those figures.");

        // Fixed: was `if check` — `check` is not in scope here, this needs
        // to read the CLI flag `args.check`.
        if args.check {
            println!("\n=== BUDGET CHECKS ===");
            let mut passed: usize = 0;
            let mut failed: usize = 0;
            for report in &reports {
                let Some(pass) = report.pass else {
                    continue;
                };
                let status = if pass { "PASS" } else { "FAIL" };
                let value_str = match report.value {
                    Some(v) => format_value_with_share(
                        u64::from(v),
                        report.metric,
                        report.share_pct,
                        args.share_threshold,
                    ),
                    None => "<simulation failed>".to_string(),
                };
                let limit_str = report
                    .limit
                    .map(|limit_val| {
                        // Limits wider than u32::MAX are not representable in
                        // the table's units, but anything close to the
                        // practical ceiling formats fine.
                        let display_value = u32::try_from(limit_val).unwrap_or(u32::MAX);
                        format_with_commas_and_units(u64::from(display_value), report.metric)
                    })
                    .unwrap_or_else(|| "-".to_string());
                println!(
                    "{}::{} [{}] value={} limit={} {}",
                    report.package, report.function, report.metric, value_str, limit_str, status
                );
                if pass {
                    passed += 1;
                } else {
                    failed += 1;
                }
            }
            println!("Summary: {} check(s) passed, {} failed", passed, failed);
        }
    }
    // PR #195: `--check` exits non-zero when any limit was breached so CI can
    // gate on the result. Mirrors the empty-measurements branch above.
    if args.check && checks_failed {
        std::process::exit(1);
    }
    Ok(())
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum Mode {
    Report,
    Record(PathBuf),
    Check(PathBuf),
}

impl Mode {
    fn from_args(args: &BudgetReportArgs) -> Self {
        if let Some(p) = &args.record_baseline {
            Mode::Record(PathBuf::from(p))
        } else if let Some(p) = &args.check_baseline {
            Mode::Check(PathBuf::from(p))
        } else {
            Mode::Report
        }
    }
}

#[cfg(test)]
mod module_8;

#[cfg(test)]
mod module_18;

/// Serializes tests that mutate the process working directory.
#[cfg(test)]
static TEST_CWD_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;
    use std::time::{SystemTime, UNIX_EPOCH};
    use stellar_xdr::curr::WriteXdr;

    const SHARED_BUDGET_TOML: &str = include_str!("../fixtures/shared_budget.toml");

    fn unique_test_path() -> PathBuf {
        let mut path = std::env::temp_dir();
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("system time is before UNIX_EPOCH")
            .as_nanos();
        path.push(format!("cargo_budget_report_test_{}.toml", nanos));
        path
    }

    // --- Network simulation loop helper tests ---

    #[test]
    fn build_invoke_args_without_function_args() {
        let invoke_args = build_invoke_args("CCONTRACT", "alice", "testnet", "do_work", &[]);
        assert_eq!(
            invoke_args,
            vec![
                "contract",
                "invoke",
                "--id",
                "CCONTRACT",
                "--source",
                "alice",
                "--network",
                "testnet",
                "--build-only",
                "--",
                "do_work",
            ]
        );
    }

    #[test]
    fn build_invoke_args_appends_function_args_after_separator() {
        let func_args = vec!["--n".to_string(), "10000".to_string()];
        let invoke_args = build_invoke_args("CCONTRACT", "alice", "testnet", "do_work", &func_args);
        assert_eq!(
            invoke_args,
            vec![
                "contract",
                "invoke",
                "--id",
                "CCONTRACT",
                "--source",
                "alice",
                "--network",
                "testnet",
                "--build-only",
                "--",
                "do_work",
                "--n",
                "10000",
            ]
        );
    }

    #[test]
    fn build_rpc_payload_wraps_xdr_in_simulate_transaction_request() {
        let payload = build_rpc_payload("AAAAAgAAAAA=");
        assert_eq!(payload["jsonrpc"], "2.0");
        assert_eq!(payload["method"], "simulateTransaction");
        assert_eq!(payload["params"]["transaction"], "AAAAAgAAAAA=");
    }

    #[test]
    fn build_rpc_payload_empty_xdr_is_still_well_formed() {
        let payload = build_rpc_payload("");
        assert_eq!(payload["params"]["transaction"], "");
    }

    // --- Metric extraction tests ---

    const FIXTURE_INSTRUCTIONS: u32 = 1_000_000;
    const FIXTURE_READ_BYTES: u32 = 2_048;
    const FIXTURE_WRITE_BYTES: u32 = 4_096;
    const FIXTURE_RESOURCE_FEE: i64 = 0;

    fn make_fixture_tx_data() -> SorobanTransactionData {
        use stellar_xdr::curr::{ExtensionPoint, LedgerFootprint, VecM};
        SorobanTransactionData {
            ext: ExtensionPoint::V0,
            resources: stellar_xdr::curr::SorobanResources {
                footprint: LedgerFootprint {
                    read_only: VecM::default(),
                    read_write: VecM::default(),
                },
                instructions: FIXTURE_INSTRUCTIONS,
                read_bytes: FIXTURE_READ_BYTES,
                write_bytes: FIXTURE_WRITE_BYTES,
            },
            resource_fee: FIXTURE_RESOURCE_FEE,
        }
    }

    fn fixture_rpc_response_json() -> serde_json::Value {
        let tx_data = make_fixture_tx_data();
        let b64 = tx_data
            .to_xdr_base64(Limits::none())
            .expect("failed to encode fixture SorobanTransactionData");
        serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "result": {
                "transactionData": b64
            }
        })
    }

    #[test]
    fn extract_metrics_from_programmatic_rpc_response() {
        let rpc_json = fixture_rpc_response_json();
        let (instructions, read_bytes, write_bytes) =
            extract_metrics(&rpc_json).expect("extraction should succeed");
        assert_eq!(instructions, FIXTURE_INSTRUCTIONS);
        assert_eq!(read_bytes, FIXTURE_READ_BYTES);
        assert_eq!(write_bytes, FIXTURE_WRITE_BYTES);
    }

    #[test]
    fn extract_metrics_from_fixture_file() {
        let fixture_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("fixtures")
            .join("simulate_transaction_response_valid.json");
        let fixture_json: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(&fixture_path).expect("failed to read fixture file"),
        )
        .expect("failed to parse fixture JSON");

        let meta = &fixture_json["_metadata"];
        assert_eq!(meta["network"].as_str(), Some("testnet"));
        assert!(meta["protocol_version"].as_u64().is_some());

        let (instructions, read_bytes, write_bytes) =
            extract_metrics(&fixture_json).expect("extraction from fixture should succeed");
        assert_eq!(instructions, FIXTURE_INSTRUCTIONS);
        assert_eq!(read_bytes, FIXTURE_READ_BYTES);
        assert_eq!(write_bytes, FIXTURE_WRITE_BYTES);
    }

    #[test]
    fn extract_metrics_fails_on_rpc_error() {
        let rpc_json = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "error": {
                "code": -32600,
                "message": "Invalid Request"
            }
        });
        let result = extract_metrics(&rpc_json);
        assert!(result.is_err());
        let err = format!("{:#}", result.as_ref().unwrap_err());
        assert!(
            err.contains("Invalid Request"),
            "error should mention the RPC error message, got: {}",
            err
        );
    }

    #[test]
    fn extract_metrics_fails_on_missing_transaction_data() {
        let rpc_json = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "result": {
                "some_other_field": "no transaction data here"
            }
        });
        let result = extract_metrics(&rpc_json);
        assert!(result.is_err());
        let err = format!("{:#}", result.unwrap_err());
        assert!(
            err.contains("transactionData"),
            "error should mention transactionData, got: {}",
            err
        );
    }

    #[test]
    fn extract_metrics_fails_on_invalid_xdr() {
        let rpc_json = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "result": {
                "transactionData": "this-is-not-valid-base64-xdr!!!"
            }
        });
        let result = extract_metrics(&rpc_json);
        assert!(result.is_err(), "extraction should fail on invalid XDR");
    }

    #[test]
    fn extract_metrics_from_malformed_fixture_file() {
        let fixture_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("fixtures")
            .join("simulate_transaction_response_malformed.json");
        let fixture_json: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(&fixture_path).expect("failed to read malformed fixture file"),
        )
        .expect("failed to parse malformed JSON");

        let result = extract_metrics(&fixture_json);
        assert!(
            result.is_err(),
            "extraction should fail on malformed response"
        );
        let err = format!("{:#}", result.unwrap_err());
        assert!(
            err.contains("No transaction data available"),
            "Expected specific error message"
        );
    }

    #[test]
    fn extract_metrics_from_cpu_exceeded_fixture_file() {
        let fixture_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("fixtures")
            .join("simulate_transaction_response_cpu_exceeded.json");
        let fixture_json: serde_json::Value = serde_json::from_str(
            &std::fs::read_to_string(&fixture_path)
                .expect("failed to read cpu exceeded fixture file"),
        )
        .expect("failed to parse cpu exceeded JSON");

        let result = extract_metrics(&fixture_json);
        assert!(
            result.is_err(),
            "extraction should fail on cpu exceeded response"
        );
        let err = format!("{:#}", result.unwrap_err());
        assert!(
            err.contains("CPU budget exceeded"),
            "Expected error to mention CPU budget exceeded, got: {}",
            err
        );
    }

    #[test]
    fn extract_metrics_fails_on_non_string_transaction_data() {
        let rpc_json = serde_json::json!({
            "jsonrpc": "2.0",
            "id": 1,
            "result": {
                "transactionData": 12345
            }
        });
        let result = extract_metrics(&rpc_json);
        assert!(
            result.is_err(),
            "extraction should fail when transactionData is not a string"
        );
    }

    // --- Budget toml loading tests ---

    #[test]
    fn missing_budget_toml_returns_default() {
        let path = unique_test_path();
        let _ = fs::remove_file(&path);

        let config = load_budget_toml(&path).expect("missing file should return default");
        assert!(config.network.is_none());
        assert!(config.source.is_none());
        assert!(config.functions.is_empty());
        assert!(config.tolerance.is_none());
    }

    #[test]
    fn empty_budget_toml_returns_default() {
        let path = unique_test_path();
        fs::write(&path, "\n\n").expect("failed to write empty budget.toml");

        let config = load_budget_toml(&path).expect("empty file should return default");
        assert!(config.network.is_none());
        assert!(config.source.is_none());
        assert!(config.functions.is_empty());
    }

    #[test]
    fn malformed_budget_toml_errors_with_parse_message() {
        let path = unique_test_path();
        fs::write(
            &path,
            "network = \"testnet\"\n[functions.do_expensive_work]\nargs = \"--n 10\"\n",
        )
        .expect("failed to write malformed budget.toml");

        let err = load_budget_toml(&path).unwrap_err();
        let err_text = err.to_string();

        assert!(
            err_text.contains("TOML error"),
            "expected TOML error in message, got: {}",
            err_text
        );
        assert!(err_text.contains("line") || err_text.contains("Line"));
        assert!(err_text.contains("column") || err_text.contains("Column"));
    }

    #[test]
    fn budget_toml_parses_global_and_per_function_tolerance() {
        let path = unique_test_path();
        fs::write(
            &path,
            "network = \"testnet\"\ntolerance = 0.10\n\
             [functions.do_expensive_work]\nargs = [\"--n\", \"10\"]\ntolerance = 0.05\n",
        )
        .expect("failed to write budget.toml");
        let config = load_budget_toml(&path).expect("parse should succeed");
        assert_eq!(config.tolerance, Some(0.10));
        let func = config
            .functions
            .get("do_expensive_work")
            .expect("function present");
        assert_eq!(func.tolerance, Some(0.05));
    }

    // --- Tolerance resolution ----------------------------------------------

    #[test]
    fn resolve_tolerance_precedence_cli_over_toml_over_default() {
        let config = BudgetToml {
            tolerance: Some(0.25),
            ..Default::default()
        };
        let t = resolve_tolerance(Some("0.42"), &config).expect("cli should win");
        assert!((t.value - 0.42).abs() < f64::EPSILON);

        let t = resolve_tolerance(None, &config).expect("toml should win");
        assert!((t.value - 0.25).abs() < f64::EPSILON);

        let empty = BudgetToml::default();
        let t = resolve_tolerance(None, &empty).expect("default should win");
        assert!((t.value - 0.10).abs() < f64::EPSILON);
    }

    #[test]
    fn resolve_tolerance_rejects_invalid_cli() {
        let config = BudgetToml::default();
        let err = resolve_tolerance(Some("nope"), &config)
            .unwrap_err()
            .to_string();
        assert!(err.contains("tolerance must be a number"), "got: {err}");
    }

    // --- Mode dispatch ------------------------------------------------------

    #[test]
    fn mode_defaults_to_report_when_no_flags() {
        let args = BudgetReportArgs {
            init: false,
            force: false,
            network: None,
            source: None,
            json: false,
            check: false,
            csv: false,
            record_baseline: None,
            check_baseline: None,
            tolerance: None,
            quiet: false,
            ..Default::default()
        };
        assert_eq!(Mode::from_args(&args), Mode::Report);
    }

    #[test]
    fn mode_distinguishes_record_and_check() {
        let record = BudgetReportArgs {
            init: false,
            force: false,
            network: None,
            source: None,
            json: false,
            check: false,
            csv: false,
            record_baseline: Some("budget-baseline.toml".to_string()),
            check_baseline: None,
            tolerance: None,
            quiet: false,
            ..Default::default()
        };
        assert_eq!(
            Mode::from_args(&record),
            Mode::Record(PathBuf::from("budget-baseline.toml"))
        );

        let check = BudgetReportArgs {
            init: false,
            force: false,
            network: None,
            source: None,
            json: false,
            check: false,
            csv: false,
            record_baseline: None,
            check_baseline: Some("custom.toml".to_string()),
            tolerance: None,
            quiet: false,
            ..Default::default()
        };
        assert_eq!(
            Mode::from_args(&check),
            Mode::Check(PathBuf::from("custom.toml"))
        );
    }

    #[test]
    fn shared_budget_toml_parses_with_foreign_sections() {
        let config: BudgetToml = toml::from_str(SHARED_BUDGET_TOML)
            .expect("shared budget.toml with foreign [lints] section should parse");
        assert_eq!(config.network.as_deref(), Some("testnet"));
        assert_eq!(config.source.as_deref(), Some("alice"));
        assert!(config.functions.contains_key("do_expensive_work"));
        assert!(config.functions.contains_key("require_auth_only"));
    }

    #[test]
    fn unknown_function_keys_produce_error() {
        let err =
            toml::from_str::<BudgetToml>("[functions.do_expensive_work]\ncpu_lmit = 5000000\n")
                .unwrap_err();
        let err_text = err.to_string();
        assert!(
            err_text.contains("unknown field") || err_text.contains("cpu_lmit"),
            "expected error mentioning unknown field or the offending key, got: {err_text}"
        );
    }

    #[test]
    fn known_function_key_spelling_produces_correct_deserialization() {
        let config: BudgetToml = toml::from_str(
            r#"
[functions.do_expensive_work]
cpu_limit = 5000000
read_limit = 5000
write_limit = 1000
"#,
        )
        .expect("valid function config should parse");
        let func = &config.functions["do_expensive_work"];
        assert_eq!(func.cpu_limit, Some(5000000));
        assert_eq!(func.read_limit, Some(5000));
        assert_eq!(func.write_limit, Some(1000));
    }

    // --- TransactionData deserialization tests ---

    #[test]
    fn transaction_data_parsing_deserializes_successfully() {
        let json_str = r#"{"resources": {"instructions": 1000, "disk_read_bytes": 2048, "write_bytes": 3072}}"#;
        let tx_data = TransactionData::parse_json(json_str).expect("Parsing should succeed");
        assert_eq!(tx_data.resources.instructions, 1000);
        assert_eq!(tx_data.resources.disk_read_bytes, 2048);
        assert_eq!(tx_data.resources.write_bytes, 3072);
    }

    #[test]
    fn transaction_data_parsing_fails_on_missing_field() {
        let json_str = r#"{"resources": {"instructions": 1000, "disk_read_bytes": 2048}}"#;
        let result = TransactionData::parse_json(json_str);
        assert!(result.is_err(), "Parsing should fail on missing field");
        let err_msg = format!("{:#}", result.unwrap_err());
        assert!(
            err_msg.contains("write_bytes"),
            "Error should mention missing field, got: {}",
            err_msg
        );
    }

    #[test]
    fn transaction_data_parsing_fails_on_non_numeric_field() {
        let json_str = r#"{"resources": {"instructions": "not-a-number", "disk_read_bytes": 2048, "write_bytes": 3072}}"#;
        let result = TransactionData::parse_json(json_str);
        assert!(result.is_err(), "Parsing should fail on non-numeric field");
        let err_msg = format!("{:#}", result.unwrap_err());
        assert!(
            err_msg.contains("invalid type") || err_msg.contains("not-a-number"),
            "Error should mention type mismatch, got: {}",
            err_msg
        );
    }

    // --- Cost value formatter tests ---

    #[test]
    fn formatter_zero_cpu() {
        assert_eq!(
            format_with_commas_and_units(0, "CPU Instructions"),
            "0 inst."
        );
    }

    #[test]
    fn formatter_zero_bytes() {
        assert_eq!(format_with_commas_and_units(0, "Read Bytes"), "0 B");
    }

    #[test]
    fn formatter_single_digit_cpu() {
        assert_eq!(
            format_with_commas_and_units(7, "CPU Instructions"),
            "7 inst."
        );
    }

    #[test]
    fn formatter_single_digit_bytes() {
        assert_eq!(format_with_commas_and_units(3, "Write Bytes"), "3 B");
    }

    #[test]
    fn formatter_just_below_thousand() {
        assert_eq!(
            format_with_commas_and_units(999, "CPU Instructions"),
            "999 inst."
        );
    }

    #[test]
    fn formatter_at_thousand() {
        assert_eq!(
            format_with_commas_and_units(1_000, "CPU Instructions"),
            "1,000 inst."
        );
    }

    #[test]
    fn formatter_just_above_thousand() {
        assert_eq!(
            format_with_commas_and_units(1_001, "CPU Instructions"),
            "1,001 inst."
        );
    }

    #[test]
    fn formatter_just_below_million() {
        assert_eq!(
            format_with_commas_and_units(999_999, "Read Bytes"),
            "999,999 B"
        );
    }

    #[test]
    fn formatter_at_million() {
        assert_eq!(
            format_with_commas_and_units(1_000_000, "CPU Instructions"),
            "1,000,000 inst."
        );
    }

    #[test]
    fn formatter_just_above_million() {
        assert_eq!(
            format_with_commas_and_units(1_000_001, "Write Bytes"),
            "1,000,001 B"
        );
    }

    #[test]
    fn formatter_ten_million() {
        assert_eq!(
            format_with_commas_and_units(10_000_000, "CPU Instructions"),
            "10,000,000 inst."
        );
    }

    #[test]
    fn formatter_u32_max_cpu() {
        assert_eq!(
            format_with_commas_and_units(u64::from(u32::MAX), "CPU Instructions"),
            "4,294,967,295 inst."
        );
    }

    #[test]
    fn formatter_u32_max_bytes() {
        assert_eq!(
            format_with_commas_and_units(u64::from(u32::MAX), "Read Bytes"),
            "4,294,967,295 B"
        );
    }

    #[test]
    fn formatter_write_bytes_gets_byte_unit() {
        assert_eq!(
            format_with_commas_and_units(4_096, "Write Bytes"),
            "4,096 B"
        );
    }

    #[test]
    fn formatter_non_bytes_metric_gets_inst_unit() {
        assert_eq!(
            format_with_commas_and_units(500, "Some Other Metric"),
            "500 inst."
        );
    }

    // --- CSV serialization tests ---

    /// Helper to serialize a slice of CostReport to CSV bytes and return the
    /// result as a String, using the same logic as the `--csv` output path.
    fn reports_to_csv(reports: &[CostReport], check: bool) -> String {
        let mut csv_writer = csv::Writer::from_writer(vec![]);
        if check {
            csv_writer
                .write_record(["package", "function", "metric", "value", "limit", "pass"])
                .unwrap();
            for report in reports {
                let value_str = report.value.map(|val| val.to_string()).unwrap_or_default();
                let limit_str = report.limit.map(|lim| lim.to_string()).unwrap_or_default();
                let pass_str = report.pass.map(|p| p.to_string()).unwrap_or_default();
                csv_writer
                    .write_record([
                        report.package.as_str(),
                        report.function.as_str(),
                        report.metric,
                        value_str.as_str(),
                        limit_str.as_str(),
                        pass_str.as_str(),
                    ])
                    .unwrap();
            }
        } else {
            csv_writer
                .write_record(["package", "function", "metric", "value"])
                .unwrap();
            for report in reports {
                if report.value.is_some() {
                    let value_str = report.value.map(|val| val.to_string()).unwrap_or_default();
                    csv_writer
                        .write_record([
                            report.package.as_str(),
                            report.function.as_str(),
                            report.metric,
                            value_str.as_str(),
                        ])
                        .unwrap();
                }
            }
        }
        csv_writer.flush().unwrap();
        String::from_utf8(csv_writer.into_inner().unwrap()).unwrap()
    }

    #[test]
    fn csv_output_without_check_has_four_columns() {
        let reports = vec![
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "CPU Instructions",
                value: Some(1_000_000),
                limit: None,
                pass: None,
                ..Default::default()
            },
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "Read Bytes",
                value: Some(2_048),
                limit: None,
                pass: None,
                ..Default::default()
            },
        ];
        let csv = reports_to_csv(&reports, false);
        let expected = concat!(
            "package,function,metric,value\n",
            "my-contract,do_work,CPU Instructions,1000000\n",
            "my-contract,do_work,Read Bytes,2048\n",
        );
        assert_eq!(csv, expected);
    }

    #[test]
    fn csv_output_with_check_has_six_columns() {
        let reports = vec![
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "CPU Instructions",
                value: Some(1_000_000),
                limit: Some(5_000_000),
                pass: Some(true),
                ..Default::default()
            },
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "Write Bytes",
                value: Some(4_096),
                limit: Some(1_000),
                pass: Some(false),
                ..Default::default()
            },
        ];
        let csv = reports_to_csv(&reports, true);
        let expected = concat!(
            "package,function,metric,value,limit,pass\n",
            "my-contract,do_work,CPU Instructions,1000000,5000000,true\n",
            "my-contract,do_work,Write Bytes,4096,1000,false\n",
        );
        assert_eq!(csv, expected);
    }

    #[test]
    fn csv_output_without_check_excludes_null_values() {
        let reports = vec![
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "CPU Instructions",
                value: None,
                limit: None,
                pass: None,
                ..Default::default()
            },
            CostReport {
                package: "my-contract".to_string(),
                function: "do_work".to_string(),
                metric: "Read Bytes",
                value: Some(2_048),
                limit: None,
                pass: None,
                ..Default::default()
            },
        ];
        let csv = reports_to_csv(&reports, false);
        let expected = concat!(
            "package,function,metric,value\n",
            "my-contract,do_work,Read Bytes,2048\n",
        );
        assert_eq!(csv, expected);
    }

    #[test]
    fn csv_output_with_check_includes_simulation_failures() {
        let reports = vec![CostReport {
            package: "my-contract".to_string(),
            function: "do_work".to_string(),
            metric: "CPU Instructions",
            value: None,
            limit: Some(5_000_000),
            pass: Some(false),
            ..Default::default()
        }];
        let csv = reports_to_csv(&reports, true);
        let expected = concat!(
            "package,function,metric,value,limit,pass\n",
            "my-contract,do_work,CPU Instructions,,5000000,false\n",
        );
        assert_eq!(csv, expected);
    }

    #[test]
    fn csv_output_empty_reports_produces_header_only() {
        let reports: Vec<CostReport> = vec![];
        let csv = reports_to_csv(&reports, false);
        assert_eq!(csv, "package,function,metric,value\n");
    }
}
